### ISSUE TITLE
(scite4autohotkey) Not silent

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1051]
This popsup:

![image](https://user-images.githubusercontent.com/85767/40979267-9e925b96-68d5-11e8-9628-6ef727e586ed.png)

**Comment by AdmiringWorm** [comment]
I guess we should classify this as a bug then.

Maybe a need to use autohotkey script to automate it?

**Comment by AdmiringWorm** [comment]
Still relevant I believe, but we need someone familiar with autohotkey to make this happen (IE, not me)

**Comment by majkinetor** [comment]
Looks like working now on second try. Probably some intermitient AHK issue as install script could be better. 

I will close this as there is no much interest in improving this and it kinda works...

Anyway, it would be much better to switch to portable package as then no AHK installer is needed.
