### ISSUE TITLE
(vscode) Add NoAutoUpdate parameter

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1063]
Currently package `visualstudiocode-disableautoupdate` does this.

Parameter is IMO better option because:

- We wont have problems like #1061
- Its easier to maintain, more DRY.
- Reinstalling main package generally may spoil dependent packages. This may not be the case here but generally it is a problem. Reinstalling app later leaves number of zombie packages related to previous install. This can't happen with parameters as they are remembered.

https://github.com/chocolatey/chocolatey-coreteampackages/pull/1061#issuecomment-398814838

/cc @AdmiringWorm  @pascalberger

**Comment by pascalberger** [comment]
This shouldn't be about which option is better as it is not an either/or decision. Both ways have their pros & cons. I've no objections about a parameter. If there's no interest to maintain the `visualstudiocode-disableautoupdate` package any longer here I would take maintainance over in another repo.

**Comment by majkinetor** [comment]
Its ok to have both options.
