### ISSUE TITLE
(Argusmonitor) checksums do not match and not in Gallery

### ISSUE THREAD

**Issue by tcinbis** [chocolatey-community/chocolatey-coreteampackages#1084]
https://chocolatey.org/packages/Argusmonitor

## Expected Behavior

Downloads and Installs Argus monitor software.
## Current Behavior

Crashes after download because checksums do not match and is missing in package gallery.
## Possible Solution

Update checksum.

## Steps to Reproduce (for bugs)

1. choco install argusmonitor

or
1. Check checksums by hand

**Comment by majkinetor** [comment]
Not sure how this tool got here but its invalid in total. 

I vote for removal from this repository here if it doesn't get fixed by somebody in next few weeks. 

While tool looks great, personally, I don't commit to exclusive commercial software/tools of any kind, but others might be interested. 

/cc @AdmiringWorm

**Comment by AdmiringWorm** [comment]
@majkinetor it got here because @p3lim opened a PR to add the package to this repo.
While we don't make commercial programs a priority, there isn't anything stopping it from being included in the repo as long as it matches the contribution guidelines.

**Comment by majkinetor** [comment]
> While we don't make commercial programs a priority, there isn't anything stopping it from being included in the repo as long as it matches the contribution guidelines.

Sure, but the package doesn't work ATM at all. If nobody fixes it in realistic time frame it will only contribute chaos and additional maintenance (like this issue).

**Comment by AdmiringWorm** [comment]
It is not relevant, since the package was rejected soon after submission.

@p3lim I will be removing the package from this repo in a few days, as there is no need for a package in this repository that isn't available on the community repo.
