### ISSUE TITLE
(chromium) Shows old version after update

### ISSUE THREAD

**Issue by lostmsu** [chocolatey-community/chocolatey-coreteampackages#1088]
After running choco update all, and getting the latest version of Chromium, it still launches the old version. In the C:\Program Files (x86)\Chromium\Application folder, I see subfolders 68.0.3440.84 and 66.0.3359.181. Also, I see chrome.exe dated 16.05.2018 and new_chrome.exe dated 01.08.2018.

I suspect this might be caused by some other program using Chromium (probably Steam).

I think I have rebooted the system since.

## Expected Behavior
The latest version of Chromium should launch after upgrade + restart (I am using chrome://restart)

## Current Behavior
The old version launches.

## Steps to Reproduce (for bugs)
It might be necessary to install Steam prior to installing Chromium from Chocolatey.
1. Install 66.* version of Chromium
2. Launch it and keep it running
3. choco upgrade chromium 
4. Navigate to chrom://restart to restart the browser or restart OS
5. Start Chromium, and check its version

## Your Environment
* Package Version used: 68.0.3440.84
* Operating System and version: Windows 10 April 2018 Update (Release)
* Chocolatey version: 0.10.11
* Install/uninstall gist: where to get it?

**Comment by lostmsu** [comment]
The issue is still present.

**Comment by RedBaron2** [comment]
@lostmsu 
Could you provide a gist of the chocolatey log file? This is not the normal behavior of the installer, but there might be a switch that is missing for the stable installer. -- I'm Checking on it --

**Comment by lostmsu** [comment]
@RedBaron2 This is the log, there are no apparent issues I could find: https://gist.github.com/lostmsu/16a6d66c92ac962031277e940d8adc19

As to the why question: I wanted to keep it up to date, so I have a Task Scheduler script, that tries to update it daily (only when my user is logged in), so that I would not have to manually track security fixes. It happens at the night time. It would be very inconvenient, if I had to be present. In fact, I'd have it auto-relaunch, if I figured how.

**Comment by RedBaron2** [comment]
@lostmsu  I've tested this, and it is not a problem of the Chocolatey package. The software is installed correctly, and completes with a error code of 0. The software detects a running chromium application and creates a new name for the newest executable by naming it `new_chrome.exe`. 

There are PowerShell ways to find running processes and then relaunch a program afterwards. I can give you a few suggestions of using something like this [script](https://gist.github.com/RedBaron2/7ccd4bc4d5b6355f4981a4cb6975f384) or even this [script](https://gist.github.com/RedBaron2/887d57cdb00e2a040937b6fdcff62ac4)

These are not fool proof they are concepts, and may damage more than help.

I recommend this issue be closed since it isn't a Package fault, but a case of a running app while updating.

**Comment by lostmsu** [comment]
@RedBaron2 at the very least, the issue should be forwarded to Chromium itself.

I'd also argue, that since the package is "core", it should be followed up right here. Imagine how many people would continue using vulnerable versions of Chromium, believing they are up to date, until they notice the version in About.

**Comment by AdmiringWorm** [comment]
I don't think there is much that the chromium developers could do either, but that is a different story.

Pretty much the only thing we can do here is to add a check if any process with the name chromium is running, and if it do we can throw an error to stop the upgrade.

Most likely though, I don't believe this will fix anything. Most likely, the process running don't have anything with chromium in the name.

Considering that, what would need to be done then is to check for **every** single known program that is known to use chromium behind the scenes.

This means, check for steam, origin, vscode, and pretty much every other application that makes use of the `electron` framework (*electron makes use of chromium*).
This is in impossible task unfortunately.

**Comment by lostmsu** [comment]
@AdmiringWorm what does Chrome do in this scenario? It looks like it shows a notification, and swaps executables upon relaunch. I can see that could be a problem when the unprivileged user does not have write access to the catalog, where chrome is installed. But I understand that could be worked around by simply launching new_chrome.exe upon chrome.exe start, if it is present.

Curiously, it seems, that Windows does not prevent executable files from being renamed while they are executing. So it might also be possible to just rename the old chrome.exe to old_chrome.exe, then create a new one. Would still need some kind of notification though.

**Comment by AdmiringWorm** [comment]
@lostmsu I could be wrong, but I believe chrome spawns a subprocess (a different program in this case) when the current version of chrome gets closed, which then replaces the current version of chrome.

**Comment by AdmiringWorm** [comment]
I believe that unless someone magically happens to come over a solution to this (unlikely), this issue will never be fixed.

As such, I will be closing this issue, If you disagree, or if someone wants to look into this, then feel free to comment and we can re-open this issue.
