### ISSUE TITLE
(winscp) Command-line utility has no shim

### ISSUE THREAD

**Issue by bryceschober** [chocolatey-community/chocolatey-coreteampackages#1134]
I installed the winscp package and was disappointed to see that it didn't make easily available (by shim) the winscp.com command-line utility. See [winscp executables](https://winscp.net/eng/docs/executables): The winscp.com, which isn't shimmed is the appropriate one for scripted usage.

**Comment by majkinetor** [comment]
Or just use [Set-AppKeyAlias](https://github.com/majkinetor/posh/blob/master/MM_Admin/Set-AppKeyAliases.ps1) and have it today including bunch of other utilities.

**Comment by AdmiringWorm** [comment]
@majkinetor which will only work when using `Win+R`, or if the session have been modified to make use of App Paths.

This won't make it available on the commandline by default.
