### ISSUE TITLE
(virtualbox) ExtensionPack - Oracle changed PUEL License

### ISSUE THREAD

**Issue by bobk-rey** [chocolatey-community/chocolatey-coreteampackages#1145]
It would be good to change the package to avoid installing the extension pack by default.

Oracle just hit us up for $6100 ($61 * minimum of 100 licenses).

About a year ago (between 5.1 and 5.2), Oracle snuck in changes to the PUEL license requiring a paid license if used in a commercial setting (vs previous stance of 'It doesn't matter whether you just use it for fun or run your multi-million euro business with it. Also, if you install it on your work PC at some large company, this is still personal use.')

Nov 2016: https://web.archive.org/web/20161108235524/https:/www.virtualbox.org/wiki/Licensing_FAQ
Jan 2017: https://web.archive.org/web/20170126161100/https://www.virtualbox.org/wiki/Licensing_FAQ
Dec 2017: https://web.archive.org/web/20171201035409/https://www.virtualbox.org/wiki/Licensing_FAQ

## Expected Behavior
Not get sent a bill by Oracle if a developer issues 'cinst virtualbox' without carefully reading the license.

## Current Behavior
Get sent a bill by Oracle.

## Possible Solution
Change the package defaults to skip the extension pack, and instead of arguments to opt-out of the extension pack, require arguments to opt-in.

## Steps to Reproduce (for bugs)
Download the extension pack via choco upgrade a number of times from a network address space that can be reverse looked up.
Wait for Oracle rep to come knocking with download logs.

**Comment by majkinetor** [comment]
LOL, this does smell Oracle so much.

We already have a parameter, its just a matter of reversing it.

**Comment by timjosborn** [comment]
We just got a call from Oracle. Same story. They said we'd installed 18 time. We said only 2 of them are active and we'd uninstall them. They said, too bad, you used it, you give us all your money, before our fiscal year end in 2 days...
We're going to try this: https://www.cdw.com/product/oracle-vm-virtbox-ent-nmd-user/2652849

**Comment by majkinetor** [comment]
OK, I will fix this because I don't want damn predators to get richer because of our free work. 

I can reverse the parameter or add a BIG NOTE about this problem.

I am a little bit hesitant to reverse a parameter as it changes behavior of existing installations.
What do you think @gep13 @AdmiringWorm ?

**Comment by gep13** [comment]
@majkinetor like you, I am hesitant to reverse the parameter, but part of me thinks that it might be the right thing to do ☹️

The warning will likely be missed, whereas something missing after installation will prompt the user to think about what has happened, and then make an informed decision about what to do now.

Interested to hear @AdmiringWorm thoughts on this.

**Comment by AdmiringWorm** [comment]
While I don't really like the idea of reversing the parameter, I unfortunately do see it as the best option for this, at least for now.

If we knew what conditions Oracle use to check if there is a commercial setting, we probably could skip the installation by default if we checked those conditions in the package.

**Comment by majkinetor** [comment]
OK, reversing the param then AND adding a note.

**Comment by majkinetor** [comment]
Done, not published (don't like to see fix versions honestly if I don't have to) Package is updated regularly so this will be online soon enough.

**Comment by madskristiansen** [comment]
I like your bug reporting skills. :P

Quite the blocker you found there.
