### ISSUE TITLE
(everything) Include everything.exe on the path

### ISSUE THREAD

**Issue by andrewsav-datacom** [chocolatey-community/chocolatey-coreteampackages#1153]
## Expected Behavior

I would like to be able to connect remotely to a box running Everything via command line ([OpenSSH](https://github.com/PowerShell/openssh-portable)) and with minimal hassle run command line search:

```powershell
es es.exe
```

I expect this to succeed.

## Current Behavior
Currently if you do that you will get:

```text
Everything IPC window not found, IPC unavailable.
```
Googling this message finds [this thread](https://www.voidtools.com/forum/viewtopic.php?t=5611). Software author suggests running a separate Client Service, but says that he does not know if it works. I was not able to make it work this way.

However if you run from command line:

```powershell
& 'C:\Program Files\Everything\Everything.exe'
es es.exe
```
Then it starts working. It's a bit tedious typing the whole `& 'C:\Program Files\Everything\Everything.exe'` every time you establish an ssh session, or even pasting it.

## Possible Solution

The chocolatey package should make sure that `Everything.exe` is on the system path. This way I will be able to reduce typing to just:

```powershell
everything
es es.exe
```

## Steps to Reproduce (for bugs)

1. Set up OpenSSH server. There are numerous guides in internet how to do this, I used parts of [this one](https://365adviser.com/powershell/install-use-openssh-windows-powershell-core-remoting-via-ssh/). In essence it's running `Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0` and then fiddling with setting as required.  
2. Install everything via chocolatey
3. Remotely connect to your server via ssh
4. Try running `es es.exe` observe failure
5. Try running `everything.exe` observe that it cannot be found without specifying the full path

## Your Environment

* Package Version used: everything 1.4.1895.20180530
* Operating System and version: Windows Server 2019 Core
* Chocolatey version: v0.10.11
* Install/uninstall gist: `cinst everything -y`

**Comment by majkinetor** [comment]
This is out of scope of chocolatey package I think. You can fix it easly by actually setting everything to run on remote machine as a service or by creating a function on remote machine.

**Comment by AndrewSav** [comment]
@majkinetor how do you mean out of scope? Most of the packages put whatever they install in the path, how is this one different?

**Comment by majkinetor** [comment]
> Most of the packages put whatever they install in the path, how is this one different?

This is actually not true. Most of the packages DO NOT put anything on PATH. Portable packages put stuff in bin folder, install packages usually dont, unless native installer does it.

I personally do not need this as I already have this option - everything registers as windows app in registry and you can use [Set-AppKeyAliases](https://github.com/majkinetor/posh/blob/master/MM_Admin/Set-AppKeyAliases.ps1). This will not work on remote location again as it must be set in profile.

Anyway, feel free to PR anytime if you want additional shim. I will mark this as enhacement. However, the ticket to update choco is here:

https://github.com/chocolatey/choco/issues/1072

and maybe it will be there in the future even without modifications of package.
