### ISSUE TITLE
(vscode) Introduce metapackage

### ISSUE THREAD

**Issue by pascalberger** [chocolatey-community/chocolatey-coreteampackages#1155]
## Expected Behavior
As there's also a vscode.portable package, we should rename the vscode package to vscode.install and introduce a new vscode metapackage with a dependency to vscode.install.

## Current Behavior
Currently there's a vscode package using the installer and a vscode.portable package

## Possible Solution

* Rename vscode to vscode.install
* Add vscode package with dependeny to vscode.install

## Context

See also this question on Disqus: https://chocolatey.org/packages/vscode#comment-4229298611

**Comment by AdmiringWorm** [comment]
adding this as an `Up for Grabs`, so if anyone is interested we would love a PR to add the metapackage.

**Comment by AdmiringWorm** [comment]
Still relevant

**Comment by majkinetor** [comment]
I don't think that this should be done at all. It will break current scripts because virtual package doesn't pass parameters to dependencies and vscode has lots of params. #1355

**Comment by AdmiringWorm** [comment]
@majkinetor meta packages do pass in parameters to the dependency, but only for `.install` and `.portable` dependency.

**Comment by majkinetor** [comment]
Didn't know that. Then its OK.

**Comment by jack1142** [comment]
Didn't know that either, I will have to update README file so that it won't say that you have to install `vscode.install` directly for it to work then. I'll do that and fix conflicts when I wake up. Let me know if there's anything else I should do.

**Comment by AdmiringWorm** [comment]
This is now available in the repository, however it won't be available on chocolatey.org until the next version of vscode is released.
