### ISSUE TITLE
(qTox) Qtox is outdated

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-coreteampackages#1182]
Package qTox is outdated. Maybe the automatic updater broke.

## Expected Behavior
repo has current version, 1.16.3 (2018-07-21)

## Current Behavior
repo has outdated version 1.14.1 (2018-04-03)

## Possible Solution
depends on what's broken. Maybe the package source changed (?)

## Context
Issue https://github.com/chocolatey/chocolatey-package-requests/issues/517 was raised. With this issue I attempt to reach the current maintainers according to the triage process.

Link to Package https://chocolatey.org/packages/qtox
Link to GitHub Repo https://github.com/qTox/qTox

## Your Environment
![image of chocolatey package version](https://user-images.githubusercontent.com/6533815/50839973-c76bd880-1361-11e9-8bd6-f8fbb487a312.png)
![image of GitHub versions of the package](https://user-images.githubusercontent.com/6533815/50840031-e10d2000-1361-11e9-948b-5209c9b87b93.png)

**Comment by majkinetor** [comment]
Updater looks at Jenkins builds here:

- https://build.tox.chat/view/qtox/job/qTox_pkg_windows_x86-64_stable_release/

Those are disabled, so we need to switch to Github releases which provide binaries for Windows for last couple of versions.

**Comment by JonasDralle** [comment]
so? What will be done here?
