### ISSUE TITLE
(everything) Package param REQ: add an additional switch to prevent service creation (ie. /no-service)

### ISSUE THREAD

**Issue by CollinChaffin** [chocolatey-community/chocolatey-coreteampackages#1187]
Package:  `everything`
https://chocolatey.org/packages/Everything

It is fairly common scenario where the addition/installation of the Everything service is not allowed/desired, especially in cases of Win7 where UAC is already disabled making it not only unnecessary, but also introducing the ability of all users gaining access to search data.

Since pretty much every other possible switch that is presented in the Everything installer is available for package installation, it appears the only one not available is the switch to prevent the service install so if one could be added (ie. /no-service) it would save substantial work it takes now post-install to launch Everything and use it's GUI options to then remove the unwanted service.

Thanks!

**Comment by majkinetor** [comment]
> but also introducing the ability of all users gaining access to search data.

Not terrible securrity issue really, given that you still can't access data.

It was like that BTW, but people had more problems with non service variant so I made it default. Its tones better to work as a service for everybody.

I wouldn't mind PR but I personally have 0 incentive to change this particularly as it can't be done with 5% of the brain in this case.
