### ISSUE TITLE
(virtualbox) - Upgrade hangs if virtualbox is open with no VMs running

### ISSUE THREAD

**Issue by noaho** [chocolatey-community/chocolatey-coreteampackages#1206]
## Expected Behavior
When virtualbox window is open, and I call choco upgrade virtualbox, It would be great if virtualbox is quit and the upgrade continues. eg:

"virtualbox is running, quitting virtualbox process."

## Current Behavior
However, it returns nothing from vboxmanage list runningvms, and the virtualbox window stays open, so the process hangs at "virtualbox is running, trying to gracefully shutdown any running machines" indefinitely. 

## Steps to Reproduce (for bugs)

1. choco install virtualbox --version 6.0
2. Launch virtualbox
3. choco upgrade virtualbox
4. ... Infinite wait. 

## Your Environment

* Package Version used: 6.0.2
* Operating System and version: Windows 10

**Comment by procdaddy11** [comment]
My issue is a bit different, but I still need the same functionality. I’m able to upgrade just fine, but it breaks my Guest OS every time.

Looks like it should be fairly easy to add using ManageVBox

Here is an example of it being done on Ubuntu

https://askubuntu.com/questions/42482/how-to-safely-shutdown-guest-os-in-virtualbox-using-command-line#42484
