### ISSUE TITLE
(mkvtoolnix) Won't upgrade from release 23.0.0 to 31.0.0

### ISSUE THREAD

**Issue by Argonaute** [chocolatey-community/chocolatey-coreteampackages#1220]
## Expected Behavior
Upgrade MKVToolnix version 23.0.0 to version 31.0.0

## Current Behavior
The package won't install with error

## Possible Solution
Uninstall the package manually from "Programs and Features"

## Steps to Reproduce (for bugs)
N/A

## Context
The transcript below :
```
PS C:\WINDOWS\system32> choco upgrade mkvtoolnix -y
Chocolatey v0.10.12-beta-3-gb65f586
Upgrading the following packages:
mkvtoolnix
By upgrading you accept licenses for the packages.
You have mkvtoolnix v23.0.0 installed. Version 31.0.0 is available based on your source(s).
mkvtoolnix not upgraded. An error occurred during installation:
Already referencing a newer version of 'chocolatey'.
mkvtoolnix package files upgrade completed. Performing other installation steps.
The upgrade of mkvtoolnix was NOT successful.
mkvtoolnix not upgraded. An error occurred during installation:
Already referencing a newer version of 'chocolatey'.
Chocolatey upgraded 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures

mkvtoolnix (exited 1) - mkvtoolnix not upgraded. An error occurred during installation:
Already referencing a newer version of 'chocolatey'.
```

## Your Environment

* Package Version used: MKVToolnix 31.0.0
* Operating System and version: Windows 10 Pro x64
* Chocolatey version: 10.11 and 10.12beta
* Install/uninstall gist: ?

**Comment by AdmiringWorm** [comment]
Most likely you have a stray lib directory for the `chocolatey` package which prevents the update.

Look in the following directory `%chocolateyInstall%\lib` and see if you have something similiar to the following directories in there:
```
chocolatey
chocolatey.0.10.11
chocolatey.0.10.12-beta-20181011`
```
If you have any of the last two directories, try deleting them (not the `chocolatey` directory). But do take a backup of those directories before deleting them, so you can restore them if something breaks.

**Comment by majkinetor** [comment]
I agree with above statement, it doesn't appear there is anything we can do here.
I will close this now, feel free to comment in future if you feel this is not adequate.
