### ISSUE TITLE
(gitextensions) Update problem

### ISSUE THREAD

**Issue by sboulianne** [chocolatey-community/chocolatey-coreteampackages#1221]
Hi,
Thanks for your great work but each time I want to upgrade gitextensions, the upgrade begin and my screen went black.
Explorer crash.
What is the cause ?
Is it a way to fix it ?

**Comment by majkinetor** [comment]
Can you provide log ?

**Comment by sboulianne** [comment]
Sorry for the delay sir.
I haven't receive your answer on my email.
I will choco upgrade gitextensions -debug this pm.

**Comment by majkinetor** [comment]
Closing this as there was no feedback. Feel free to reopen if that changes.
