### ISSUE TITLE
(spotify) Way Out Of Date

### ISSUE THREAD

**Issue by zero77** [chocolatey-community/chocolatey-coreteampackages#1229]
The Spotify package seems to be way out of date, the current chocolatey version is 1.0.80.474.
But, the latest version out is 1.1.0.237 also, from what i can see there isn't any errors.

https://chocolatey.org/packages/spotify

![untitled](https://user-images.githubusercontent.com/16563034/53018808-38b3a680-344b-11e9-8245-a4e24c8596c1.png)

**Comment by AdmiringWorm** [comment]
http://disq.us/p/1rgi22x

**Comment by zero77** [comment]
I have checked their and all packages listed are way out of date, including the packages marked " waiting for maintainer".

**Comment by AdmiringWorm** [comment]
@zero77 that link is a link to a specific disqus comment I made some time ago for why the spotify package is outdated and doesn't work correctly.

But let me quote it for you:
> From further testing, it actually seems it's random which installer you're getting.
> I got 2 different installers with different version numbers during my testing, curious if this is something they do on purpose, or if it's just a coincidence.
> Still, queued an update for the spotify package now, which should be pushed to chocolatey.org quite soon.
> Don't expect it to be automatically available yet though, as the automatic validator on chocolatey is down and packages won't be approved until it have ran successfully.

Basically, this means that unless the spotify developers start being consistent with the installer they supply, there won't be a working package and it will most likely always be outdated.

**Comment by zero77** [comment]
I missed that, thank you.

**Comment by AdmiringWorm** [comment]
I have opened the following issue to decide the future of the spotify package: #1273

Please join in with either voting on the solution, or discussing other alternatives.

I'll be closing this issue, to keep most things in that issue instead.
