### ISSUE TITLE
(sourcetree) AU update no longer working

### ISSUE THREAD

**Issue by pascalberger** [chocolatey-community/chocolatey-coreteampackages#1261]
## Expected Behavior
The AU script should update the Sourcetree package

## Current Behavior
Current version available from https://www.sourcetreeapp.com/enterprise is 3.1.2. But Atlassian has changed its page once again. The HTML page still contains links to 3.0.17 and the links to 3.1.2 are injected through JavaScript.

## Steps to Reproduce (for bugs)
1. Run update.ps1 for the Sourcetree package
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by 4nd3r5** [comment]
There is already a jira bug on this in the atlassian public bugtracking, but it seems like they do not update this tracker anymore.
https://jira.atlassian.com/browse/SRCTREEWIN-7045

**Comment by AdmiringWorm** [comment]
@pascalberger @4nd3r5 is there any kind of API that we can use to make this easier?
Assuming the program auto-updates (or auto-checks), can we piggyback on the same api?

**Comment by 4nd3r5** [comment]
it is somewhere on https://sourcetree-nps-bridge.us-east-1.prod.public.atl-paas.net, but that is all I can see from Fiddler.

**Comment by pascalberger** [comment]
@AdmiringWorm  We did this in the past (was changed with https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/8e364c1fd184721e3c4dea0dabc8f6629fdb89f2#diff-62f4977c124b3bb7b884f86a45c8c23d), but they changed installer and update with version 2. Also they have a staged rollout, so there was always discussions at what time the Chocolatey package should update (see discussions on the [package page](https://chocolatey.org/packages/SourceTree))

**Comment by AdmiringWorm** [comment]
@pascalberger here is the only thing I've found on the page that mentions any correct download location (formatted to make it easier to read)

```html
<script type="text/x-component">
{ 
	"type":"imkt.components.SourcetreeDownload",
	"params": { 
		"macURL":"https://product-downloads.atlassian.com/software/sourcetree/ga/Sourcetree_3.1.2_216.zip",
		"windowsURL":"https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourceTreeSetup-3.1.2.exe",
		"enterpriseURL":"https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourcetreeEnterpriseSetup_3.1.2.msi"
	}
} 
</script>
```

**Comment by AdmiringWorm** [comment]
They also do some funny looking replacements in the following javascript file: https://www.sourcetreeapp.com/assets/build/js/ad-hoc/sourcetree/homepage.min.js?cdnVersion=le (use some kind of javascript formatter to make it readable)

**Comment by RedBaron2** [comment]
@pascalberger @AdmiringWorm 
This seems to be the way some corporations are going for making their websites. The package wps-office-free uses a helper to read the javascript generated pages. I just tried this helper to read the sourcetree website, and it found a url the 3.1.2 version. I can work on a PR for it for later.

**Comment by AdmiringWorm** [comment]
a fix for this was merged just now.
https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/dc213b0a166b1527d13062ae5b02297084c68b23
