### ISSUE TITLE
(Mumble) missing Murmur server

### ISSUE THREAD

**Issue by kroppt** [chocolatey-community/chocolatey-coreteampackages#1264]
## Expected Behavior
Installing Mumble via choco gives access to both mumble.exe and murmur.exe

## Current Behavior
Installing Mumble via choco gives access to only mumble.exe

## Possible Solution
- Either include murmur.exe in the installation, or
- Create a separate package for Murmur

## Context
While Mumble currently satisfies what most people are looking for, it does not include the server for running a Mumble server. So, one cannot currently install Murmur using Chocolatey.

The installation medium includes Murmur. I looked through the scripts to figure out why Murmur was excluded in the final chocolatey directory, but I could not determine how it was being excluded; I do not have sufficient experience with PowerShell or the Chocolatey tools.

## Your Environment
* Package Version used: 1.2.19.20180702
* Operating System and version: Windows 10 Education version 1809 build 17763.437
* Chocolatey version: 0.10.13
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
Seems like they have included the server in the installer, but they haven't enabled it by default.

You can include the installation of the server by installing mumble with the following:
`choco install mumble --ia "ADDLOCAL=ALL"`

We should probably add a package parameter to help with this in future packages (probably not installing the server by default though)

**Comment by kroppt** [comment]
Yes, adding a flag for the package makes a lot of sense. The above worked. Thanks.

**Comment by AdmiringWorm** [comment]
@kroppt this have now been implemented in the source, and will be available when the next version of mumble is released.
