### ISSUE TITLE
(bleachbit / bleachbit.install) Outdated

### ISSUE THREAD

**Issue by Technetium1** [chocolatey-community/chocolatey-coreteampackages#1269]
## Current Behavior
Installs version 2.0

## Possible Solution
Install version 2.2

## Context
The 2.2 installer [was released on March 20, 2019](https://www.bleachbit.org/news/bleachbit-22)

**Comment by AdmiringWorm** [comment]
There is a open PR to fix this: #1249 
Unfortunately, due to the amount of changes in the PR, I have not yet had the time to review it :cry:

**Comment by majkinetor** [comment]
https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/de0751a90a3f756e6b8f5d56f575ae3ed43dd9b6#pushed
