### ISSUE TITLE
(mkdocs) Package fails if older version of pip is installed 

### ISSUE THREAD

**Issue by andmos** [chocolatey-community/chocolatey-coreteampackages#1271]
👋 Hi, 

It seems like the `mkdocs` package throws some kind of exitcode if the installed version of `pip` is outdated. `choco install mkdocs` goes fine, but at the end, it prints 
```shell
"You are using pip version 9.0.1, however version 19.1 is available.", "You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
This is failing the installation. Have also tried running
```shell
choco install mkdocs --ignore-package-exit-codes
```
With same result.

## Expected Behavior
Package should not break install on non-critical message from `pip`.

## Current Behavior
```shell
choco install mkdocs
Chocolatey v0.10.11
Installing the following packages:
mkdocs
By installing you accept licenses for the packages.
Progress: Downloading mkdocs 1.0.4... 100%

mkdocs v1.0.4 [Approved]
mkdocs package files install completed. Performing other installation steps.
The package mkdocs wants to run 'ChocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Requirement already satisfied (use --upgrade to upgrade): mkdocs==1.0.4 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): click>=3.3 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from mkdocs==1.0.4)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7.1 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from mkdocs==1.0.4)
Requirement already satisfied (use --upgrade to upgrade): Markdown>=2.3.1 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from mkdocs==1.0.4)
Requirement already satisfied (use --upgrade to upgrade): livereload>=2.5.1 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from mkdocs==1.0.4)
Requirement already satisfied (use --upgrade to upgrade): tornado>=5.0 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from mkdocs==1.0.4)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from mkdocs==1.0.4)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.23 in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from Jinja2>=2.7.1->mkdocs==1.0.4)
Requirement already satisfied (use --upgrade to upgrade): six in c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (from livereload>=2.5.1->mkdocs==1.0.4)
You are using pip version 7.1.2, however version 19.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

The install of mkdocs was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\mkdocs\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - mkdocs - Error while running 'C:\ProgramData\chocolatey\lib\mkdocs\tools\ChocolateyInstall.ps1'.
 See log for details.
```

## Steps to Reproduce (for bugs)
Have a system with older version of `pip`, then run `chocolatey install mkdocs`.

## Context
We have some 10 buildservers we provision out with `Ansible` and `Chocolatey`, using `state=latest` to pick latest version of `mkdocs`. We should be able to pick latest version of `mkdocs` without upgrading `pip` first.

## Your Environment

* `1.0.4`
* `Windows 10`, `Windows Server 2012 R2`, `Windows Server 2016`
* Chocolatey version `0.10.11`

**Comment by AdmiringWorm** [comment]
I'm unable to reproduce this with a standard installation of chocolatey.
So I believe that most likely you have the the feature `failOnStandardError` enabled (or possibly some other feature I can't think of right now).

By default, chocolatey only marks the installation as failed if an exit code of anything other than zero is set in this package (which don't seem to be the case in my tests), or if the previously mentioned feature is enabled (or the argument `--failonstderr` is used) when anything is written to the error output.

**Comment by AdmiringWorm** [comment]
Most likely, the chocolatey logs (`C:\ProgramData\chocolatey\logs\chocolatey.log`) should tell you more about why the installation was considered a failure

**Comment by andmos** [comment]
Yeah looks like you are correct. From the logs:
```
Features.FailOnStandardError='True'|Features.UsePowerShellHost='True'|
```

Just to be clear, `--ignore-package-exit-codes` and `--failonstderr` have nothing to do with each other right? Might be what I missed then.

**Comment by AdmiringWorm** [comment]
That is correct. The only thing that `--ignore-package-exit-codes` do, is to instead of chocolatey returning the exit codes gotten from the package, it will instead return either `0` or `1`. That is the only thing that argument do.
