### ISSUE TITLE
(chromium) 64-bit chromium is installed under WoW64 Program Files (x86)

### ISSUE THREAD

**Issue by wesinator** [chocolatey-community/chocolatey-coreteampackages#1275]
## Expected Behavior

64-bit chromium installs under `%PROGRAMFILES%`

## Current Behavior

64-bit chromium installed under `%PROGRAMFILES(X86)%`

Is there a reason why it is placed under the WoW64 Program files dir ?

## Steps to Reproduce (for bugs)

1. choco install chromium
![image](https://user-images.githubusercontent.com/5124946/57199112-4efcd900-6f49-11e9-89e5-9064463e4890.png)

## Context

_Originally posted by @AeliusSaionji in https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/238#issuecomment-235787365_

## Your Environment

* Package Version used: v74.0.3729.131
* Operating System and version: Windows 8.1 Pro x64
* Chocolatey version: 0.10.13
* Install/uninstall gist:

**Comment by AeliusSaionji** [comment]
Yeah, it's wrong but the fault lies with the upstream installer.

It is probably possible for this to be forcibly corrected by chocolatey,  though it's probably not wise to create a circumstance which is unique to a chocolatey install unless absolutely necessary.

**Comment by wesinator** [comment]
> Yeah, it's wrong but the fault lies with the upstream installer.

Ah, yea - https://bugs.chromium.org/p/chromium/issues/detail?id=380177
