### ISSUE TITLE
(classic-shell) archive automatic updater 

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1283]
Classic shell is not maintained any more so it should be removed since it is embedded package.

Now it is open-shell and looks like not worked-on too much:
https://github.com/Open-Shell/Open-Shell-Menu

I am not sure what should be done with the folder, but perhaps its the best idea to simply delete/rename update.ps1 so that links to package source still work, and update README.md (without pushing a fix version)

Any thoughts ?

/cc @AdmiringWorm @gep13

**Comment by gep13** [comment]
@majkinetor hmmm, I am honestly not sure what to do for the best here.

Perhaps we should move the packaging files to a new `archived` (naming is hard!) folder, similar to the deprecated folder that we have.  That way, if those files are required again, they an easily be retrieved, rather than digging into history of project.

**Comment by majkinetor** [comment]
OK, lets call such packages ***archived*** then.

Moving the archived package will invalidate older version metadata URLs which is not nice.

> That way, if those files are required again, they an easily be retrieved, rather than digging into history of project.

There is no need for delition - only `update.ps1` needs to be renamed (and README.md updated to show the current status).

If archived package is needed again, there is no need to search history - you can simply rename updater again and do your work.

**Comment by AdmiringWorm** [comment]
> Moving the archived package will invalidate older version metadata URLs which is not nice.

Well, one way to not have the older versions have invalid urls, would be to add a symlink to the new location.
But, I do agree with you that just renaming `update.ps1` and update the README.md would probably be for the best.

**Comment by gep13** [comment]
>@majkinetor said...
Moving the archived package will invalidate older version metadata URLs which is not nice.

Ah, that is a good point.

>@majkinetor said...
There is no need for delition - only update.ps1 needs to be renamed

When you said this:

>@majkinetor said...
more so it should be removed 

I thought you meant removing everything.  If we are just renaming the file, then I would agree with that as a solution going forward.
