### ISSUE TITLE
Scheduled AV build not working

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1284]
https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1273#issuecomment-494035818
> @gep13 hmm, it is odd that the schedule doesn't run then.
> I've been triggering it manually for the past few days because it didn't run.

**Comment by majkinetor** [comment]
Looks like it stopped 2 days ago.

**Comment by AdmiringWorm** [comment]
@majkinetor it stopped long before then, I've been manually running them now and then for some time now.

**Comment by majkinetor** [comment]
Even linux platforms could work as it looks like AU works on pwsh without problems.

Gitlab too is an option to although it requires setup of git mirror.

@pascalberger Isn't AV on Azure ? What are limitations on Azure ? 

AV can be easily fixed by using external scheduler... 

Any potential replacement should be thought out from the perspective of the entire AU community and not only this repo, as major point of current AU system is that everybody can use it in the same manner.

**Comment by pascalberger** [comment]
> Isn't AV on Azure ? What are limitations on Azure ?

My issues was that builds in the free-tier can only run up to 60 min, which was not enough time for the build to download a 400 MB file and calculate the checksum. Beside that Azure DevOps doesn't have any limitation on run time, it seems to have also much faster network connectivity in my case. Maybe it was just a temporary issues on AppVeyor.

I don't see how this affects AU (beside the report generation where it adds an AppVeyor badge). But otherwise it's the same scripts running and choice of build server shouldn't have any impact on migraton of package between different repos using AU, even with different build servers.

**Comment by majkinetor** [comment]
> My issues was that builds in the free-tier can only run up to 60 min, which was not enough time for the build to download a 400 MB file and calculate the checksum.

System that can not download 400 MB in an hour in 2019 is not usable in general sense. Are you sure this is not a problem of different nature.

> I don't see how this affects AU

It doesn't affect AU - it affects AU community as it adds complexity. 
Are you willing to create a wiki page pandan to the one we have now for [AV](https://github.com/majkinetor/au/wiki/AppVeyor)?

We also need build templates pandan to `.appveyor.yaml`.

The point is to make on-boarding as quick as possible, otherwise, some of the maintainers may lose patience and revert to local run which will stop working sooner or later.

> beside the report generation where it adds an AppVeyor badge

Report plugin has a type parameter which you can use for example to have textual reports without badge. Each type also has its own parameters so its easy to create badges based on other providers and you could even disable badge and let users specify whatever in custom text that is among `updateall` options.

**Comment by gep13** [comment]
I was informed that it had been enabled here:

https://twitter.com/appveyor/status/1130581959225163776?s=21

**Comment by AdmiringWorm** [comment]
@gep13 can you confirm that the schedule is still set on on the correct build vm? (https://ci.appveyor.com/project/chocolateycommunity/chocolatey-coreteampackages).
I don't have access to the settings so I can not see it myself (I'm thinking it perhaps got removed when they enabled the schedule, I know that happened on my own repository).

**Comment by gep13** [comment]
From what I can see, yes.

![image](https://user-images.githubusercontent.com/1271146/58408892-ca443d00-8066-11e9-89dc-315102b5eb0c.png)

I am going to modify it slightly and re-save the setting, to see if that has any effect.

**Comment by gep13** [comment]
@AdmiringWorm I have just re-saved the settings.  There wasn't any error when I did this, which tells me that scheduled builds are enabled, as I got an error the first time I tried to create the schedule.  Let's see if this helps any...

**Comment by AdmiringWorm** [comment]
@gep13 seems like that change fixed the issue with the schedule.
I see a scheduled build that ran ~3 hours ago: https://ci.appveyor.com/project/chocolateycommunity/chocolatey-coreteampackages/builds/24835994#L163

**Comment by gep13** [comment]
@AdmiringWorm nice one, thank you for confirming!
