### ISSUE TITLE
(msys2) Currently failing the verifier

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-coreteampackages#1286]
## Expected Behavior

The package should pass the automated verifier, or if needed get an exemption added.

## Current Behavior

Fails the automated testing.

## Possible Solution

Not looked into

## Context

Gist of the failures: https://gist.github.com/a592dc820e2b0bcaeb928f20ff7a4aec

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by jayvdb** [comment]
@diablodale , you posted a bunch of notes on the choco site, including this issue I believe, which you have already fixed at https://github.com/diablodale/gnucash-dev-docker/blob/master/windows.dockerfile#L42

**Comment by diablodale** [comment]
Yes. I have fixes that work in my scenarios. Unfortunately, the authors of the choco package have not responded to my suggestions.

**Comment by jayvdb** [comment]
Submit at PR here ? source at https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/msys2

**Comment by diablodale** [comment]
Hi. I don't mind helping. I'll have time during week of the 17th this month.

**Comment by diablodale** [comment]
Starting to look into this.
