### ISSUE TITLE
(itunes) Split Apple Application Support into sub package

### ISSUE THREAD

**Issue by Jnchi** [chocolatey-community/chocolatey-coreteampackages#1287]
## Expected Behavior

I wish to see Apple Application Support (32-bit, and 64-bit), and Apple Mobile Device Support, split out into a separate (sub) package, if possible.

## Current Behavior

One must install iTunes, and Bonjour in order to have the desired libraries.

## Context

I'd like to install and manage [iExplorer](https://macroplant.com/iexplorer/tutorials/how-to-install-iexplorer) via puppet using the chocolatey module.

**Comment by majkinetor** [comment]
This can be done. I personally do not care about itunes or any Mac stuff.
PR would be the quickest approach.
