### ISSUE TITLE
AU error report 2019-06

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1289]
Following packages should be fixed due to upstream changes:

- [ ] krita  (change so x32 version uses online download while x64 is embedded)
- [x] [codelite](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/be84e7a53aa8d8557e21436d22f88a4b5d74ac6f#codelite)
- [x] [brave (ignore invalid stream)](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#brave)

For krita decision is required - current package is embedded but new package would have ~205MB which probably means that we either have to unenbeddit or remove x32 bit version. My vote goes to removing x32 bit version because those are slowly being removed universally and because actual download shows only x64 bit version (and after all, this is graphic program and x32 OS is nota good idea for such tools).

/cc @AdmiringWorm @gep13

**Comment by AdmiringWorm** [comment]
I have actually been thinking a little about the krita package.

What I have been thinking about is to convert the package to a partial embedded package, embedding the 64 bit binary, but if 32bit is requested then download that one. I haven't really looked into this though, as I have other priorities right now, but I do not believe it would add too much complexity to the package (the update script may be a different matter though).

Thoughts?

**Comment by majkinetor** [comment]
I think that is great idea.

**Comment by gep13** [comment]
>@majkinetor said...
I think that is great idea.

Totally agree here!

**Comment by AdmiringWorm** [comment]
@majkinetor great work, and thanks for taking care of those packages.

Was planning to look into the krita package today, but I am glad that I didn't have to. have a :chocolate_bar:
