### ISSUE TITLE
(cygwin) Cygwin sets unusal permissions on ChocolateyToolsLocation if installed before other packages

### ISSUE THREAD

**Issue by tylerszabo** [chocolatey-community/chocolatey-coreteampackages#1291]
## Expected Behavior

Cygwin is installed under `$env:ChocolateyToolsLocation\cygwin` and the `$env:ChocolateyToolsLocation` directory has the same permissions it would have if another script were creating it.

## Current Behavior

If the Cygwin installer creates the `$env:ChocolateyToolsLocation` directory it's permissions will be set according to [Cygwin's mapping of POSIX permissions to Windows SIDs](https://www.cygwin.com/cygwin-ug-net/ntsec.html#ntsec-mapping).

## Possible Solution

Explicitly create `$env:ChocolateyToolsLocation` in the `chocolateyInstall.ps1` script if it doesn't exist and is going to be used before running the Cygwin installer.

## Steps to Reproduce (for bugs)

1. Remove cygwin (if installed)
2. Remove or rename the `$env:ChocolateyToolsLocation` directory
3. Install cygwin
4. Observe permissions of `$env:ChocolateyToolsLocation`

## Context

I was attempting to install a tool that installs from MSI to `$env:ChocolateyToolsLocation`. I think some installers will still succeed because Cygwin leaves it writable to the current user but `msiexec` runs as SYSTEM. 

## Your Environment

* Package Version used: `3.0.7`
* Operating System and version: Windows 10 Professional `10.0.17763.529`
* Chocolatey version:
* Install/uninstall gist:

**Comment by majkinetor** [comment]
I used chocolatey test environment with the following script to test this. I used the same script 2 times, once with cygwin package and once with tcp-linkinfo package.

```
Start-Transcript c:\dbg_cygwin.txt

$dir = $env:ChocolateyToolsLocation
if (Test-Path $dir) { rm -Recurse -Force 

[Uploading dbg_linkinfotxt.txt…]()

$dir }

cinst cygwin -f

Get-NTFSSimpleAccess $dir | ft -au
Get-NTFSAccess $dir | ft -au
Get-NTFSEffectiveAccess $dir | ft -au
Get-NTFSOwner $dir  | ft -au

Stop-Transcript
```

Here is the diff: https://ibb.co/KjYw2k8

It confirms your conclusion.
