### ISSUE TITLE
Make it very clear that the `putty` package is non-standard

### ISSUE THREAD

**Issue by jacktose** [chocolatey-community/chocolatey-coreteampackages#1293]
It seems clear from #1177 that [putty] will continue to install [putty.portable] for backwards compatibility.
It's also clear from the repeated issues, comments, etc., and the FAQ, that users expect it to install [putty.install], as with most packages.

Therefore, we should make every effort to clarify that [putty] violates that expectation, and to direct users to consider [putty.install].
I think it warrants highly visible text on at least [putty]'s web page, `choco info` text, and installer output.

[putty]: https://chocolatey.org/packages/putty
[putty.portable]: https://chocolatey.org/packages/putty.portable
[putty.install]: https://chocolatey.org/packages/putty.install

**Comment by joel0** [comment]
I agree with this!  When I was new to Chocolatey, I assumed something went wrong with the putty install or that the package was broken when the Start menu entry was missing.  It took a long time to understand that the dependency of putty.portable found below the fold was the "problem".

**Comment by majkinetor** [comment]
Added to meta package notes, will be public after next update.

**Comment by ExE-Boss** [comment]
You might want to merge #1331 before then.

**Comment by jacktose** [comment]
The note is nice, but I disagree that it resolves my issue.

> I think it warrants highly visible text on at least putty's web page, choco info text, and installer output.

Most people aren't going to read all the notes before installing.

**Comment by cinderblock** [comment]
Still think the correct solution is to make `putty` depend on `putty.install` like nearly every other Chocolately package.
