### ISSUE TITLE
(ruby) Add packages for the different major versions

### ISSUE THREAD

**Issue by tas50** [chocolatey-community/chocolatey-coreteampackages#1298]
Add packages for the different major versions

## Expected Behavior
I should be able to install Ruby 2.4, 2.5, or 2.6 instead of just the latest Ruby. A lot of people have applications that need a certain Ruby version to run.

## Current Behavior
Right now the package is just the latest Ruby.

## Possible Solution
Create a ruby24, ruby25, and ruby26 package in addition to the current package. That way someone that wants the latest can just install "ruby".

## Steps to Reproduce (for bugs)
1. Install ruby package
2. Notice it's not 2.5

## Context
N/A

## Your Environment
N/A

**Comment by AdmiringWorm** [comment]
I must have missed this when it was initially posted.
But let me say my opinion on the matter.

I strongly disagree with having multiple packages only for the usage of specific major/minor packages, if you want a polluted repository with duplicated packages, then this is exactly what you need to make that happen.
Using different packages specific to each major/minor version should be used very sparingly, and IMO should be avoided in most cases.

There is already a way to install a specific version of a package by specifying the `--version` argument when calling `choco install`.

Say for instance you want the `2.5.0.1` version of the package, you would then install the package with `choco install ruby --version 2.5.0.1`.

Only specifying the major.minor version of the package and getting the latest version matching that range isn't possible yet though. But there is an open issue for such an implementation in choco: https://github.com/chocolatey/choco/issues/1278

**Comment by majkinetor** [comment]
I will close this as this will probably be possible one day by choco client and one can easily create script that does that.
