### ISSUE TITLE
(sysinternals) add PortQry and PortQryUI

### ISSUE THREAD

**Issue by 1WindowsPuppetAdmin** [chocolatey-community/chocolatey-coreteampackages#1301]
Include portqry and portqryui in your sysinternals package.

PortQry - https://www.microsoft.com/en-us/download/details.aspx?id=17148

PortQryUI - https://www.microsoft.com/en-us/download/details.aspx?id=24009

**Comment by AdmiringWorm** [comment]
I'm afraid that the sysinternals package is specifically for the Sysinternals Suite softwares, ie the ones available here: https://docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite

Other additional programs not available in the Suite will not be added to the package.
