### ISSUE TITLE
(python) Wrongly reports install success and location when previous install exists

### ISSUE THREAD

**Issue by KrisJanssen** [chocolatey-community/chocolatey-coreteampackages#1303]
I tried to install python through choco this morning on a new machine.

While choco reported successful installation on my machine at C:\Python37.

![ChocoPython3Issue](https://user-images.githubusercontent.com/1765614/60670173-57ea2800-9e70-11e9-8852-5c7c05a7b368.jpg)

To my surprise, 'python' was reported as an unknown command. There was no C:\Python37 either.

I proceeded to edit the chocolatey install script 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1' to remove the /quiet switch and only then it became clear what the issue was:

![2019-07-04 09_53_52-tools](https://user-images.githubusercontent.com/1765614/60669834-98957180-9e6f-11e9-83b8-8e005fffb26d.png)

The machine I received from my employer had VS2019 deployed and this held an install of Python in a non-standard location with no entry on PATH.

While I am aware this is an issue specific to my machine, I think the package should have some kind of logical check to ensure the binaries are actually installed: the absence of error codes does not necessarily indicate success...

Issues like this can easily confuse users (I also spent 30 mins figuring it out :) )

**Comment by majkinetor** [comment]
Looks like an upstream problem. See this line:

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/python3/tools/chocolateyInstall.ps1#L18

i.e. we always pass target dir as a parameter to installer but in this case it choose to ignore it as far as I can see.  It looks like changing the directory is not allowed in that case, judging from the gray _Browse_ button on the screenshot.

**Comment by KrisJanssen** [comment]
Corporate policies require us to run as non-elevated users. The browse button is grayed out because the currently installed version is in a location inaccessible to normal users. 

Would it be good idea to check for an exit code on the installer? 

https://cloudywindows.io/windowsinstallererrorcodes/

**Comment by majkinetor** [comment]
It would already fail on anything not 0.  
Perhaps checking if dir exists would suffice in your case (or something in it), but that is also partial solution generally speaking.

**Comment by majkinetor** [comment]
Its also strange that `$Env:PYTHONHOME` is set to new location by the installer while it keeps old dir (I don't see a WARNING in your installation output)

**Comment by majkinetor** [comment]
We could probably remove previous location so installer doesn't see existing version but I think that would break existing installations that use this as a "feature".

Besides, we can't guarantee beahavior of the package in such scenario. We test packages using blank Windows Server.

You can always mitigate the problem yourself, by doing exactly what I mentioned above in a script, before you cinst python3.

Hence, I think this should be closed (/cc @AdmiringWorm )

**Comment by AdmiringWorm** [comment]
> We could probably remove previous location so installer doesn't see existing version but I think that would break existing installations that use this as a "feature".

Agreed, that would most likely break previous installations, and IMO we really shouldn't do that.

The only thing I believe we could do is to report the actual installation that python was installed to. (ie, grab the existing install location before installing the package, falling back to parameter/default value if there is none).
Probably would need to output a warning in that case though, when a package parameter value is passed as well.

**Comment by AdmiringWorm** [comment]
SHouldn't be closed yet though, until the reporting have been corrected.
