### ISSUE TITLE
(clipgrab) Switch to Adware-Free installer

### ISSUE THREAD

**Issue by edgarchinchilla** [chocolatey-community/chocolatey-coreteampackages#1309]
(clipgrab): Right now the package uses the Adware-Enabled installer, theorically the adware is never installed when the executable is launched from command line.

That has a (minimal?) risk for us right now.

## Expected Behavior

Use the Adware-Free installar called "clipgrab-x.y.z-portable.exe". Yes I know the name suggest a portable application but it isn't, its an installer (as literally is written on the webpage) "without third-party offers"!

Example link:
- https://download.clipgrab.org/clipgrab-3.8.3-portable.exe

## Current Behavior

Right now the "Adware-Enabled" installer is used:
- ![before](https://user-images.githubusercontent.com/16209020/62472584-4db39600-b75c-11e9-9be4-33bd3e3abcc1.png)

Use this instead:
- ![after](https://user-images.githubusercontent.com/16209020/62472472-f9a8b180-b75b-11e9-8216-1aacba2d3d92.png)

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

N/A

## Context

N/A

## Your Environment

* Package Version used: 3.8.3
* Operating System and version: Win10 1903
* Chocolatey version: 0.10.15
* Install/uninstall gist: Install

**Comment by edgarchinchilla** [comment]
All that you need is to replace this line:
> [$re = 'cgorg\.exe$'](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/79ddcdf484ea6b8c3708e5f22357ca967dc9fdb3/automatic/clipgrab/update.ps1#L24)

By:
> $re = 'portable\.exe$'

**Comment by BourgonLaurent** [comment]
Made a Pull Request #1316, just need to be merged by a maintainer.

**Comment by AdmiringWorm** [comment]
Changes have been made, but due to issue #1217 we are currently unable to push a fix version to chocolatey.
