### ISSUE TITLE
(openssl.light) Add C headers

### ISSUE THREAD

**Issue by tenderlove** [chocolatey-community/chocolatey-coreteampackages#1314]
Hi,

I was wondering if it would be possible to get an OpenSSL package that has the headers as well as the runtime?  I'd like to compile and link against OpenSSL, but the OpenSSL.light package only has the runtime files.

Thanks for your time!

**Comment by jerstlouis** [comment]
This is also an issue blocking us from using Travis for our Windows builds.

**Comment by AdmiringWorm** [comment]
We can only provide what is provided by the developers of openssl.
I just took a quick look and could not see any additional archives/installers for the C headers.

It is possible that they are supplied in the existing installer, just not selected by default. But I have not checked whether this is true or not.

**Comment by jerstlouis** [comment]
@AdmiringWorm You need to include the "For Developers"

**Comment by AdmiringWorm** [comment]
@jerstlouis I was specifically looking for either separate downloads that could be used in combination with the light edition.

Currently there is no "non-light" version available on chocolatey, there was a version pushed a couple of years ago, but never finished.

Using that executable for the light edition would be a no-go for the package, however to create a new package for the full edition would be possible. But for that I would suggest opening a RFP over at: https://github.com/chocolatey-community/chocolatey-package-requests/issues

> For MinGW-w64 we really only need the headers

Wouldn't that typically be downloaded using the built-in pacman package manager (or am I mixing mingw with msys perhaps).

**Comment by jerstlouis** [comment]
@AdmiringWorm The headers should come with OpenSSL, I don't even know anything about pacman in msys, not using either pacman or msys.

Is there any way to package the headers (that are included in the bigger package) only? Or to add them to that package?

These OpenSSL headers are going to be needed to build tons of projects.

**Comment by AdmiringWorm** [comment]
> Is there any way to package the headers (that are included in the bigger package) only? Or to add them to that package?

Not as far as I know, it would require to download and install the full installer and then extract out the necessary headers that would be needed. I could add this issue as a n `up to grabs` in case someone out there knows of a different way, but for now it seems unlikely that the headers would be included in this package.

**Comment by jerstlouis** [comment]
@AdmiringWorm Is there anything particularly problematic about installing that package and extracting the headers? I would be happy to do it but I know nothing about chocolatey packages.

**Comment by AdmiringWorm** [comment]
@jerstlouis since we are running a scheduled build on appveyor updating 200+ packages at the same time, yes I would say it could potentially be a problem installing the installer (not the package, but the software installer).

**Comment by jerstlouis** [comment]
A RFP was submitted (https://github.com/chocolatey-community/chocolatey-package-requests/issues/668) and currently has @chtof waiting to be added as a maintainer, with an updated package ready to be published.

**Comment by majkinetor** [comment]
As https://chocolatey.org/packages/openssl is now available I am closing this.
