### ISSUE TITLE
(avidemux) Latest version is failing the automated verifier

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-coreteampackages#1322]
## Expected Behavior

Expects the latest version of avidemux to pass the automated verifier.

## Current Behavior

The latest version is failing the verifier, while the package is continuing after the call to the installer it seems to fail due to the installer being in use (maybe arguments have changed? Missing dependency? Something else?)

## Possible Solution

Not known right now

## Steps to Reproduce (for bugs)
See https://gist.github.com/1597c76d8bbcdda3dbb33310164feddb

## Context
Not personally affected as I do not use avidemux, but would affect all users of avidemux that want the latest version.

## Your Environment

* Package Version used: 2.7.4
* Operating System and version: Win Server 2012R2
* Chocolatey version: 0.10.15
* Install/uninstall gist: See https://gist.github.com/1597c76d8bbcdda3dbb33310164feddb

**Comment by AdmiringWorm** [comment]
Looks like the 64bit installer have changed, and no longer have any arguments it accepts to be silent (I am unable to find them at least).

The 32bit installer seems to be the same as previously though.

**Comment by majkinetor** [comment]
There is this stuff in changelog:

```
 New Installer:Replace NSIS installer with Qt Installer Framework for native MSVC++ 64 bits Windows builds
```

**Comment by majkinetor** [comment]
Anyway, looks like AHK is the only solution now as QT Installer actually does not support silent install (lol?)

**Comment by majkinetor** [comment]
I also looked into it and I think something like this (needs testing).


```ahk
#SingleInstance, force
msgbox % FileExist(A_ProgramFiles "\Avidemux *")

WinWait, Avidemux
WinActivate, 
BlockInput, on

; Welcome screen
Send, {Enter}
Sleep, 100


; When already installed it prompts for uninstall
WinWait, Uninstall ahk_class Qt5QWindowIcon,,1
if (!ErrorLevel) {
    ; prompt detected
    WinActivate
    Send, {Enter}
}

; Folder
WinActivate
Send, {Enter}

; Components
Send, {Enter}
Sleep, 100

; Accept
Send, {Tab}{Space}{Enter}
Sleep, 100

; Start menu shortcuts
Send, {Enter}
Sleep, 100

; Finish
Send, {Enter}
BlockInput, off


; Installing here, can't detect
; but "C:\Program Files\Avidemux 2.7 VC++ 64bits\InstallationLog.txt" shows that last stuff it does
; is to copy Uninstaller and we can detect this with posh snippet bellow
```

In powershell installer after starting above AHK script:
```ps1
while ($t -lt 10){
 $t++
 $u = ls "$Env:ProgramFiles\Avidemux *\Uninstall *.exe"
 if ($!u) { sleep 1; continue } else {  sleep 1; ps avidemux* | kill }
}
if ($t -eq 10) { throw "installation failed" }
```

It seems that some options are not there when app is alrady installed so its probably for the best to unisntall old version via chocolatey and use AHK script only for fresh install.

QT controls can't be automated easily via AHK as they are not native.

**Comment by AdmiringWorm** [comment]
ah, it is a QT Installer. In that case we do not need to rely on autohotkey.
We can pass in a controller script that automated the clicking through the installer instead.

**Comment by majkinetor** [comment]
I am aware of the control script but I didn't know that it can work externally. It looks to me installer needs to support it. If I am wrong, please provide some info and example.

**Comment by AdmiringWorm** [comment]
very simple (for the installation anyhow).

Save the following script somewhere (mostly aquired from: https://stackoverflow.com/a/56922159/5075216):
```
function Controller() {
    installer.autoRejectMessageBoxes();
    installer.installationFinished.connect(function() {
        gui.clickButton(buttons.NextButton);
    })
}

Controller.prototype.WelcomePageCallback = function() {
    // click delay here because the next button is initially disabled for ~1 second
    gui.clickButton(buttons.NextButton, 3000);
}

Controller.prototype.CredentialsPageCallback = function() {
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.IntroductionPageCallback = function() {
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.TargetDirectoryPageCallback = function()
{
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.ComponentSelectionPageCallback = function() {
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.LicenseAgreementPageCallback = function() {
    gui.currentPageWidget().AcceptLicenseRadioButton.setChecked(true);
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.StartMenuDirectoryPageCallback = function() {
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.ReadyForInstallationPageCallback = function()
{
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.FinishedPageCallback = function() {
var checkBoxForm = gui.currentPageWidget().LaunchQtCreatorCheckBoxForm;
if (checkBoxForm && checkBoxForm.launchQtCreatorCheckBox) {
    checkBoxForm.launchQtCreatorCheckBox.checked = false;
}
    gui.clickButton(buttons.FinishButton);
}
```

then call the installer with the following argument: `--script C:\path\to\install.qs`

I have tested the above, and it work with the avidemux installer. Now just trying to get the uninstaller to work as well (not had any success yet)

**Comment by majkinetor** [comment]
God damn it, I already did this once but forgot. Thx

**Comment by AdmiringWorm** [comment]
Almost done with my tests for the uninstaller, so expect a PR to review shortly 😄 

> God damn it, I already did this once but forgot. Thx

You can't remember everything at all times 😸

**Comment by majkinetor** [comment]
I'll just let this one update on its own because #1217.
