### ISSUE TITLE
Bring in a fonts installer extension

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey-community/chocolatey-coreteampackages#1324]
It's well documented that installing Fonts on Windows is a pain. It's complicated to...

 * make it silent (impossible without custom C# code)
 * handle single fonts vs. a font folder
 * handle various font file types
 * report success/failure when a font already exists

The [chocolatey-font-helpers extension](https://chocolatey.org/packages/chocolatey-font-helpers.extension), currently owned by @bcurran3, is recommended to font package authors as a solution during moderation (at least, myself and @teknowledgist have had this experience).

There are [some](https://github.com/bcurran3/ChocolateyPackages/issues/70) issues with this extension, though, and it needs an update. The author is not in a position to review/test these updates. I thought it made perfect sense, at this point, to take on an official Font extension.

 * Fonts on Windows are a system thing, like Windows Features, etc.
 * Font packages should be *dead simple* to create and install with Chocolatey

I propose that @teknowledgist make a PR to this repository... start with one commit that brings in @bcurran3's existing code as-is and a second commit making [their changes](https://github.com/bcurran3/ChocolateyPackages/issues/70#issuecomment-528176610) (that way folks can not only test their final version, but diff the changes from the last accepted version).

A name like **chocolatey-fonts.extension** seems appropriate (the function `Install-ChocolateyFont` is probably still fine).

**Comment by bcurran3** [comment]
> There are some issues with this extension, though, and it needs an update. The author is not in a position to review/test these updates. 

The above two statements are false. The extension has no issues. @AnthonyMastrean has had a problem with it, yes, due to corporate group policies enforced on his machine. I AM in a position to update the extension if needed. There's currently no need.

**Comment by gep13** [comment]
@AnthonyMastrean I am still not convinced that having what is essentially a duplicate extension package makes sense.  I think it would be much better to consolidate the changes into a single package.

**Comment by bcurran3** [comment]
@gep13  Agreed, and that is the plan. REF: https://github.com/bcurran3/ChocolateyPackages/issues/70

**Comment by AnthonyMastrean** [comment]
@bcurran3 misread your position, sorry.

**Comment by AnthonyMastrean** [comment]
@gep13 it's not like the Chocolatey team hasn't obsoleted other helpers/extensions (especially early on) with built ins functions and official extensions. Totally OK if this doesn't rise to that level. Happy to have brought it up for discussion. 🤷‍♂

**Comment by gep13** [comment]
@AnthonyMastrean I agree that has happened in the past, but I don't think we are at that point with this extension just yet.  @bcurran3 is an active maintainer of many Chocolatey packages, and I think it makes sense to continue with a single package just now, rather than duplicate effort.
