### ISSUE TITLE
Badchecksum for Kitty!

### ISSUE THREAD

**Issue by boubouqc** [chocolatey-community/chocolatey-coreteampackages#1328]
zoom v4.8.2721.0811 [Approved]
zoom package files upgrade completed. Performing other installation steps.
Downloading zoom
  from 'https://zoom.us/client/latest/ZoomInstallerFull.msi'
Progress: 100% - Completed download of C:\Users\Sebastien.Boulianne\AppData\Local\Temp\chocolatey\zoom\4.8.2721.0811\ZoomInstallerFull.msi (22.92 MB).
Download of ZoomInstallerFull.msi (22.92 MB) completed.
Error - hashes do not match. Actual value was 'F01BBB214ABBD6689898C412F77514F91F5A0099643D30A25CD8446525A1CDAB'.
ERROR: Checksum for 'C:\Users\.........\AppData\Local\Temp\chocolatey\zoom\4.8.2721.0811\ZoomInstallerFull.msi' did not meet '0af0184e3c3abaa644e84b780583012572eecbe705555b635acf50de1c9d8f7c' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of zoom was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\zoom\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - zoom (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\zoom\tools\chocolateyInstall.ps1'.
 See log for details.

The package was released today.
How does it pass the automated test ?

Please fix it asap or remove from the listing.

**Comment by majkinetor** [comment]
That is output from zoom package, not kitty. Kitty can't have wrong checksum.

**Comment by majkinetor** [comment]
Furthermore, zoom is not part of this repository so closing.
