### ISSUE TITLE
(gitextensions) Install Failure for v3.2

### ISSUE THREAD

**Issue by laurin1** [chocolatey-community/chocolatey-coreteampackages#1329]
cup gitextensions

Chocolatey v0.10.15
Upgrading the following packages:
gitextensions
By upgrading you accept licenses for the packages.
You have gitextensions v3.1.1 installed. Version 3.2 is available based on your
source(s).
Progress: Downloading gitextensions 3.2... 100%
gitextensions v3.2 [Approved]
gitextensions package files upgrade completed. Performing other installation ste
ps.
Installing gitextensions...
WARNING: Generic MSI Error. This is a local environment error, not an issue with
 a package or the MSI itself - it could mean a pending reboot is necessary prior
 to install or something else (like the same version is already installed). Plea
se see MSI log if available. If not, try again adding '--install-arguments="'/l*
v c:\gitextensions_msi_install.log'"'. Then search the MSI Log for "Return Value
 3" and look above that for the error.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\
lib\gitextensions\tools\GitExtensions-3.2.0.6581.msi" /quiet /norestart ADDDEFAU
LT=ALL REMOVE=AddToPath ] was not successful. Exit code was '1603'. Exit code in
dicates the following: Generic MSI Error. This is a local environment error, not
 an issue with a package or the MSI itself - it could mean a pending reboot is n
ecessary prior to install or something else (like the same version is already in
stalled). Please see MSI log if available. If not, try again adding '--install-a
rguments="'/l*v c:\gitextensions_msi_install.log'"'. Then search the MSI Log for
 "Return Value 3" and look above that for the error..
The upgrade of gitextensions was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolate
yInstall.ps1'.
 See log for details.
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - gitextensions (exited 1603) - Error while running 'C:\ProgramData\chocolatey\
lib\gitextensions\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by majkinetor** [comment]
Take a look at `c:\gitextensions_msi_install.log` to see details. I suspect this is not chocolatey specific and that you will get the same error if you run installer non silent.

**Comment by majkinetor** [comment]
Can't confirm with 3.2.1 (and also in disucss comments) 

Here is from my machine:

```
10 [ clean ]  19-10-22 23:22:50 
master~> cinst gitextensions
Chocolatey v0.10.15
Installing the following packages:
gitextensions
By installing you accept licenses for the packages.
Progress: Downloading git 2.23.0... 100%
Progress: Downloading git.install 2.23.0... 100%
Progress: Downloading gitextensions 3.2.1... 100%

git.install v2.23.0 [Approved]
git.install package files install completed. Performing other installation steps.
Using Git LFS
Installing 64-bit git.install...
git.install has been installed.
git.install installed to 'C:\Program Files\Git'
  git.install can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of git.install was successful.
  Software installed to 'C:\Program Files\Git\'

git v2.23.0 [Approved]
git package files install completed. Performing other installation steps.
 The install of git was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

gitextensions v3.2.1 [Approved]
gitextensions package files install completed. Performing other installation steps.
Installing gitextensions...
gitextensions has been installed.
Added C:\ProgramData\chocolatey\bin\gitex.exe shim pointed to 'c:\program files (x86)\gitextensions\gitex.cmd'.
  gitextensions may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of gitextensions was successful.
  Software installed as 'msi', install location is likely default.

Chocolatey installed 3/3 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```
