### ISSUE TITLE
(PartitionMasterFree) Package is out of date, Version 13.5 is available

### ISSUE THREAD

**Issue by edoardo-molinatti** [chocolatey-community/chocolatey-coreteampackages#1336]
There's a new version available (13.5), please update the package.

[EaseUS Partition Master Free 13.5](https://www.easeus.com/partition-manager/epm-free.html)

Thank you.

**Comment by majkinetor** [comment]
This is upstream problem. Script downloads from http://download.easeus.com/free/epm.exe and checks for version number which is in this case still 13.0:

![image](https://user-images.githubusercontent.com/85767/65837116-1d1f5100-e2f4-11e9-9191-09224f7923c9.png)

This means that either vendor accidentally didn't do this or has a new release procedure. In first case this will resolve on its own in future, on second case somebody has to redo the package.

I have no interest personally on propriatery non-FOSS packages so I will leave this to others. PR are welcome.

**Comment by edomoli** [comment]
Hi majkinetor, thank you for your reply.

After a quick investigation I found that the new generic URL they use to download the installer is the following:

[http://down.easeus.com/product/epm_free](http://down.easeus.com/product/epm_free)

This will download an executable installer that is not self-contained (it will download the rest of needed files during the install process).

Do you think you (or someone at Chocolatey) can change the package script and/or test it to automatically install with the smaller installer ("**epm_free_installer.exe**")?

Thank you very much,
best regards.

**Comment by majkinetor** [comment]
I finially used http://download.easeus.com/free/epm_e1125.exe as it is the latest one that fits.
