### ISSUE TITLE
(inkscape) Executable not added to path

### ISSUE THREAD

**Issue by marcopixel** [chocolatey-community/chocolatey-coreteampackages#1344]
## Expected Behavior
After installing Inkscape, it should be available via command line. This is not in the official installers either but it would help productivity by having it directly accessible without the manual addition to `$PATH` and it would make sense especially in the context of a package manager (directly accessible in the terminal)

## Current Behavior
Executing `inkscape -v` return a `ObjectNotFound` error in Powershell.

## Possible Solution
Create a shim with [Install-BinFile](https://chocolatey.org/docs/helpers-install-bin-file) pointing to `$installLocation\inkscape.exe`.

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/2d9aa8798293763b9a054b141b2430ee473e557b/automatic/inkscape/tools/chocolateyInstall.ps1#L44-L46

The following command could be added below line 45, but i couldn't get the install script working on my local machine (can't update because `au_GetLatest failed`, maybe someone can help me out so i can create a pull request?)
```powershell
Install-BinFile 'inkscape' $installLocation\inkscape.exe
```

## Your Environment
* Package Version used: InkScape v0.92.4.20190121
* Operating System and version: Windows 10 Version 1903 (Build 18362.356)
* Chocolatey version: 0.10.15
* Install/uninstall gist: https://gist.github.com/marcopixel/19066a9d42da92448f53a30688513395#file-chocolateyinstall-ps1-L44-L46

**Comment by AdmiringWorm** [comment]
Considering the use case of the program, I don't personally see the need to have incscape available on `PATH`.

As such I do not believe any of the common maintainers of this repository will be adding this (I know I won't at least), however I have added it as an `Up for grabs` in case someone is interested in opening a PR to add this feature.

**Comment by majkinetor** [comment]
Having executable on the PATH (or equivalent) is beneficial in number of non-CLI contexts.

I am all up for PR that adds shim, feel free to provide it.
