### ISSUE TITLE
(spotify) Hashes do not match (new version available?)

### ISSUE THREAD

**Issue by dodedodo33** [chocolatey-community/chocolatey-coreteampackages#1357]
There seems to be a new version of the spotify installer available. Trying to install results in a checksum comparison fault.

## Expected Behavior
Spotify installs correctly.

## Current Behavior
Installation script returns an error after checking the installer checksum.

## Possible solution
Update the checksum?

## Context
Unable to install spotify.

## Your Environment
* Package Version used: v1.1.16.522
* Operating System and version: Win10
* Chocolatey version: 0.10.5

Error - hashes do not match. Actual value was 'F04EBF704AF629AA05689341D266B36F4A4029F1AA0F76B210315A4C317FC1ADC5D0918AAC46BD264066213308B714F2C76A776AC14540A5402D09EC36022BBE'.

**Comment by AdmiringWorm** [comment]
I am looking into fixing this issue now.

Seems that spotify have updated their download page so we the parsing of the executable url isn't possible anymore (without some major magic for combining the url by reading the included javascript).

**Comment by dodedodo33** [comment]
@AdmiringWorm Thanks for looking into this!
