### ISSUE TITLE
(pencil) Doesn't have chocolatey user ?

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1367]
https://chocolatey.org/packages/pencil

https://ci.appveyor.com/project/chocolateycommunity/chocolatey-coreteampackages/builds/28302963
 [170/234] pencil ERROR: 
     Chocolatey v0.10.15 Attempting to push pencil.3.1.0.nupkg to https://push.chocolatey.org Failed to process request. 'The specified API key does not provide the authority to push packages. This package may already exist and be owned by a different user. It could also be hidden. Try going directly to https://chocolatey.org/packages/'packageName' to determine maintainers.'.  The remote server returned an error: (403) Forbidden.. (80.09s)

**Comment by gep13** [comment]
@majkinetor I have added the chocolatey user as a maintainer of this package.
