### ISSUE TITLE
(hostsman) website is down, requires changes to new website

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-coreteampackages#1369]
## Expected Behavior
Hostsman should be able to update to the latest version.

## Current Behavior
Due to the website we are using to detect new downloads is down, the updater no longer works.

## Possible Solution
Change the website to `http://www.abelhadigital.com/hostsman/` and rewrite the package to get the provided google drive links on that page.

**Comment by majkinetor** [comment]
Unfortunatelly version is not obtainable without complete download becuase what is downloaded has different version then what is on site. 

Plus, current version from file is rejected on gallery.

So this requires download each time. Its OK since its around ~2.5MB.

**Comment by majkinetor** [comment]
https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#hostsman

**Comment by AdmiringWorm** [comment]
> So this requires download each time. Its OK since its around ~2.5MB.

There isn't really necessary to download it every time, an implementation similar to how the spotify package is handled could also be done: https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/4550f52c471748c5d483c81cd7819db556183c30/automatic/spotify/update.ps1#L21-L66

But since the file is so small, probably overkill to do that now.

**Comment by majkinetor** [comment]
No it can't. Google doesn't allow HEAD method. I tried that first.

**Comment by majkinetor** [comment]
Well, somebody might have an idea about this: When I get redirected URL from the one update returns now, then Header contains file name with version (in `Content-Disposition`). However, without HEAD, I don't know how to get headers. The equivalent I need is starting downloading in browser then canceling it - if you do that in network tab @ developer tools you will get that header.

**Comment by AdmiringWorm** [comment]
> No it can't. Google doesn't allow HEAD method. I tried that first.

I see, I never checked if it allowed it or not.

> Well, somebody might have an idea about this: When I get redirected URL from the one update returns now, then Header contains file name with version (in Content-Disposition). However, without HEAD, I don't know how to get headers. I need equivalent of starting downloading in browser then canceling it - if you do that with open network tab @ developer tools you will get that header.

Well, in theory you could use `System.Net.WebRequest`, but in any case the server would send the actual content to the machine, which is also true when you cancel a download (depending on the transfer encoding of course). But in the case of such a small file I would say it isn't needed.
