### ISSUE TITLE
(ffmpeg): "Protocol not found. Make sure ffmpeg/Libav is compiled with networking support." — compile FFmpeg with libssh

### ISSUE THREAD

**Issue by 07416** [chocolatey-community/chocolatey-coreteampackages#1381]
## Expected Behavior
When running `mpv sftp://[user[:password]@]server[:port]/path/to/remote/resource.mp4`, the stream should start.

## Current Behavior
FFmpeg returns the error:

```
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open [path]
```

## Possible Solution
Compile ffmpeg with [libssh](https://ffmpeg.org/ffmpeg-protocols.html#libssh) (?), as suggested in the error message.
## Steps to Reproduce (for bugs)
1. Install [mpv](https://chocolatey.org/packages/mpv) and [FFmpeg](https://chocolatey.org/packages/ffmpeg).
2. Configured the command `sftp://[user[:password]@]server[:port]` with your server credentials.
3. Run the command `mpv sftp://[user[:password]@]server[:port]/path/to/remote/resource.mp4`.

## Context
I'm trying to stream media from my server using FFmpeg and mpv.
## Your Environment

* Package Version used: 4.2.1 and 2019.11.02.
* Operating System and version: Windows 10 64-bit (build 18362)
* Chocolatey version: 2019.11.02
* Install/uninstall gist:

**Comment by majkinetor** [comment]
> Compile ffmpeg with libssh (?), as suggested in the error message.

We don't compile. Its upstream problem so report there.
