### ISSUE TITLE
(BeCyIconGrabber) Add a start menu entry

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-coreteampackages#1384]
## Expected Behavior

That there is a start menu entry created when the package is installed. 

I think having it be an option via package parameters would be best, but having it create an entry be default would also work. 

The per-user start directory for the current user does not need administrative privileges to write to, so that is probably where the shortcut should be located.  

## Current Behavior

Currently, the executable is in the tools directory and also shimmed.

## Possible Solution

crystaldiskinfo.portable has a working solution. 
https://chocolatey.org/packages/crystaldiskinfo.portable#files

As does filespy
https://chocolatey.org/packages/filespy/4.1.0.522#files

## Context

Many portable programs are CLI, so shimming only is fine. However, since this is GUI program, having a easy GUI way to access it would be nice. Typing in the executable name in the run box works, but I do not use this enough to remember the spelling of the name.

**Comment by AdmiringWorm** [comment]
Unfortunately it is not possible to update the `becyicongrabber` package anymore, as the website for the software no longer exist.

Thus I will be closing this issue. If there ever is a change in the website status, then please let me know I we can open this issue again.
