### ISSUE TITLE
(Audacity) Stable version of the package is outdated

### ISSUE THREAD

**Issue by holysaiyan1** [chocolatey-community/chocolatey-coreteampackages#1395]
The stable version of the Audacity package has not been updated since May 2019.

## Expected Behavior
Stable release package is up-to-date (version 2.3.3 at the time of this writing)

## Current Behavior
The stable release is version 2.3.2

## Possible Solution
Update the package to the latest version, available at https://www.audacityteam.org/audacity-2-3-3-released/.

## Context
I am trying to use Chocolatey to keep my programs updated, so as to maintain proper security and functionality.

**Comment by AdmiringWorm** [comment]
Unfortunately, because the Audocity team is using `fosshub` as the only way to get new releases, we need to wait until the version is provided on other file shares hosts.

Right now we are using [filehippo](https://filehippo.com/download_audacity/) to detect and download the latest versions for Audacity, but unfortunately they have not yet updated the software there.

We may switch to a different provider, but personally I do not have the possibility to make these changes for the moment.

**Comment by jerome-benoit** [comment]
I fail to understand why using fosshub is an issue. 
You can't extract the links on https://www.fosshub.com/Audacity.html, extract from them the latest version and the download link for the windows version ?

**Comment by AdmiringWorm** [comment]
@jerome-benoit yes, the links *can* be extracted from fosshub, but there are also other counter-measures implemented by fosshub to try denying automatic downloads (not going to go into what here).

See https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub for some explanation. While that link is a rule for submitted packages, we also follow that rule for updating packages here in this repository.

**Comment by jerome-benoit** [comment]
> Le 30 déc. 2019 à 22:25, Kim J. Nordmo <notifications@github.com> a écrit :

> See https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub <https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub> for some explanation. While that link is a rule for submitted packages, we also follow that rule for updating packages here in this repository.

I see. If someone knows a good files download provider that is up to date for audacity, I can make the change and do a PR. But the file provider should really be as good as file hippo: no installer overload with ads and other craps, no user agent filtering policy, etc.

Regards.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by rasa** [comment]
> Right now we are using [filehippo](https://filehippo.com/download_audacity/) to detect and download the latest versions for Audacity, but unfortunately they have not yet updated the software there.
> 
> We may switch to a different provider, but personally I do not have the possibility to make these changes for the moment.

Why not scrape https://www.audacityteam.org/ or https://fossies.org/windows/misc/ and download from https://fossies.org/windows/misc/ via https://fossies.org/windows/misc/audacity-win-2.3.3.exe/ or https://fossies.org/windows/misc/Audacity-2.3.3.zip/ ?

**Comment by rasa** [comment]
> If someone knows a good files download provider that is up to date for audacity, I can make the change and do a PR. 

How about scraping https://www.audacityteam.org/ or https://fossies.org/windows/misc/ and downloading from https://fossies.org/windows/misc/ via https://fossies.org/windows/misc/audacity-win-2.3.3.exe/ or https://fossies.org/windows/misc/Audacity-2.3.3.zip/ ?

**Comment by jerome-benoit** [comment]
> Le 22 janv. 2020 à 17:18, Ross Smith II <notifications@github.com> a écrit :
> 
> If someone knows a good files download provider that is up to date for audacity, I can make the change and do a PR.
> 
> How about scraping https://www.audacityteam.org/ <https://www.audacityteam.org/> or https://fossies.org/windows/misc/ <https://fossies.org/windows/misc/> and downloading from https://fossies.org/windows/misc/ <https://fossies.org/windows/misc/> via https://fossies.org/windows/misc/audacity-win-2.3.3.exe/ <https://fossies.org/windows/misc/audacity-win-2.3.3.exe/> or https://fossies.org/windows/misc/Audacity-2.3.3.zip/ <https://fossies.org/windows/misc/Audacity-2.3.3.zip/> ?
> 


Sounds good. I will do a PR when time permits.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by jerome-benoit** [comment]
I've tried to use the URLs previously given for audacity: 

* The content parsing to get latest version is working, 
* The exe installer downloading is not working within PowerShell chocolatey HTTP client: HTTP 403. Looks like the site is not tolerating some user agent string ...  

I do not know what is the chocolatey policy but I bet it's not to fake UA to a more acceptable one to work around it.

**Comment by AdmiringWorm** [comment]
@jerome-benoit while it would be preferable to not fake the UA, we don't really have any rules regarding not doing that.

If that is what is needed, then it is fine.

**Comment by jerome-benoit** [comment]
> Le 25 janv. 2020 à 03:19, Kim J. Nordmo <notifications@github.com> a écrit :
> 
> @jerome-benoit <https://github.com/jerome-benoit> while it would be preferable to not fake the UA, we don't really have any rules regarding not doing that.
> 
> If that is what is needed, then it is fine.
> 

How doing it within the chocolatey powershell code ? Is there a runtime tunable that permit to set the UA string during update check and install PS scripts ?

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by rasa** [comment]
I don’t think it’s the UA. I think it’s the Referer header. See https://github.com/lukesampson/scoop-extras/issues/368#issuecomment-287621674

**Comment by jerome-benoit** [comment]
> Le 25 janv. 2020 à 08:51, Ross Smith II <notifications@github.com> a écrit :
> 
> I don’t think it’s the UA. I think it’s the Referer header. See lukesampson/scoop-extras#368 (comment) <https://github.com/lukesampson/scoop-extras/issues/368#issuecomment-287621674>

OK, but still, how to set the headers content for all requests during update and install ?

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by majkinetor** [comment]
You don't need it during install, this is embedded package. So you do it in AU, not during update or install.

AU has options for it and Invoke-WebRequst has it.

**Comment by jerome-benoit** [comment]
> Le 26 janv. 2020 à 09:52, Miodrag Milić <notifications@github.com> a écrit :
> 
> You don't need it during install, this is embedded package. So you do it in AU, not during update or install.
> 
> AU has options for it and Invoke-WebRequst has it.
> 

Maybe you can just give us the options for settings the referrer in headers with Update-Package  ?

Because I don’t need it in global:au_GetLatest with Invoke-WebRequest, only during the download with Update-Package and reading https://github.com/majkinetor/au/blob/master/AU/Public/Update-Package.ps1 <https://github.com/majkinetor/au/blob/master/AU/Public/Update-Package.ps1> do not give straight away the options to set HTTP header fields.

Thanks.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by majkinetor** [comment]
https://github.com/majkinetor/au#cant-validate-url-error

Options are used with Get-RemoteFiles that u use in au_BeforeUpdate to produce embedded package and when checking URLs. Thats all you need.

**Comment by jerome-benoit** [comment]
I've been able to have URL check working and get the remote version from fossies.org. The Get-RemoteFiles is still not working but I can't do more tests because I've done too much requests on fossies.org to find out the right headers needed and my IP seems to be temporary (I hope) blacklisted. I do not have a VPN. The code is here https://github.com/jerome-benoit/chocolatey-coreteampackages in the master branch for people here to test.

**Comment by jerome-benoit** [comment]
My public IP is still blacklisted and I'm afraid it's not going to change anytime soon. So until I'm able to free some time to test my latest change at my work place, if someone is kind enough to test my audacity update.ps1 changes because it might work, I've just not been able to test the referrer change done before calling Get-RemoteFiles.

**Comment by AdmiringWorm** [comment]
@jerome-benoit could you open what you have currently as a draft PR?
This way we can make changes if there is a need to.

**Comment by jerome-benoit** [comment]
The issue have been closed before the package moderator approval: https://chocolatey.org/packages/audacity/2.3.3 

Nobody is doing the packages moderation? because it has been so since months ...

**Comment by majkinetor** [comment]
The package moderation is irrelevant for this repo. The gallery is just one way to install it (you can grab artifact from github for example).

**Comment by gep13** [comment]
@jerome-benoit the issue with package validator has been addressed, and the audacity package is now correctly approved, and ready for installation.

**Comment by jerome-benoit** [comment]
> @jerome-benoit <https://github.com/jerome-benoit> the issue with package validator has been addressed, and the audacity package is now correctly approved, and ready for installation.

Great !

Thanks.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3
