### ISSUE TITLE
(Python) Chocolatey does not uninstall python 3.8.0

### ISSUE THREAD

**Issue by dakimaz** [chocolatey-community/chocolatey-coreteampackages#1396]
Chocolatey does not uninstall python 3.8.0. 

## Expected Behavior
Python 3.8.0 is uninstalled

## Current Behavior
Python 3.8.0 is not uninstalled

## Command output
C:\WINDOWS\system32>`choco install python --version=3.8.0 --force`
Chocolatey v0.10.15
Installing the following packages:
python
By installing you accept licenses for the packages.
python v3.8.0 already installed. Forcing reinstall of version '3.8.0'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading python 3.8.0... 100%

python v3.8.0 (forced) [Approved]
python package files install completed. Performing other installation steps.
 The install of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\WINDOWS\system32>`choco uninstall python --version=3.8.0 --force`
Chocolatey v0.10.15
Uninstalling the following packages:
python

python v3.8.0 (forced)
 Skipping auto uninstaller - No registry snapshot.
python not uninstalled. An error occurred during uninstall:
 Could not find a part of the path 'C:\ProgramData\chocolatey\lib\python\python.nupkg'.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - python (exited 1) - python not uninstalled. An error occurred during uninstall:
 Could not find a part of the path 'C:\ProgramData\chocolatey\lib\python\python.nupkg'.

If a package uninstall is failing and/or you've already uninstalled the
 software outside of Chocolatey, you can attempt to run the command
 with `-n` to skip running a chocolateyUninstall script, additionally
 adding `--skip-autouninstaller` to skip an attempt to automatically
 remove system-installed software. This will only remove the packaging
 files and not things like software installed to Programs and Features.

If a package is failing because it is a dependency of another package
 or packages, then you may first need to consider if it needs removed
 as it is typically installed as a dependency for a reason. If you
 decide that you still want to remove it, head into
 `$env:ChocolateyInstall\lib` and find the package folder you want
 removed. Then delete the folder for the package. This option should
 only be used as a last resort.

## Context
I use chocolatey for a lot of packages, because it makes things that much easier, but choco fails to uninstall python. It removes the entries from Programs and Features list, but the source code for python is still there as well as entries in the system Path environment.
I have tried different versions of python too (3.7.4, 3.7.0) but with the same result.
I have also tried on a different laptop (with windows 10 too), with the same result.
The installation process appears to be fine, and I can use python, but I cannot uninstall it again.
The reason i explicitly specify which version of python to uninstall is that i have a working 3.7.4 installation that I'd rather not corrupt.

If I omit the "--force" argument the following output is produced:
C:\WINDOWS\system32>`choco uninstall python --version=3.8.0`
Chocolatey v0.10.15
Uninstalling the following packages:
python

python v3.8.0
 Skipping auto uninstaller - No registry snapshot.
 python has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

However, the python source code and Path entries are still there:

![image](https://user-images.githubusercontent.com/51018418/70618326-cfd42f80-1c12-11ea-9e30-bdfdc346ccf1.png)

![image](https://user-images.githubusercontent.com/51018418/70618381-f3977580-1c12-11ea-884b-f16b7f683050.png)

## Your Environment
* Package Version used: 3.8.0
* Operating System and version: Windows 10
* Chocolatey version: 0.10.15

**Comment by AdmiringWorm** [comment]
> Python 3.8.0 is not uninstalled

Not really surprised, as you only uninstall the meta package (`python`) and not the actual installation package (`python3`).

Either pass in `-x` when uninstalling the meta package, or directly uninstall the `python3` package.

**Comment by dakimaz** [comment]
How is `choco uninstall python --version=3.8.0` only uninstalling the meta package?
Is that really expected behavior?
`choco uninstall python -x --version=3.8.0` seems to solve the issue, but it throws a lot of errors:

C:\WINDOWS\system32>choco uninstall python -x --version=3.8.0
Chocolatey v0.10.15
Uninstalling the following packages:
python
[NuGet] 'chocolatey 0.10.15' skipped, because it is in use by 'cmake.install 3.14.0, git.install 2.20.1'.
[NuGet] 'chocolatey-core.extension 1.3.3' skipped, because it is in use by '7zip.install 19.0, git.install 2.20.1, notepadplusplus.install 7.6.1'.

python v3.8.0
 Skipping auto uninstaller - No registry snapshot.
 python has been successfully uninstalled.

python3 v3.8.0
 Running auto uninstaller...
 Auto uninstaller failed. Please remove machine installation manually.
 Exit code was 1603
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller failed. Please remove machine installation manually.
 Exit code was 1603
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller failed. Please remove machine installation manually.
 Exit code was 1603
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
 python3 has been successfully uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).

Chocolatey uninstalled 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - python3 -  Auto uninstaller failed. Please remove machine installation manually.
 Exit code was 1603

**Comment by AdmiringWorm** [comment]
> How is choco uninstall python --version=3.8.0 only uninstalling the meta package?
> Is that really expected behavior?

Yes, as long as the meta package don't have a dependency on a `.install`/`.portable` package, then that is expected.

> Exit code was 1603

That exit code is usually related to your environment, possibly you got python running so it is locking the python executable, or there are something else locking the files/directory of the python installation.

That is only an assumption from me though.

In the end though, this is one of following things:
1. Something environment related (IE, your computer)
2. A bug in the software uninstaller
3. Something is locking a file/directory

As I mentioned earlier, we don't handle the uninstall directly in the package, but makes use of chocolatey's auto-uninstaller (which then runs the official software uninstaller when it can).

As such, this issue is not package related and I will be closing the issue.
