### ISSUE TITLE
(gpg4win)  The term 'touch' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by jerome-benoit** [chocolatey-community/chocolatey-coreteampackages#1398]
## Current Behavior

Install or upgrade failure due to: 

```
touch : The term 'touch' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Error while running 'C:\ProgramData\chocolatey\lib\Gpg4win\tools\chocolateyInstall.ps1'.
```

## Possible Solution

Use New-Item or echo >> or ... but an existing Windows commands, nor an alias.

## Your Environment

* Package Version used: v3.1.11
* Operating System and version: Windows 10
* Chocolatey version: current stable

**Comment by AdmiringWorm** [comment]
Seems that the helper module used don't expand the `touch` command, as it isn't detectable as an alias.

Opened https://github.com/WormieCorp/Wormies-AU-Helpers/issues/30 as a cross-reference.
