### ISSUE TITLE
chocolatey-core.extension v1.3.5.1 fails to install behind proxy

### ISSUE THREAD

**Issue by holmesb** [chocolatey-community/chocolatey-coreteampackages#1400]
Installing using command:
choco install --force chocolatey-core.extension -y --version 1.3.5.1
fails with error:
"The remote server returned an error: (403) Forbidden. URLBlocked"

Installing prior version works fine:
choco install chocolatey-core.extension -y --version 1.3.5

Also installing v1.3.5.1 when not behind a proxy server works fine.

**Comment by AdmiringWorm** [comment]
Sounds like your proxy are getting blocked by `chocolatey.org`, you will need to contact the chocolatey staff for resolving this (https://chocolatey.org/contact).

Bottom line, this is not a package issue so I will be closing this issue.
