### ISSUE TITLE
(python3) Split python3 major versions into separate packages

### ISSUE THREAD

**Issue by ImportTaste** [chocolatey-community/chocolatey-coreteampackages#1410]
Very rarely is upgrading to the latest stable release on the day it comes out a good idea, because most python package developers are not preparing for it by testing against the alpha. Most are one major release behind, with Python 3.8 still not supported by any different packages even though it's been out for months now.

Python keeps roughly 3 to 4 major versions up to date all at once due to the major compatibility differences between them, so when a new 3.8 build is out, a new 3.7 build is out on the same day, and you'd only really be able to install it on Chocolatey by removing any pins you may have, verifying the new version in the version history (and 3.7 is so far down now you have to click on 'see more' to see it), installing that exact version manually, and then re-pinning.

So in my opinion it doesn't really make much sense to have a single python3 package, I think it would be better to have python36, python37, python38, python39, etc.

**Comment by majkinetor** [comment]
This is a job for choco.exe, not this place (pinning to version but allowing certain updates). Doing that on package level seem to only make entropy worse.

For now you can create shell script that implements this (its trivial) and use it instead choco directly.

**Comment by ImportTaste** [comment]
I don't think that's the answer. Most Linux distros have different repos for different versions of Python3, with the main python3 pointing to a stable that is usually two versions behind the latest.

It should probably be the same on choco, with python3 being a virtual package much like python, pointing to a major version that's one version behind latest, and then having python36 python37 python38 and python39 packages.

The end user shouldn't have to rely on a script for this functionality.

**Comment by AdmiringWorm** [comment]
@ImportTaste I am curious of which distros you have seen doing this.

I have used my fair share of different linux distros, and I can not remember a single time when they have provided different packages for major.minor versions of the python package.
At most, they provide a python 3.x and python 2.x package (not named that way of course), some don't even do that and only provide a single package.

I am with @majkinetor on this one though (but maybe not for the entirely same reason).
Providing a python package for every single minor release of python would just end up diluting the community repository, and basically make finding packages harder to accomplish.

**Comment by ImportTaste** [comment]
> I have used my fair share of different linux distros, and I can not remember a single time when they have provided different packages for major.minor versions of the python package.

Debian.

> I am with @majkinetor on this one though (but maybe not for the entirely same reason).
> Providing a python package for every single minor release of python would just end up diluting the community repository, and basically make finding packages harder to accomplish.

I think that's a bit hyperbolic.

**Comment by AdmiringWorm** [comment]
> Debian

Sure, debian do this. But only for the library, not the full package. Basically just enough so existing pre-compiled softwares can run (possibly also compile, I dunno as I am not a python dev).

> which is one of the most common distros, and often a base for other distros, does this.

That is a moot point, as most distros dependent on debian provide their own package repository, and some aren't even compatible with the debian package repository (yes, some are compatible, like Ubuntu for instance, but not for all packages).

> I think that's a bit hyperbolic.

How so. Think about it this way. If we start releasing a new package (not a version) for every minor version of the python package, shouldn't this also be done for every other package in this repository (a little over 200 packages).
Now, if you wanted to search for a package then, you know the name but not necessarily the id of the package.
If a new package is being pushed for every single minor version of every package, how many pages would you navigate through before getting to the correct one (assuming that the main package isn't the most popular one of course).

**Comment by AdmiringWorm** [comment]
Btw, just to make sure I actually checked the official debian package repository (for the latest buster edition).
The only one it got there for python 3.x range right now is 3.7 (at least from what I could find). Not 3.6, 3.5, 3.4, etc.

**Comment by ImportTaste** [comment]
> Btw, just to make sure I actually checked the official debian package repository (for the latest buster edition).
> They only got one for the python 3.x range, which is right now [3.7](https://packages.debian.org/buster/amd64/python3.7) (at least from what I could find). Not 3.6, 3.5, 3.4, etc.

Check the oldstable repo.

**Comment by majkinetor** [comment]
Let me be really concise:

- Lots of work for very small improvement (or, if we make it standard, its enormous work for next to 0 benefit)
- Repository client (choco.exe) needs to have this option like almost EVERY other
- You can make 5 line script (I did it for me) to mitigate this.

No brainer for me.

**Comment by ImportTaste** [comment]
Forgive my ignorance, but wouldn't it just be a matter of splitting up what you already automate? It seems like it would be pretty easy to just regex search https://www.python.org/ftp/python/ and then the subfolder.

**Comment by majkinetor** [comment]
I will close this as there isn't anything more to discuss.
