### ISSUE TITLE
(python2) move to manual folder

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1411]
AFAIK python2 wont have updates any more.

**Comment by AdmiringWorm** [comment]
python 2 is still in active support (most likely will be until this year is over).

version 2.7.18 is planned to be released mid april or something around that.

https://www.python.org/dev/peps/pep-0373/

**Comment by majkinetor** [comment]
> Being the last of the 2.x series, 2.7 will receive bugfix support until 2020.
> Support officially stops January 1 2020, but the final release will occur after that date.
