### ISSUE TITLE
(winscp) WinSCP.com should get a shim

### ISSUE THREAD

**Issue by burfo** [chocolatey-community/chocolatey-coreteampackages#1412]
## Expected Behavior
With winscp.portable (and likely winscp.installer too), the file WinSCP.com should get a shim.

## Current Behavior
WinSCP.exe gets a shim during installation, but WinSCP.com doesn't.

## Context
WinSCP.com is the console-only version which can be used in automated scripts, etc.  It's possible to use `WinSCP.exe /console` for some situations, but exit codes don't work the same way.

**Comment by majkinetor** [comment]
Duplicatet: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1134

**Comment by burfo** [comment]
@majkinetor do you want me to close this one and open #1134, or leave this one open?

**Comment by majkinetor** [comment]
All is fine.

**Comment by burfo** [comment]
AFAIK, still relevant.

**Comment by RedBaron2** [comment]
@burfo 
Would copying WinSCP.com to the location of the shimmed WinSCP.exe accomplish what is requested?

The questions are more about:
- do you require it in the PATH?
{The entire chocolatey lib directory is on the PATH}
- what location is expected?
- would something like `programdata/chocolatey/WinSCP.com` work for you?

**Comment by burfo** [comment]
@RedBaron2 I would expect (and prefer) for WinSCP.com to be in the PATH, yes.  This executable is used in scripts and such; it would not be ideal to embed the executable's path into the scripts.  If it's in PATH, then I don't have any preference on where it's actually stored but being next to WinSCP.exe would seem appropriate to me.

**Comment by RedBaron2** [comment]
@burfo 
I'll work on a test package for you by the end of the week :crossed: . You can give me feedback if it works for you.

I'll edit this with the package URL later

**Comment by AdmiringWorm** [comment]
@RedBaron2 be mindful that adding files manually to the `bin` directory is not allowed on chocolatey.org.
The same goes for any directory underneath `%ChocolateyInstall%` other than the package directory itself.

The best bet would actually be to change the installation location to use `Get-ToolsLocation` and add that to the `PATH` environment variable instead of relying on shims.

*NOTE: This will require a call to `refreshenv` by the user for them to use the program immediately after installation without restarting the shell*

**Comment by majkinetor** [comment]
I suggest simply adding shim to it.

**Comment by AdmiringWorm** [comment]
@majkinetor I don't think that would work in this case, I believe it may be incompatible with the already shimmed `WinSCP.exe` file.
But by all means, if it do work then indeed that would be the best.

**Comment by RedBaron2** [comment]
FYI: the normal install of the WinSCP Setup file **_Does Not_** add either `WinSCP.exe` or `WinSCP.com` to the _Path_
This is only done when installing  `WinSCP.Install` through Chocolatey

AdmiringWorm had quoted in issue #1134 
> I'm guessing that if we were to shim the winscp.com utility, it would ... be shimmed as `winscp.com.exe` 

This appears to be the easiest solution to the problem.
- It will put it on the path
- It will make it accessible from the cmd and posh
- It will be a simple line addition to the `WinSCP.Install` package un/install script files
- NOTE: If the shim is renamed to be `WinSCP.com` **_It will be uninstalled_** through chocolatey {Tested Works}
AdmiringWorm has pointed out that manual change to any files in the `bin` directory is not allowed on chocolatey.org.

The negatives are 
- That it doesn't add the shim if the `WinSCP.Portable` is installed.

@burfo 
If you are concerned about the .exe extension now added to the file. This appears to be a side effect of the `Un/Install-BinFile` helper function 😞
