### ISSUE TITLE
GitExtensions 3.3.1 - Installing v3.3.0 instead

### ISSUE THREAD

**Issue by laurin1** [chocolatey-community/chocolatey-coreteampackages#1413]
```
C:\windows\system32>cinst gitextensions
Chocolatey v0.10.15 Business
Installing the following packages:
gitextensions
By installing you accept licenses for the packages.
Progress: Downloading gitextensions 3.3.1... 100%

**gitextensions v3.3.1 [Approved]**
gitextensions package files install completed. Performing other installation steps.
**Installing GitExtensions-3.3.0.7886.msi...
GitExtensions-3.3.0.7886.msi has been installed.**
Added C:\ProgramData\chocolatey\bin\gitex.exe shim pointed to 'c:\program files (x86)\gitextensions\gitex.cmd'.
gitextensions may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
see the changes (or in powershell/cmd.exe just type refreshenv).
The install of gitextensions was successful.
Software install location not explicitly set, could be in package or
default install location if installer.

Chocolatey installed 1/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by majkinetor** [comment]
Sorry, its unfixable due to #1217. ([build](https://ci.appveyor.com/project/chocolateycommunity/chocolatey-coreteampackages/builds/30244393)) - all updated embedded packages errored on push, even tho this one is only ~20MB

**Comment by AdmiringWorm** [comment]
Seems the updated 3.3.1 version was actually pushed to chocolatey (and is available for consumption).

Regarding the 3.3.0 version in the 3.3.1 release, this was the executable provided by the developers when they created the 3.3.1 tag (I assume that it was just incorrectly named, or not fully updated to the correct version).

Anyways, closing this issue as the latest version contains the latest executable available.

**Comment by laurin1** [comment]
FYI, our automated scripts will not be update to update the machines because of this:

C:\windows\system32>cup gitextensions
Chocolatey v0.10.15 Business
Upgrading the following packages:
gitextensions
By upgrading you accept licenses for the packages.

You have gitextensions v3.3.1 installed. Version 3.3.1.20200120 is available based on your source(s).
Progress: Downloading git 2.17.1.2... 100%
gitextensions not upgraded. An error occurred during installation:
 Already referencing a newer version of 'git.install'.
gitextensions package files upgrade completed. Performing other installation steps.
The upgrade of gitextensions was NOT successful.
gitextensions not upgraded. An error occurred during installation:
 Already referencing a newer version of 'git.install'.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - gitextensions (exited 1) - gitextensions not upgraded. An error occurred during installation:
 Already referencing a newer version of 'git.install'.

**Comment by AdmiringWorm** [comment]
@laurin1 this is something that happens from time to time, and is covered in the chocolatey documentation: https://chocolatey.org/docs/troubleshooting#already-referencing-a-newer-version-of-packagename

**Comment by laurin1** [comment]
I am aware that it can happen and how to fix it, but it breaks automated update scripts when it does, was all I was saying.
