### ISSUE TITLE
KB3035131 "WARNING: User (you) cancelled the installation." when install over openssh

### ISSUE THREAD

**Issue by soul4soul** [chocolatey-community/chocolatey-coreteampackages#1414]
Unable to install KB3035131 over openssh on Windows-7-x86. This package is a dependency of  vcredist140. openssh is configured to use windows powershell 5.1 as the default shell. I am able to install other packages using choco over openssh. The account being used has administrator privileges. When physically logged (RDP or physically at the machine) onto the machine running `choco install -y KB3035131` works.

This issue appears to be the similar to #1002 and (https://github.com/hashicorp/packer/issues/6156). 

## Expected Behavior

KB3035131 should install

## Current Behavior

KB3035131 fails to install with given error message. Attached ZIP contains the event log.
[KB3035131.Install.zip](https://github.com/chocolatey-community/chocolatey-coreteampackages/files/4055887/KB3035131.Install.zip)

```ps
PS C:\Users\engineer> choco install kb3035131 -y
Chocolatey v0.10.15                                                                                                                                                                 Installing the following packages:
kb3035131
By installing you accept licenses for the packages.                                                                                                                                 Progress: Downloading KB3035131 1.0.3... 100%

KB3035131 v1.0.3 [Approved]
kb3035131 package files install completed. Performing other installation steps.                                                                                                     Downloading KB3035131 32 bit
  from 'https://download.microsoft.com/download/8/A/3/8A3E90CC-AEC3-4645-8CF3-2BD205E26B5E/Windows6.1-KB3035131-x86.msu'                                                            Progress: 100% - Completed download of C:\Users\engineer\AppData\Local\Temp\chocolatey\KB3035131\1.0.3\Windows6.1-KB3035131-x86.
msu (6.32 MB).
Download of Windows6.1-KB3035131-x86.msu (6.32 MB) completed.                                                                                                                       Hashes match.
Installing KB3035131...
WARNING: User (you) cancelled the installation.                                                                                                                                     WARNING: Update KB3035131 installation failed (exit code 5).
WARNING: More details may be found in the installation log (C:\Users\engineer\AppData\Local\Temp\chocolatey\KB3035131.Install.ev
t) or the system CBS log (C:\Windows\Logs\CBS\CBS.log).                                                                                                                             ERROR: Update KB3035131 installation failed (exit code 5).
The install of kb3035131 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
 See log for details.                                                                                                                                                               
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - kb3035131 (exited 5) - Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
 See log for details.                          
```

## Possible Solution

Seeing the related issue used an elevated prompt to solve the issue I tried.
`Start-Process powershell -ArgumentList "-Command choco install -y kb3035131 | out-file log.txt" -Verb RunAs -Wait` and `powershell -executionpolicy bypass "Start-Process powershell -ArgumentList '-executionpolicy bypass -Command choco install -y kb3035131 | out-file log.txt' -Verb RunAs -Wait"` with neither working.

## Context

I'm trying to provision Windows 7 x86 computers over openssh using windows powershell.

## Your Environment

* Package Version used: 1.0.3
* Operating System and version: Windows 7 x86
* Chocolatey version: 0.10.15
* Install/uninstall gist: `choco install -y kb3035131`

**Comment by majkinetor** [comment]
Looks like there was some popup somewhere (didn't run elevated for some reason?).
