### ISSUE TITLE
(inkscape) Add support for beta releases

### ISSUE THREAD

**Issue by YAMLcase** [chocolatey-community/chocolatey-coreteampackages#1420]
## Expected Behavior
Please add beta support for Inkscape.

## Current Behavior
Inkscape 1.0 beta was released in December 2019.  It will container lots of major improvements, including official theme support (dark themes).

## Context
Those of us with sensitivity to light are always looking for a way to darken our applications.  Inkscape never had official support for theme-ing instead relying on 3rd party hacks that are not resilient.  Inkscape 1.0 beta now officially support themes and has a dark theme available.

Thank you!

**Comment by yamlCase** [comment]
Release page:
https://inkscape.org/release/1.0beta2/windows/

**Comment by AdmiringWorm** [comment]
I have no interest in looking into providing pre-release versions of Inkscape, however, I will make this `up for grabs` in case there is someone interested in making the necessary changes to make this happen.

**Comment by tunisiano187** [comment]
it seems, they've changed the links
