### ISSUE TITLE
cmake needs to be updated

### ISSUE THREAD

**Issue by pgalbraith** [chocolatey-community/chocolatey-coreteampackages#1423]
[cmake](https://chocolatey.org/packages/cmake) needs some moderator attention, the current pusblished version is 3.16.4.  3.16.3 has been uploaded but is stuck in moderation waiting for attention.

**Comment by pgalbraith** [comment]
There's now 4 versions of this package stuck in moderation with "waiting for maintainer" status.

**Comment by majkinetor** [comment]
https://chocolatey.org/packages/cmake/3.16.4.20200220

**Comment by majkinetor** [comment]
Nah, I give up, you will have to wait for new version. When I finally got the syntax right, it failed due to #1217...

**Comment by pgalbraith** [comment]
Hmmmm, if it's still an issue, which it seems to be, shouldn't the issue be left open?

**Comment by majkinetor** [comment]
I made it:

* https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/4ed0f8547f0977d4fc0b6cc0f93925b983e0936b#pushed
