### ISSUE TITLE
(FreeCAD) Needs updated

### ISSUE THREAD

**Issue by Technetium1** [chocolatey-community/chocolatey-coreteampackages#1425]
FreeCAD package: https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/freecad

Current releases: https://github.com/FreeCAD/FreeCAD/releases

**Comment by majkinetor** [comment]
[FreeCAD 0.18.16146](https://chocolatey.org/packages/freecad/0.18.16146) is actually as it points to `FreeCAD-0.18.4.980bf90-WIN-x64-installer.exe` which IS [latest realease](https://github.com/FreeCAD/FreeCAD/releases/tag/0.18.4) on Github ATM.

Now, we have a versioning bug here, don't know what happend here and where 16146 comes from (there is actually a Linux file name containing that string on latest release). I run updater on my machine and it reports corretly:

```
1 [ clean ]  20-02-18 21:39:14  C:\Work\_\_\chocolatey-coreteampackages\automatic\freecad
master~> .\update.ps1
freecad - checking updates using au version 2019.5.22

URL check
  https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x32-installer.exe
  https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x64-installer.exe
nuspec version: 0.18.16146
remote version: 0.18.4
No new version found


Path          : C:\Work\_\_\chocolatey-coreteampackages\automatic\freecad
Name          : freecad
Updated       : False
Pushed        : False
RemoteVersion : 0.18.4
NuspecVersion : 0.18.16146
Result        : {freecad - checking updates using au version 2019.5.22, , URL check,   https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x32-installer.ex
                e...}
Error         :
NuspecPath    : C:\Work\_\_\chocolatey-coreteampackages\automatic\freecad\freecad.nuspec
NuspecXml     : #document
Ignored       : False
IgnoreMessage :
StreamsPath   : C:\Work\_\_\chocolatey-coreteampackages\automatic\freecad\freecad.json
Streams       :
```

This version will also block any further 18.4.x updates as they will all probably be "lower" then 16146.

IMO, we should wait for some time to see if it will self-recover.

**Comment by RedBaron2** [comment]
@majkinetor @Technetium1 
> The FreeCAD [Wiki](https://www.freecadweb.org/wiki/Download)
The first 0.18 release of FreeCAD (16093) was published on 2019-03-12. The latest bug fix release 0.18.4 (16146) was published on 2019-10-26. To find out what's new, see the [release notes](https://www.freecadweb.org/wiki/Release_notes_0.18).

The version bug is due to PR #1377

**Comment by majkinetor** [comment]
So it was my bad :)

Thanks for clarifying it.

**Comment by majkinetor** [comment]
I will close this as there is nothing more to do.
