### ISSUE TITLE
(Total Commander) update to 9.50

### ISSUE THREAD

**Issue by CWempe** [chocolatey-community/chocolatey-coreteampackages#1426]
There is a new version of Total Commander with many new features (including dark mode).

I would appreciate an update for this package.

https://chocolatey.org/packages/TotalCommander
https://www.ghisler.com/download.htm

**Comment by majkinetor** [comment]
For some reason we look here:

https://www.ghisler.com/amazons3.php

And it isn't updated.... Seems like an upstream problem.

**Comment by majkinetor** [comment]
Changed to official place.

FYI, there is my package with dark theme

https://chocolatey.org/packages/tcc-unlit
