### ISSUE TITLE
(kitty) kitty.exe (0.73.2.3) 6 Virus Total detections

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-coreteampackages#1427]
The [kitty package](https://chocolatey.org/packages/kitty) has been reported as having a [high number of Virtual Total detections](https://chocolatey.org/packages/kitty/0.73.2.3#virus). The [kitty.exe file has 13](https://www.virustotal.com/file/dd6bb61464beee6787ff01b0eb35505b1aead6fa8aa910fe67a179435158109c/analysis/) (you'll need to click through the link to see the new number).

Can somebody clarify this?

**Comment by pauby** [comment]
As an update I re-ran the virus scanner on the package (thanks @mkevenaar) and it's now reporting 2 on the site but 15 in VT.

**Comment by pauby** [comment]
I've rejected the package version in the meantime.

**Comment by majkinetor** [comment]
You should undo that, only 4:

```
PS> iwr https://github.com/cyd01/KiTTY/releases/download/v0.73.2.3/kitty.exe -OutFile kitty.exe
PS> sigcheck -vt .\kitty.exe

Sigcheck v2.73 - File version and signature viewer
Copyright (C) 2004-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Users\mmilic\Downloads\kitty.exe:
        Verified:       Unsigned
        Link date:      09:30 12.2.2020.
        Publisher:      n/a
        Company:        Simon Tatham
        Description:    SSH, Telnet and Rlogin client
        Product:        PuTTY suite
        Prod version:   Release 0.73 - KiTTY fork - Additional features on KiTTY That's all folks! by 9bis.com, 2005-2020
        File version:   Release 0.73 (without embedded help)
        MachineType:    32-bit
        VT detection:   4/70
        VT link:        https://www.virustotal.com/file/dd6bb61464beee6787ff01b0eb35505b1aead6fa8aa910fe67a179435158109c/analysis/
```

**Comment by blowsfire** [comment]
.

**Comment by pauby** [comment]
It's now currently at 6 for `kitty.exe` for version 0.73.2.3

**Comment by majkinetor** [comment]
Could you explain the treashold on numbers you guys use ?
