### ISSUE TITLE
[vscode.install] do we really need to depend on dotnet 4.5.2?

### ISSUE THREAD

**Issue by casz** [chocolatey-community/chocolatey-coreteampackages#1434]
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/2118b0cf93bf76a56979a156434b3cc1b56dc2e8/automatic/vscode.install/vscode.install.nuspec#L48

I do not think there is a need for vscode.install to depend on dotnet 4.5.2 as https://code.visualstudio.com/docs/setup/windows states:

> Note: .NET Framework 4.5.2 or higher is required for VS Code. If you are using Windows 7, make sure you have at least .NET Framework 4.5.2 installed. You can check your version of .NET Framework using this command, `reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full" /v version` from a command prompt.

Perhaps it would be better to check the registry and suggest user to install if `4.5.2` or higher when version does not match the minimum required.

**Comment by mkevenaar** [comment]
@casz If you take a look at the code of the [package](https://chocolatey.org/packages/dotnet4.5.2#files), and expand the `ChocolateyInstall.ps1` file, you'll notice that it will only install .NET Framework 4.5.2 if the registry key does not exist.

Packages in the Chocolatey Community Repository will aim into a as painless installation as possible. Based on this, I don't think removing the dependency is a good idea.

**Comment by casz** [comment]
I kinda of disagree, I do not want software on my machine that's from 2014 that serves no purpose, vscode is definitely not dependent on exactly .NET Framework 4.5.2 😅

**Comment by mkevenaar** [comment]
@casz I just tested this on a mint installation of Windows Server 2016. 4.5.2 will not get installed. 

To reproduce, if you run the command:
```powershell
if(-not (test-path "hklm:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework,Version=v4.5.2")) {
    Write-Host "Microsoft .Net 4.5.2 Framework is not installed."
} else {
    Write-Host "Microsoft .Net 4.5.2 Framework is already installed on your machine."
}
```
This is the exact same verification as the package uses, without the actual installation. 

This results that the Chocolatey package gets installed on your machine, not the actual .NET framework software defined in the package, because you're locally installed framework version is newer than this version.

So no "old software" gets installed on your machine.

**Comment by casz** [comment]
Okay checked on Windows 10 1909 and 2004 that this is the case 😓
