### ISSUE TITLE
(googlechromebeta) not updating

### ISSUE THREAD

**Issue by nsleigh** [chocolatey-community/chocolatey-coreteampackages#1436]
The googlechromebeta package has stopped updating, the last update was 04/02/2020 and there should have been a couple of updates since then.

I have update.ps1 locally and it doesn't fail and the package updates to 81.0.4044.34-beta.

I originally authored this package in 2019 but cannot remember if there are any logs I can check to workout why it is not updating.

Can someone suggest the next steps.

**Comment by mkevenaar** [comment]
Hi @nsleigh the package got stuck in moderation. I gave it a slight push and should now be updated again on the next update run.

**Comment by nsleigh** [comment]
Many thanks, I'll keep an eye on it.

**Comment by mkevenaar** [comment]
@nsleigh A new version is now pushed. https://chocolatey.org/packages/googlechromebeta/81.0.4044.34-beta once validation is complete, it will be available on the website. I'm closing this issue now.
