### ISSUE TITLE
(winscp) package failing validation

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey-community/chocolatey-coreteampackages#1439]
## Expected Behavior
Package passing validation

## Current Behavior
Package failing validation:
```
The ProjectSourceUrl element in the nuspec file should be a valid Url. Please correct this More...
```

## Possible Solution
Fix ProjectSourceUrl or remove it.

## Steps to Reproduce (for bugs)
see https://chocolatey.org/packages/winscp/5.17.2

**Comment by mkevenaar** [comment]
This has been fixed here: https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/4b46e8ebcb8ed9b897ea8ee113eed1dedfc43559

A new version of the package should be pushed out. @majkinetor @AdmiringWorm could one of you do that?

**Comment by gep13** [comment]
@mkevenaar are there any plans to fix the existing package versions that are failing validation?  Or should those be rejected?

**Comment by mkevenaar** [comment]
I will reject them. We can always un reject them if required.

**Comment by majkinetor** [comment]
We don't generally do that here.

**Comment by majkinetor** [comment]
@mkevenaar you had typo here

[AU winscp\5.17.2 winscp.install\5.17.2 winscp.**portalbe**\5.17.2]

**Comment by mkevenaar** [comment]
@majkinetor I added another commit to fix that just now.
