### ISSUE TITLE
Cmake not in path

### ISSUE THREAD

**Issue by manang** [chocolatey-community/chocolatey-coreteampackages#1444]
I'm trying to install cmake, but when I execute cmake, the command is not available
## Steps to Reproduce (for bugs)

1.choco install cmake
2.cmake <path>

**Comment by AdmiringWorm** [comment]
The CMake installer (which the package uses) makes cmake available on path by default, however it won't be available immediately.
You will need to either call `refreshenv` in your cmd or Powershell (assuming you have the profile correctly set up) shell, or re-launch your terminal to have it available.
