### ISSUE TITLE
(php) PHP 7.4 does not install required dependency VC++ Redistributable 2019

### ISSUE THREAD

**Issue by Silic0nS0ldier** [chocolatey-community/chocolatey-coreteampackages#1446]
Discovered when attempting to install composer (`choco install composer`). PHP 7.4 was installed to meet the dependency requirement beforehand, however VC++ Redistributable 2019 (https://visualstudio.microsoft.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2019) was not installed, resulting in composer being unable to install and PHP showing the following error.

```
C:\tools\php74\php.exe -v
PHP Warning:  'vcruntime140.dll' 14.0 is not compatible with this PHP build linked with 14.16 in Unknown on line 0
```

Installing VC++ Redistributable 2019 resolved the issue. Ideally this would be automatically installed.

## Expected Behavior

`choco install php` installs  VC++ Redistributable 2019 if not already installed to meet PHP 7.4 requirements.

## Current Behavior

`choco install php` does not install VC++ Redistributable 2019, leaving PHP 7.4 unable to be run.

## Possible Solution

Automatically install VC++ Redistributable 2019 if not already present.
Alternatively, show a warning if the requirement is not met to save on potential time spent tracing the issue cause.

## Steps to Reproduce (for bugs)

On a fresh environment (issue hit on Windows 10);
1. `choco install composer -y`
2. Note install fails once composer install commences (composer needs PHP to install)

## Context

Additional time spent resolving environment issues, more effort required to setup quick start script when reimaging (something I usually end up needing to do roughly every 6 months on multiple machines depending on how heavily each is used)..

## Your Environment

* Package Version used: Latest. at time was composer 5.1 and PHP 7.4.3
* Operating System and version: Windows 10 2004 19041.153 (Insider Slow Ring)
* Chocolatey version: 0.10.15
* Install/uninstall gist: ?

**Comment by AdmiringWorm** [comment]
The package `php` have `vcredist140` (VC++ redist 2019) as a dependency, make sure that you have the package `vcredist140` installed and that the version is `14.16` or higher.

I will bump the minimum version for the `php` package, but that won't be available until the next version of PHP is available.
