### ISSUE TITLE
(nodejs) No package available for 12.16.1

### ISSUE THREAD

**Issue by v1v** [chocolatey-community/chocolatey-coreteampackages#1453]
## Expected Behavior

To be able to install 12.16.1

## Current Behavior

```
 Installing nodejs version: 12.16.1 ...
 Chocolatey v0.10.11
 Installing the following packages:
 nodejs
 By installing you accept licenses for the packages.
 nodejs not installed. An error occurred during installation:
  Unable to resolve dependency 'nodejs.install (= 12.16.1)'.
 nodejs package files install completed. Performing other installation steps.
 The install of nodejs was NOT successful.
 nodejs not installed. An error occurred during installation:
  Unable to resolve dependency 'nodejs.install (= 12.16.1)'.
 Chocolatey installed 0/1 packages. 1 packages failed.
  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

 Failures

  - nodejs (exited 1) - nodejs not installed. An error occurred during installation:
  Unable to resolve dependency 'nodejs.install (= 12.16.1)'.
```

## Possible Solution
- Enable the version in https://chocolatey.org/packages/nodejs.install/12.16.1

## Steps to Reproduce (for bugs)
`choco install nodejs --version=12.16.1`

## Your Environment

Ubuntu 18.04

**Comment by AdmiringWorm** [comment]
The dependency `nodejs.install` was never approved due to what seems to be an intermittent failure on the verification tests, as such it was eventually rejected.

I have set it to run again and if all goes well it should be available for consumption in a few hours.

**Comment by AdmiringWorm** [comment]
Forgot to close this when the install package was automatically approved. @v1v can you test again, everything should work as you expected now.

**Comment by v1v** [comment]
Hi,

I missed your comment, I just verified and it works like a charm. See [here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-test-pipeline/detail/apm-test-pipeline/686/pipeline/406#step-415-log-27) 

Thanks for your prompt reply and fix :)
