### ISSUE TITLE
(vcredist140) Invalid urls in nuspec metadata file

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-coreteampackages#1454]
The Bug Tracker URL and the License URL is now invalid and points to webpages that no longer exist. Before any new releases of these packages can be pushed, we will need to fix or remove this URLs.

@jberezanski are you aware of the new locations of these two URLs?

**Comment by jberezanski** [comment]
Ah, sorry, did not notice this issue. I've fixed it already in https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/555432a32429e3cd5073c3fddff4637849b2ff4a.
