### ISSUE TITLE
(vim) Forgets package parameters on upgrade

### ISSUE THREAD

**Issue by kevinoid** [chocolatey-community/chocolatey-coreteampackages#1455]
##  Expected Behavior

When upgrading `vim`, package parameters would be preserved/respected.

## Current Behavior

During upgrade, package parameters are forgotten and the package is reinstalled with default parameters.

## Steps to Reproduce (for bugs)

On Windows 10 with Chocolatey installed and Vim not installed.:

1. `choco install vim -y --params "'/NoDesktopShortcuts /InstallDir:C:\Program Files'" --version=8.2.0486`
2. Observe that Vim is installed to `C:\Program Files` and no shortcuts appear on the desktop.
3. `cup -y vim`
4. Observe that a copy of Vim is installed to `C:\tools` and shortcuts appear on the desktop (the original copy in `C:\Program Files` remains, but is not referenced by start menu shortcuts or uninstaller info).

## Context

It is frustrating for the Vim shortcuts to reappear after every upgrade (since the package is upgraded near-daily) and confusing to have Vim installed in multiple places.

## Your Environment

* Package Version used: 8.2.0486 upgrading to 8.2.0488 (also observed during previous upgrades)
* Operating System and version: Windows 10 Build 18363
* Chocolatey version: v0.10.15
* Install/uninstall gist: ???

Thanks for considering,
Kevin

**Comment by mkevenaar** [comment]
@kevinoid This could be done using the Chocolatey Feature [useRememberedArgumentsForUpgrades](https://chocolatey.org/docs/chocolatey-configuration#general-1)

`choco feature enable --name="'useRememberedArgumentsForUpgrades'"` to enable

**Comment by kevinoid** [comment]
Thanks @mkevenaar, that works great!  Sorry for the noise.
