### ISSUE TITLE
(vscode.portable) Migrate VSCode portable to meta package

### ISSUE THREAD

**Issue by some1one** [chocolatey-community/chocolatey-coreteampackages#1459]
## Expected Behavior
The vscode portable package should support similar options and share code with the install package. It should live in this repository along with the other vscode packages. It should install very similarly to the vscode package but it will live inside the chocolatey library as a portable application.

## Current Behavior
vscode.portable is currently located and maintained in the echizenryoma/Chocolatey-Package repository.

## Possible Solution
I am ready to make a pull request but I wanted to get with the package maintainers to make sure the transition would go smoothly. It is currently not a virtual or meta package (no shared code with vscode.install) but it follows the same format as the install package. Along with that, the uninstall script has not had the uninstall process for the context menu added.

## Context
I wanted standardize the vscode.portable package and add more flexibility to the install. Would I would like to see as the end result is the ability to run a chocolatey install to create a  ready-to-go vscode environment to use with the remote development extensions.

Related Maintainers:
@echizenryoma
@pascalberger
@AdmiringWorm 
@jack1142 
@jivkok

**Comment by AdmiringWorm** [comment]
@some1one feel free to open a PR to add that package to the repo, just make sure it follows our [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) and that you have permission from the maintainer of the package to move it here.
