### ISSUE TITLE
(cutepdf) SHA265 Checksum out of date

### ISSUE THREAD

**Issue by matstocks** [chocolatey-community/chocolatey-coreteampackages#1461]
Error - hashes do not match. Actual value was '23294C7A93BE6F5A1D973155DCFA54957
6FD918A8C5422AA42419296AB2A720B4D62DBE718C87C2A7C293930C67CF30EC7F97106B1E51D703
249AC2DB81ACD8A'.
ERROR: Checksum for 'C:\WINDOWS\TEMP\chocolatey\CutePDF\4.0.0.201\CuteWriter.exe
' did not meet '88490EB055EB1F594B30436CD299D5F0C1B425978128424EBF3D3124B6B9E42CC9E0E8FC556B1FA3589A1E76E4E23D99D4647DADA4EED0A0CE598C4357E8996A'

**Comment by AdmiringWorm** [comment]
I have triggered a forced update of this package, it wasn't updated because the remote version is exactly the same as the version already available on chocolatey.org.

I will close this issue when I get a notification that it have been pushed.

**Comment by AdmiringWorm** [comment]
updated version is available
