### ISSUE TITLE
(kitty) correct shim icon

### ISSUE THREAD

**Issue by CWempe** [chocolatey-community/chocolatey-coreteampackages#1463]
It would be great if the shim for `kitty.exe` would have the correct icon from the original program.

this works for other programs, but not for kitty.

![image](https://user-images.githubusercontent.com/1270359/80020545-860d2700-84d9-11ea-890b-a16715b92607.png)

**Comment by AdmiringWorm** [comment]
The package itself don't generate the shim, and it is chocolatey itself that generates shims for any `.exe` files located in the package.

I have no idea why the icon don't show up though, could be that the `.exe` don't have an icon and thus not detected by the shim utility.

I'll add this as an `Up for Grabs` as there probably is something we can do to add an icon (like specifically calling a function to generate the shim with a separate icon).

**Comment by cyd01** [comment]
KiTTY has many icons as you can see on that [page](https://www.9bis.net/kitty/#!pages/kitty_icon.md).  
The first one is the [official one](https://www.9bis.net/kitty/img/kitty.ico):  
![](https://www.9bis.net/kitty/img/kitty.ico).

I'm not sure, but I guess it has been an issue with the compressor binaries that I use: [UPX](https://upx.github.io/).
Can you test with the [KiTTY uncompressed version](https://www.fosshub.com/KiTTY.html?dwl=kitty_nocompress-0.74.4.3.exe) please ?

**Comment by CWempe** [comment]
Looks better.

At least Windows is able to show/extract the icons.

![image](https://user-images.githubusercontent.com/1270359/103932008-8447ca00-5121-11eb-925e-ca963c68bf81.png)

But I don't know to proceed with this information.
I guess it would not make sense to renounce compression just for a few chocolate users. 😄

**Comment by AdmiringWorm** [comment]
@CWempe I think it is fine to change the package to use the uncompressed edition.
TBH, this change should probably have been done quite some time ago (I personally never got around to it), and since it is just a 1,3-1,4 MB difference, it shouldn't matter too much to the majority of users.

I will be updating the script that checks for updated versions of kitty later this week to use the uncompressed edition, however, if you want to provide a PR to update it instead then feel free to do so.

**Comment by cyd01** [comment]
For your information: compressed version, has sometimes issues with some anti-virus. I suggest you to use the uncompressed version for that reason too. Don't forget to add the `kitty.ini` configuration file in the same directory where `kitty.exe` is, with the right save mode selection:
- `savemode=dir` for portable mode
- `savemode=reg` for classic mode (in registry)

**Comment by AdmiringWorm** [comment]
The changes to use the uncompressed edition of kitty is now added to the repository, I have not pushed a fix version to the chocolatey repository but will be available with the next time a new version of kitty is available.
