### ISSUE TITLE
(gimp) Requires a rewrite of updater to detect updated revisions

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-coreteampackages#1464]
Due to gimp developers not releasing a new version of the software for **minor** bug fixes, but rather pushes new revisions of the software/installer instead, we need to take into account this when checking for updates of the software.

This requires the need to rewrite the updater to make this happen correctly.

*The packages is also outdated because of this 😢*

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Should the fix version be something like
`2.10.18.2` or `2.10.182`  or `2.10.18.20200423`

Just curious to the correct way to implement it.

**Comment by AdmiringWorm** [comment]
@RedBaron2 it would be `2.10.18.2`.
