### ISSUE TITLE
(vim) - Prevent install script from wiping current directory.

### ISSUE THREAD

**Issue by gonzolively** [chocolatey-community/chocolatey-coreteampackages#1467]
I'd like to request that this installer not wipe it's current install directory as a part of upgrade. This is very disruptive as I have my .vimrc, as well as all my plugins in that folder. The solution right now is to skip upgrades to vim completeley in order to keep my config. This installer needs some serious attention.

## Expected Behavior
I'd love to be able to run `choco upgrade vim` and not have all of my config files and plugins wiped out everytime...which we know happens a lot as vim has a pretty aggressive release pattern.

## Possible Solution
Maybe stash the contents of the current package directory in a temp location and add back as a post-install step?

## Your Environment

* Package Version used: vim (all)
* Operating System and version: Windows 10 Professional
* Chocolatey version: 0.10.15

**Comment by matsuhav** [comment]
I summarized upgrade scenarios.
1. Upgrading from version 8.X to 8.Y
1.1 `$VIMRUNTIME` (i.e. `C:\tools\vim\vim8X`) directory is wiped.
1.2 Both new files and modified files are deleted.

2. Upgrading from version 8.2.XXXX to 8.2.YYYY
2.1 New files are preserved.
2.2 Files which are distributed with Vim and you modified are overwritten.

System-wide configs (`C:\tools\vim\vim8X` directory) are treated inconsistently. 
User-specific configs (`$HOME\vimfiles` directory) are preserved completely in any case.
Unfortunately there is no way to distinguish files you modified and we can't solve 2.2.

Copying will make scenario 1 behave the same as scenario 2. This increases consistency.
It preserves newly installed files but, modified files would be overwritten anyways.

---
It is not the recommended way to put files in `$VIMRUNTIME`.
Any upgrade could overwrite files.

We should think `$VIMRUNTIME` (`C:\tools\vim\vim8X`) directory is for files distributed with Vim.
Please see [:help runtimepath](https://vimhelp.org/options.txt.html#%27runtimepath%27)

If we want system-wide configs, we should put files in some shared directory and add it to `runtimepath` in `C:\tools\vim\_vimrc`

If we have only one user on our PC, we should put files in `$HOME\vimfiles`.
