### ISSUE TITLE
(fah) new version 7.6.13 available

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-coreteampackages#1470]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
Wrong repository, the `fah` package is not maintained in this repository.
Please contact the actual maintainer of the package.
