### ISSUE TITLE
(python3) Installer prints bogus warning about install directory

### ISSUE THREAD

**Issue by HunterZ** [chocolatey-community/chocolatey-coreteampackages#1477]
## Expected Behavior

Chocolatey python3 install script should determine the actual location to which it ends up installing, and should not print a warning about some other path that some other copy of Python happens to live in.

## Current Behavior

Install script warns that it is installing to the location of a copy of Python in a subdirectory of my GOG Galaxy folder, but it actually ends up installing to the correct place (C:\Python38).

GOG Galaxy's Python folder does NOT appear anywhere in the Registry or in my environment variables, so I don't know how the install script is even finding it.

```
python3 v3.8.3 [Approved]
python3 package files upgrade completed. Performing other installation steps.
Installing 64-bit python3...
python3 has been installed.
WARNING: Provided python InstallDir was ignored by the python installer
WARNING: Its probable that you had pre-existing python installation
WARNING: Installed to: C:\Program Files (x86)\GOG Galaxy\python
WARNING: Installation folder is not the default. Not changing permissions. Please ensure your installation is secure.
  python3 can be automatically uninstalled.
 The upgrade of python3 was successful.
  Software installed as 'exe', install location is likely default.

python v3.8.3 [Approved]
python package files upgrade completed. Performing other installation steps.
 The upgrade of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
python3 v3.8.3 is the latest version available based on your source(s).
```

## Possible Solution

Use a different method for determining the existing Python install location that doesn't return bogus results. My `HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.8\InstallPath` Registry key lists the correct location, for example (`C:\Python38\`).

## Steps to Reproduce (for bugs)

1. Install an old version of Python via Chocolatey?
2. Install GOG Galaxy
3. Attempt to update Python via Chocolatey
4. Observe the bogus warning

## Context

Makes me think that something is wrong, when everything is actually fine. Debugging cost me the same amount of time that upgrading manually would have cost, negating some of the advantage of Chocolatey.

## Your Environment

* Package Version used: 3.8.3
* Operating System and version: Windows 10 x64 v1909
* Chocolatey version: v0.10.15
* Install/uninstall gist: Sorry, I don't run debug logs during normal use, and the upgrade is complete, so it's too late.

**Comment by HunterZ** [comment]
FYI, another person reported similar behavior: http://disq.us/p/28sa09l

**Comment by AdmiringWorm** [comment]
This issue have been resolved in the repository, and a package fix is in the process of being submitted to chocolatey.org for version 3.8.x (fix versions for older versions and beta versions are not planned at this time).
