### ISSUE TITLE
(avidemux) Outdated

### ISSUE THREAD

**Issue by aminya** [chocolatey-community/chocolatey-coreteampackages#1480]
The latest version is 2.7.5
https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/avidemux

**Comment by gep13** [comment]
To add to this, I have just been back to test the previously reject package version:

https://chocolatey.org/packages/avidemux/2.7.4

Looks like there is a problem with the silent installation arguments.  When testing on the Chocolatey Test Environment, it gets to this point:

![image](https://user-images.githubusercontent.com/1271146/82835653-93dd1000-9ebc-11ea-8c5c-c493225d35f8.png)

And then doesn't progress any further.

**Comment by majkinetor** [comment]
This requires some non-trivial update.

Like I said [here](https://chocolatey.org/packages/avidemux#comment-4930608308), we have a working package forever so if there is no personal use in coreteam, there is no incetive to fix random software (we got from 2 active maintainers to 0.1 active maintainers in last year).

**Comment by aminya** [comment]
There is always a possibility to email the original developer: http://avidemux.sourceforge.net/

**Comment by majkinetor** [comment]
That rarelly works, but u cant blame one for trying.

**Comment by majkinetor** [comment]
https://chocolatey.org/packages/avidemux/2.7.5
