### ISSUE TITLE
(Firefox) Firefox reinstalling without force

### ISSUE THREAD

**Issue by gregoryka** [chocolatey-community/chocolatey-coreteampackages#1495]
When performing `choco upgrade Firefox`, if firefox is already installed and up to date the package will still go through the entire installation process. 

## Expected Behavior
The package will detect an up to date install and skip the installation.

## Current Behavior
The package detects the install is up to date, but reinstalls anyway.

## Possible Solution
The problem is in chocolateyInstall.ps1, line 48.
`if ($alreadyInstalled -and $env:ChocolateyForce) {`
it seems to me a -not was forgotten before $env:ChocolateyForce, causing the package to install when it is up to date and not forced(conversely, if it was forced it would skip the install).

## Steps to Reproduce (for bugs)
1. Install firefox latest version(or update existing install via firefox about menu)
2. Perform `choco upgrade Firefox`
3. Package downloads and installs needlessly

## Your Environment

* Package Version used: 77.0.1
* Operating System and version: Windows 10 Version 1903
* Chocolatey version: 0.10.15
* Install/uninstall gist: `choco upgrade Firefox`

**Comment by AdmiringWorm** [comment]
A fix have been implemented for the package, and if all goes well, a new package fix version should be available on chocolatey.org in a few hours (could take longer).
