### ISSUE TITLE
(cutepdf) cannot upgrade, fails with exit code 1, must uninstall and reinstall to update

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-coreteampackages#1500]
## Expected Behavior

That `choco upgrade cutepdf` will upgrade CutePDF without errors.

## Current Behavior

Running `choco upgrade cutepdf` fails with
```
ERROR: Running ["C:\ProgramData\chocolatey\lib\cutepdf\tools\CuteWriter.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- ] was not successful. Exit code was '1'. See log for possible error messages.
```

I can install the updated version if I uninstall and then reinstall

## Possible Solution

If I try to run the `4.0.0.401` installer manually with version `4.0.0.300` being installed, it tells me that I must uninstall the current version before installing the new version.
![image](https://user-images.githubusercontent.com/38865330/85597226-0d793280-b610-11ea-8f63-c59534a63acf.png)

So I presume the solution is to change the install script to try to uninstall the old version of CutePDF before installing the new one. 

## Steps to Reproduce (for bugs)

1. Install a recent but outdated version of CutePDF, I used `4.0.0.300`. The installer must have been downloaded previously and internalized into the package since it is no longer available to download. 
2. Run `choco upgrade cutepdf`

## Your Environment

* Package Version used: `4.0.0.300` upgrading to `4.0.0.401`
* Operating System and version: Win10 x64 2004
* Chocolatey version: 0.10.15
* Install/upgrade gist: https://gist.github.com/TheCakeIsNaOH/8f4bc05d5f284951e2ce44b2cc73cf5c

**Comment by hobbes** [comment]
hello, just to chime in: that problem is still present in current chocolatey / cutepdf, has this fix been released ?

**Comment by majkinetor** [comment]
No, we thought it has quick release cycle but I guess that was during first half of 2020. I will force it now.
