### ISSUE TITLE
CCleaner 5.68 is still installing 5.67

### ISSUE THREAD

**Issue by virtualex-itv** [chocolatey-community/chocolatey-coreteampackages#1501]
## Expected Behavior
The new version 5.68 should install when running `choco install ccleaner`

## Current Behavior
The old version 5.67 get's installed instead

## Possible Solution
AdmiringWorm will look into this as I've brought it to his attention.  He asked if I could file this as an issue to keep track until he can look into it later next week.

## Steps to Reproduce (for bugs)

```
> choco install ccleaner -y

Chocolatey v0.10.15
Installing the following packages:
ccleaner
By installing you accept licenses for the packages.
Progress: Downloading ccleaner 5.68.7820.20200624... 100%

ccleaner v5.68.7820.20200624 [Approved]
ccleaner package files install completed. Performing other installation steps.
Downloading ccleaner
  from 'https://download.ccleaner.com/ccsetup567.exe'
Progress: 100% - Completed download of C:\Users\virtualex\AppData\Local\Temp\chocolatey\ccleaner\5.68.7820.20200624\ccsetup567.exe (24.66 MB).
Download of ccsetup567.exe (24.66 MB) completed.
Hashes match.
Installing ccleaner...
ccleaner has been installed.
 The install of ccleaner was successful.
  Software installed as 'EXE', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

```

## Your Environment
* Package Version used: 5.68.7280.20200624
* Operating System and version: Windows 10 x64 v2004
* Chocolatey version: 10.15.0
* Install/uninstall gist: choco install -y ccleaner

**Comment by AdmiringWorm** [comment]
I could not determine what caused the issue on the appveyor server, but the correct package fix version have been pushed to chocolatey.org. As such I am closing this now.
