### ISSUE TITLE
(ffmpeg) 4.3 build missing libx264, libx265

### ISSUE THREAD

**Issue by KeenRivals** [chocolatey-community/chocolatey-coreteampackages#1503]
## Expected Behavior
``ffmpeg -encoders`` includes libx264, libx265

## Current Behavior
``ffmpeg -encoders`` doesn't include libx264, libx265

## Possible Solution
It looks like upstream rebuilt the package with the needed libraries. ffmpeg @ chocolately might just need a rebuild too.

## Steps to Reproduce (for bugs)

1. Run ``ffmpeg -encoders``, check for  libx264, libx265 in output.

## Context
Cannot use the x264 or x265 encoder in ffmpeg.

## Your Environment

* Package Version used: 4.3
* Operating System and version: Windows 10 2004

**Comment by AdmiringWorm** [comment]
@majkinetor would you be able to force a new package fix for the ffmpeg package?
The latest compiled binary on the location we use as the source should have been rebuild (checksums have at least changed), but is still under the same version so a fix version is needed.

I am unfortunately unable to do that myself until the coming weekend.

**Comment by majkinetor** [comment]
By the time it took you to write that message you could do it from GitHub UI ? :)

**Comment by AdmiringWorm** [comment]
@majkinetor 

1. I do not like making commits through the GitHub UI
2. It do not allow empty commits
3. I am on a very slow and unstable network connection, so no it would have been faster to make the changes than adding aa commit (it would actually take way longer time).

Anyways, thanks for forcing the new fix version.

**Comment by majkinetor** [comment]
One of the goals of entire AU setup was to enable you quick ad hoc interventions via GitHub UI. I am not saying you should use it for other stuff in general. To circumvent empty commit, I add space in main readme or delete it.

**Comment by KeenRivals** [comment]
Thanks for forcing the rebuild. Confirming issue is resolved!
