### ISSUE TITLE
(dropbox) should be version 100.4.409

### ISSUE THREAD

**Issue by RedBaron2** [chocolatey-community/chocolatey-coreteampackages#1504]
@AdmiringWorm @gep13 @majkinetor @ferventcoder 

The current stable version is 100.4.409, but the current version for chocolatey is version 99.4.501

**Comment by AdmiringWorm** [comment]
It looks like the updater is failing to update due to a `Forbidden` response from the server.
```
au_GetLatest failed
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
```
https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#dropbox

**Comment by RedBaron2** [comment]
@AdmiringWorm the error if forbidden is due to the version being passed to the URL check in the script.
(Example: latest version `99.6.54` version that gets passed to the URL check is `99.6.54`, but since the latest version is `100.4.321` the version that gets passed to the URL check is `00.4.321` which results in a forbidden URL error )

**Comment by RedBaron2** [comment]
We will be working on a new updater for this package. Website and versioning changes make this a need for this package.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Since the merging of PR #1508 . I will now close this issue.
