### ISSUE TITLE
(cygwin) package doesn't update installer 

### ISSUE THREAD

**Issue by musm** [chocolatey-community/chocolatey-coreteampackages#1505]
Cygwin upgrade need to also check and update the installer https://cygwin.com/setup-x86_64.exe to the latest version

**Comment by AurelienCordonnier** [comment]
Copy from chocolatey Disqus, 2 month ago : It seems that 'cygwinsetup.exe' is not updated when a new version is pushed. Lately, I have been forced to update my packages by downloading the setup directly, without chocolatey...
Putting the setup-x86_64.exe in the choco install directory was solve my problem temprarily.

**Comment by tunisiano187** [comment]
It's been updated July 13th so i think, you can close this issue.

**Comment by nutterthanos** [comment]
setup file last updated 28 June 2020

**Comment by AdmiringWorm** [comment]
Closing, as looking at our update script the latest version of the setup file gets downloaded on each new release.
As such, I don't believe there is much for us to do.

If you disagree, please let us know and we can re-open the issue.

**Comment by riedel** [comment]
@AdmiringWorm: Can you please reopen this ticket. It would be easy to actually rather track the setup version as it much more relevant to chocolatey as cygwin brings its own package manager. A good solution would be adding the setup version as in the cygwin version string.
