### ISSUE TITLE
(python) [URGENT] 3.9.0-b5 is installed through 'upgrade all', despite --pre not being set

### ISSUE THREAD

**Issue by ImportTaste** [chocolatey-community/chocolatey-coreteampackages#1510]
For some reason, 3.8.5 appeared in the python3 package but not in the python package. I ran an upgrade all operation.

'python' initially stayed at 3.8.4
'python3' then runs its upgrade operation, upgrading to 3.8.5, its dependency is 'python' and so it tries to match version numbers, but since python did not have 3.8.5, it instead then installed 3.9.0-b5 as well.

I ended up with Python 3.8.4, 3.8.5, and 3.9.0-b5 install data in my Windows Apps & features section. It's a mess. This needs to be fixed ASAP.

**Steps to replicate, starting with no python packages installed:**
1. `choco install python --version 3.8.4 -y`
2. `choco upgrade all -y` OR `choco upgrade python python3 -y`

**Comment by ImportTaste** [comment]
Someone in chat just replied to me that the metadata for python --version 3.8.5 exists: https://chocolatey.org/packages/python/3.8.5

But it does not show up in the Version History: ![](https://files.catbox.moe/w37hak.png)

**Comment by ImportTaste** [comment]
I have no clue what's going on. Someone in chat was unable to reproduce it. I'm just going to close this.

3.8.5 still does not appear in the version history of these packages on the site, however. I have to think it's somehow related. This seems like an issue with the site itself.

**Comment by AdmiringWorm** [comment]
> Someone in chat just replied to me that the metadata for python --version 3.8.5 exists:

That someone would be me, but as I mentioned on gitter there isn't anything wrong from a package perspective, but could be a bug in the choco client itself, or an intermittent error.

**Comment by ImportTaste** [comment]
Well, this might be a clue as to why it happened. Or this might just be a red herring.
```
WARNING: Provided python InstallDir was ignored by the python installer
WARNING: Its probable that you had pre-existing python installation
WARNING: Installed to: C:\Program Files (x86)\Streamlink\Python
WARNING: Installation folder is not the default. Not changing permissions. Please ensure your installation is secure.
```
(streamlink is installed through chocolatey as well)
