### ISSUE TITLE
(kubelogin) adding a new automatic package?

### ISSUE THREAD

**Issue by jetersen** [chocolatey-community/chocolatey-coreteampackages#1511]
I would like to contribute an automatic package for kubelogin.
The maintainer is kind enough to offer 64 bit builds on github releases: https://github.com/int128/kubelogin/releases

Before starting the work, I would ask if this something your open to or should I maintain the chocolatey package in my own repo.

**Comment by AdmiringWorm** [comment]
Sorry about the late response (this issue must have gone under my radar).

We are generally open to accepting new packages, as long as the package is up to our standards (as defined in the [Contributing](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) documentation )).

Just be aware that you (assuming you will be the one that submits the package to the repository) will still be considered the actual maintainer of the package, and will be responsible for fixing issues related to it (as a general note, we will step in when it is necessary to do so).

**Comment by jetersen** [comment]
Great, I got side tracked myself. I'll get back to opening a PR.

**Comment by jetersen** [comment]
will AU upload itself or do I have to create it?

**Comment by majkinetor** [comment]
It will handle it once you fix this error:

https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors

**Comment by jetersen** [comment]
hmm could I reuse the kubernetes logo? Kubelogin does not have one.

**Comment by majkinetor** [comment]
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#125-provide-icon

**Comment by jetersen** [comment]
Could I be added as package manager for the kubelogin package? my profile: https://chocolatey.org/profiles/jetersen

**Comment by majkinetor** [comment]
We don't generally practice that as you can always PR here and we have single package authority.

**Comment by jetersen** [comment]
sure thing, still learning. Just wanted to be able to see approval and the likes 😅

**Comment by AdmiringWorm** [comment]
@jetersen you have been added as a maintainer for the kubelogin package.
You should have received an email with a link to confirm your addition.

**Comment by jetersen** [comment]
Many thanks 🙇

**Comment by jetersen** [comment]
Still awaiting approval, sadly means no `choco install kubelogin` joy 😓
