### ISSUE TITLE
(firefox) Specific language not taken into account

### ISSUE THREAD

**Issue by vMaGa** [chocolatey-community/chocolatey-coreteampackages#1514]
Installation with specific language seems not working... I tried to force french language or en-GB, but it is always redirected to en-US. However, for example, when I try manually this link "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=fr", it goes really to the french package. During the installation I saw in the console that the downloaded package is with "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US"

## Possible Solution
Comment from @AdmiringWorm : "Looks like there is a need to update the script that are checking for firefox updates"

**Comment by tinydew4** [comment]
It seems that the content of LanguageChecksums.csv has been removed from this commit:
https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/2bb76a6458cb05f92c3b7e93bf49a4ed3208b853

**Comment by AdmiringWorm** [comment]
I hope to be able to look into the issue sometime this weekend unless someone else is willing to open a PR to fix the issue.

I am going off on the assumption that the formatting of the links on the website have changed, and thus the locales are no longer being detected during the update checks.

**Comment by AdmiringWorm** [comment]
I have identified what caused the empty LanguageChecksums.csv file, and have updated the updater with a fix.
A fixed version of the firefox package is being queued to be pushed to chocolatey.org while I am typing this.

**Comment by AdmiringWorm** [comment]
Re-opening this issue, as there is a problem with the builds we are running on appveyor and thus is preventing us to push a new version (I will close this issue when we are able to run builds on appveyor again).

**Comment by gerdlimbeck** [comment]
still open this bug?

**Comment by gerdlimbeck** [comment]
Bug is still present:
`C:\Windows\system32>choco upgrade chocolatey`
`Chocolatey v0.10.15`
`Upgrading the following packages:`
`chocolatey`
`By upgrading you accept licenses for the packages.`
`chocolatey v0.10.15 is the latest version available based on your source(s).`

and then

`C:\Windows\system32>choco install firefox /l:de`
`Chocolatey v0.10.15`
`Installing the following packages:`
`firefox`
(...)
`Downloading Firefox 64 bit`
`  from 'https://download.mozilla.org/?product=firefox-79.0-ssl&os=win64&lang=en-US'`

**Comment by AdmiringWorm** [comment]
@gerdlimbeck new package versions don't get immediately approved on chocolatey.org, it takes time before between the package gets pushed and it is available for normal consumption.

A fixed version didn't get pushed before this issue was closed: https://chocolatey.org/packages/Firefox/79.0.0.20200805
