### ISSUE TITLE
(LibreOffice) Implement Proxy Authentication based on Install-ChocolateyPackage

### ISSUE THREAD

**Issue by wget** [chocolatey-community/chocolatey-coreteampackages#1515]
Internal function `GetLibOExactVersion` from the LibreOffice streams helpers I wrote is not supporting proxies.

## Expected Behavior
Handle proxy.

## Current Behavior
Fails with a 407 error.

## Possible Solution
Reuse the code from Install-ChocolateyPackage

## Steps to Reproduce (for bugs)
1. Use a HTTP proxy
2. Try to install LibreOffice
3. Fails because the internal helper function is not supporting proxy

## Context
Reported via a comment on the Chocolatey Store:
https://chocolatey.org/packages/libreoffice-still#comment-5012607851

## Your Environment
N/A

**Comment by RedBaron2** [comment]
@wget @ferventcoder 
I will make the suggestion that the proxy detection used by Install-ChocolateyPackage script should be made into it's own helper script. This would make usage in other packages easier in the future.
Right now the proxy detection lines of code are used in three chocolatey functions.

**Comment by wget** [comment]
@RedBaron2 Could you please be more meaningful about this and point me to the aforementioned 3 files already using the proxy detection code?

**Comment by RedBaron2** [comment]
I will fill this in later with the actual lines for the proxy detection code

1.

2.

3.
