### ISSUE TITLE
How about deactivating AppVeyorBot's comments on PRs?

### ISSUE THREAD

**Issue by felipecassiors** [chocolatey-community/chocolatey-coreteampackages#1519]
In my last two PR's (https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1517 and https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1512), most of the comments are just repeated AppVeyorBot's messages: "Verification failed", "Verification completed". All these comments sadly also goes to the mailboxes of the people subscribed to the PR.

I wonder, is it really needed? GitHub Checks already prevent PRs from merging without CI's success, and everyone can see realtime status without having to receive comments for that. 

![image](https://user-images.githubusercontent.com/29582865/89555199-1ef45380-d7e6-11ea-8db8-aaf3f5ab4d08.png)

**Comment by AdmiringWorm** [comment]
> I wonder, is it really needed?

Yes, it is needed (maybe not for multiple approved messages, but for failing builds they certainly are).

> GitHub Checks already prevent PRs from merging without CI's success, and everyone can see realtime status without having to receive comments for that.

They only prevent the merge if protected branches are enabled, which can not be enabled at this time.
Also, the comments were added on purpose as when only having the checks, the submitter typically ignored them.

So bottom line, they will not be removed.

**Comment by felipecassiors** [comment]
> They only prevent the merge if protected branches are enabled, which can not be enabled at this time.

Does the comments prevents that?

**Comment by AdmiringWorm** [comment]
No, they do not.
They are more for the submitter to take notice, and to a reviewer to mention that latest build was successful/failed (if they subscribe to the pull request).

**Comment by felipecassiors** [comment]
> They are more for the submitter to take notice, and to a reviewer to mention that latest build was successful/failed (if they subscribe to the pull request).

If for historical reasons the users does not pay attention to the checks, but only to the comments, I understand, despite I can't imagine such a situation.

**Comment by AdmiringWorm** [comment]
> despite I can't imagine such a situation.

That has happened (generally because they didn't get some notification of whether something worked or not), some even still ignore the comments (very few, thankfully).

**Comment by felipecassiors** [comment]
I see. Thank you so much for the clarifications!
