### ISSUE TITLE
(WindowBlinds) new version (10.84) available

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-coreteampackages#1520]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
The WindowBlinds package is not hosted in this repository, only packages that have the `chocolatey` user are available in this repository.

Please contact the actual maintainer of the package by using the `Contact Maintainers` on the package page.

**Comment by mstick99** [comment]
Had contacted the maintainer but there was no response so thought to try here. Oh well no big deal.

**Comment by AdmiringWorm** [comment]
@mstick99 if you do not get a response from the maintainer (using the `Contact Maintainers` link), then the next step is to use the `Contact Site Admins` link instead (when sending that message, you should mention if you wish to become the new maintainer or not).

This is detailed in the [Package Triage Documentation](https://chocolatey.org/docs/package-triage-process).
