### ISSUE TITLE
(libreoffice-fresh) - Not auto-updating to version 7

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-coreteampackages#1526]
It's at 6.4.6, which is where the Still version should be. Still is... still on 6.3.6.

**Comment by RedBaron2** [comment]
@wget 
If you could take a look at why it isn't updating. It appears to only be feeding `a a a` to the LinkArray variable. Thanks

**Comment by wget** [comment]
@RedBaron2 Thanks will do :)

**Comment by wget** [comment]
Btw, the auto update process to 7 is normal. The TDF sysadmin team has not pushed the 7.0 version to the update service yet :)

**Comment by opusforlife2** [comment]
Oh. That's interesting. Do you know the reason why TDF is maintaining such a large gap between the release and automatic updates? Server load, maybe?

**Comment by RedBaron2** [comment]
@wget 
I'm curious as to the reasoning for using TDF's update services to update this package on chocolatey.
It seems to lag behind other methods used by other AU updated packages that use
- blogs from the developer
- website download pages
- GitHub release tags
- other FOSS websites

I'm just curious to know the reasoning that this approach was chosen. It seems to be very inefficient.

**Comment by RedBaron2** [comment]
@wget 
The new current version is `7.0.1`
It doesn't seem to be the script.
My local forked copy of the repo updated to this new version on `9/3/2020`

**Comment by opusforlife2** [comment]
Now it's at 7.0.2.

**Comment by RedBaron2** [comment]
@opusforlife2 
After the PR gets approved the package should be updated to the latest builds.

**Comment by opusforlife2** [comment]
Thank you!

**Comment by wget** [comment]
> @wget
> I'm curious as to the reasoning for using TDF's update services to update this package on chocolatey.
> It seems to lag behind other methods used by other AU updated packages that use
> 
>     * blogs from the developer
> 
>     * website download pages
> 
>     * GitHub release tags
> 
>     * other FOSS websites
> 
> 
> I'm just curious to know the reasoning that this approach was chosen. It seems to be very inefficient.

Simple. That way, TDF controls the updates :)
