### ISSUE TITLE
(PIA) new version 2.3.1 available

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-coreteampackages#1529]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
As I told you when you opened a different issue 2 weeks ago:

> The WindowBlinds package is not hosted in this repository, only packages that have the chocolatey user are available in this repository.

> Please contact the actual maintainer of the package by using the Contact Maintainers on the package page.
