### ISSUE TITLE
(supertuxkart) Outdated

### ISSUE THREAD

**Issue by pataluc** [chocolatey-community/chocolatey-coreteampackages#1532]
Supertuxkart 1.2.0 just released: https://blog.supertuxkart.net/2020/08/supertuxkart-12-release.html

Changelog is here: https://github.com/supertuxkart/stk-code/blob/1.2/CHANGELOG.md, binaries moved to github here: https://github.com/supertuxkart/stk-code/releases/tag/1.2

;)

**Comment by RedBaron2** [comment]
@pataluc @AdmiringWorm 
I will submit a PR for this later today. It needs a better regex to get those new links.
