### ISSUE TITLE
(wixtoolset) Include Visual Studio integration

### ISSUE THREAD

**Issue by aminya** [chocolatey-community/chocolatey-coreteampackages#1536]
wixtoolset does not include Visual Studio integration

https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2019Extension
https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2017Extension

This integration is needed for developing packages (such as ChocolateyGUI). Based on the documentation installing wixtoolset should be enough, but I could not build ChocolateyGUI until I installed the visual studio integration extensions.
https://github.com/chocolatey/ChocolateyGUI#building

**Comment by RedBaron2** [comment]
@aminya 
This is not a package that is handled in this repository, but I'm going to ask for this issue to be moved by @gep13 
Thanks for the report and @gep13 for the assistance.

**Comment by gep13** [comment]
@RedBaron2 why are you saying that this package isn’t maintained here?

https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/wixtoolset

**Comment by RedBaron2** [comment]
@gep13 
`wixtoolset` is but the `wix visual studio extension` is not handled here.

I called you in to check if this is truly a package problem or if Chocolatey GUI needs to list it as a requirement.

Though now as I have looked closer into it. `wix visual studio extension` seems to need to be made into a chocolatey package, but this is not a issue of the `wixtoolset` package IMHO.

**Comment by RedBaron2** [comment]
Currently working on the extension package for wix toolset.

Would like to know?
- preferred idea for naming this package @gep13 

- dependency only on wix toolset
- dependency on wix toolset and visual studio

Thanks for the assistance

**Comment by aminya** [comment]
Thank you for working on this! I think it's best to keep the original name so people can find it! I had preferred them included in the WiX toolset itself, but that's just my opinion, and there are many other good reasons for not doing so.

**Comment by gep13** [comment]
@RedBaron2 apologies, I never read the original issue properly!

@aminya would you be in a position to send a PR to correct the documentation for this on the Chocolatey GUI repository?

@RedBaron2 there are existing Visual Studio Extensions out there, for example: https://chocolatey.org/packages/visualstudio2017-powershelltools so I would suggest in terms of naming conventions, that similar to the existing be used.  Notice the depedency on this package: https://chocolatey.org/packages/chocolatey-visualstudio.extension which helps with installations in newer versions of Visual Studio.

**Comment by RedBaron2** [comment]
> @aminya wrote: 
> If you are going separate probably you should create one for each Visual Studio version (the same as vcbuildtools).

This will have a separate package for each version currently supported on Wix website.

@gep13 
This should follow the current naming convention 🤞 
Current name of package will be `wixtoolset-visualstudio<year>extension` the variable `<year>` would be swapped out for 2010 through 2019

This will install through chocolatey the `wixtoolset` package if not installed, and will check the registry for a valid uninstall key for `visualstudio`. If no key for `visualstudio` found the package will fail to install writing a warning on the screen of
_**Visual Studio not found installed on the system. This package will not be installed.**_
It will be up to the consumer to install the correct extension for their `Visual Studio`.

I will work on submitting the PR next week.

**Comment by AdmiringWorm** [comment]
> This should follow the current naming convention 🤞
> Current name of package will be `wixtoolset-visualstudio<year>extension` the variable `<year>` would be swapped out for 2010 through 2019

Indeed, it should follow the naming convention.
Using `wixtoolset-visualstudio<year>extension` is not following the convention though.
It is an extension to visual studio, not for wixtoolset as that name would imply.

The correct name would be:
```
visualtudio<year>-wixtoolset
```

**Comment by RedBaron2** [comment]
@AdmiringWorm 
I point out what is written on WiX Website
> **WiX Toolset Visual Studio Extension** this extension provides integration for the **WiX Toolset** into **Visual Studio**

Though I will submit the PR with the name of
'visualtudio<year>-wixtoolset`

**Comment by RedBaron2** [comment]
@gep13 @ferventcoder 
I closed my PR because of [issue](https://github.com/chocolatey/choco/issues/1201) 
I tried several different ways to have it install correctly in Appveyor which has 2010 - 2019 versions of Visual Studio installed.
All the installs fail with the error _**"Visual Studio is not installed or the specified version is not present."**_
The PR can not be approved if the package won't complete successfully in Appveyor.
Note:
It appears that the detection used for the `Install-ChocolateyVsixPackage` doesn't detect certain versions of Visual Studio. The use of the `Get-UninstallRegistryKey` helper detects the latest version installed, but for some reason the `Install-ChocolateyVsixPackage` helper was not finding Visual Studio installed at all.

**Comment by AdmiringWorm** [comment]
closing as the wixtoolset do not have the responsibility of installing the extensions for the specific visual studio versions.
Please use https://github.com/chocolatey-community/chocolatey-package-requests for requesting new packages.
