### ISSUE TITLE
(paint.net) Unattended installation fails when running as SYSTEM

### ISSUE THREAD

**Issue by MartijnOnGithub** [chocolatey-community/chocolatey-coreteampackages#1542]
Chocolatey Package - Paint.net
If running a hidden (as SYSTEM) installation (/update/removal) this fails.
Especially in a situation where it is not possible for the installer to show a GUI (lets call is headless)
Check also issue #1421 

## Possible Solution
Check my comment at #1421: adding a MSI mode to the package may be a solution

## Steps to Reproduce (for bugs)
Check my comment at #1421: create a headless installation in the Windows task scheduler (running under account SYSTEM) and start it manually)
Check after some time the appl. event log for errors: 'SetupFrontEnd.exe' crashed.

- Create a hidden task in Win task scheduler
- Be sure SYSTEM is the account in the Security section
- Command: C:\ProgramData\chocolatey\choco.exe
- Args: install paint.net -y
- RunLevel = HighestAvailable
- Hidden = true
- Save it
- Run it manually in the scheduler

## Context
Try to automate installation, using agents that run the hidden installation (or upgrade/removal) as system

## Your Environment
* Package Version used: 'paint.net 4.2.13'
* Operating System and version: Windows 10 Pro
* Chocolatey version: Chocolatey v0.10.13

**Comment by majkinetor** [comment]
See my response here:
https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1421#issuecomment-698161932

**Comment by jmeile** [comment]
I think this should be written on the info page from the package. Some users like me, waste lot of time trying to figure out why the update from Paint.Net isn't working.

Finally, I think all other packages requiring a GUI for its installation, removal, and update should be noted on the package's page. This will save other people a lot of time.

**Comment by pauby** [comment]
If you want to raise an issue about this (this one is closed), and a PR to fix it, then that would be welcomed.
