### ISSUE TITLE
(lightworks) Update the Software Author

### ISSUE THREAD

**Issue by LWKS-PM** [chocolatey-community/chocolatey-coreteampackages#1544]
The author shown here: https://chocolatey.org/packages/lightworks shows the previous owner as: EditShare 
Since September 15th 2020 Lightworks is now owned by: LWKS Software LTD If this could be updated to reflect that change, it would be great. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by gep13** [comment]
@LWKS-PM looks like this has been addressed via a PR from @RedBaron2 When a new release of LightWorks is made, the package will have the updated information regarding the owners.

Is there a new release of the software planned?

**Comment by LWKS-PM** [comment]
Hi, the latest release 2020.1.1 has just been made available. The next release is scheduled for 25th November 2020
