### ISSUE TITLE
(ffmpeg) separate to x86 and x64 flavors

### ISSUE THREAD

**Issue by ohadschn** [chocolatey-community/chocolatey-coreteampackages#1551]
## Expected Behavior
Current package continues to work the same, but interested users can opt for an architecture-specific package and save download time and disk space.

## Current Behavior
Currently the `nupkg` contains both x86 and x64 ffmpeg flavors, approximately doubling its size. 

## Possible Solution
Separate these to two different packages (one for x86 and one for x64). Of course the current package could be retained, simply adding a dependency on both flavors (so that it continues to function as it does now, auto-installing the correct flavor).

## Context
Some users have slow internet connections, downloading both flavors is needlessly time consuming (and also technically space consuming when running very low on space).

**Comment by majkinetor** [comment]
Sorry, we don't do that., its too much hassle for trivial benefit.
