### ISSUE TITLE
(ffmpeg) Release site has shutdown, needs new release source

### ISSUE THREAD

**Issue by jtcmedia** [chocolatey-community/chocolatey-coreteampackages#1552]
## Current Behavior
ffmpeg.zeranoe.com, the source for new releases for this package, has shutdown as mentioned [here](https://www.reddit.com/r/ffmpeg/comments/ikht2k/ffmpegzeranoecom_will_close_on_sep_18_2020/)

## Possible Solution
Get static builds from either [www.gyan.dev](https://www.gyan.dev/ffmpeg/builds/) or [https://github.com/BtbN/FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds)

**Comment by naveen521kk** [comment]
Looks like there will be no support for 32 bit. Both the build are for 64 bit,
