### ISSUE TITLE
(youtube-dl) Outdated - Github repo suspended

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-coreteampackages#1561]
Since the Github repo is suspended for an indeterminate amount of time, the script should use the official website (https://youtube-dl.org/) to download new versions.

**Comment by majkinetor** [comment]
There are no new versions AFAIK. We should IMO wait until situation resolves. The tool is embedded and last version will work anyway.

**Comment by opusforlife2** [comment]
The version in the repo is 2020.09.14. The latest version is 2020.11.12.

**Comment by majkinetor** [comment]
Interesting. Thx.

**Comment by opusforlife2** [comment]
So will you be reviewing the linked PR?

**Comment by majkinetor** [comment]
I merged it, but it failed verification which needs to be fixed /cc @jaynemo 

https://chocolatey.org/packages/youtube-dl/2020.11.12

**Comment by opusforlife2** [comment]
@majkinetor @jaynemo What's the plan now? youtube-dl repo is restored. Do you want to revert the PR or is it better to depend on the official website in case something like this happens again?

**Comment by opusforlife2** [comment]
Ah. The 17 Nov update successfully arrived.

**Comment by opusforlife2** [comment]
All versions after 19 November failed automated validation.
