### ISSUE TITLE
(julia) v1.5.3 is awaiting moderation

### ISSUE THREAD

**Issue by DhruvaSambrani** [chocolatey-community/chocolatey-coreteampackages#1568]
## Possible Fix

Please moderate as necessary

Ps: Not entirely sure if I should open an issue here or not😅

**Comment by majkinetor** [comment]
https://chocolatey.org/packages/Julia/1.5.3

https://gist.github.com/choco-bot/19ccc839ee91cfe0ef2b254916da6e08


Looks like it should just get repeated
