### ISSUE TITLE
(git) Initial install should require reboot

### ISSUE THREAD

**Issue by BlythMeister** [chocolatey-community/chocolatey-coreteampackages#1569]
## Expected Behavior
On fresh machine, when installing Git the package should return exit code 1641 or 3010 stating a reboot was started or is required.

## Current Behavior
Exit code 0

## Possible Solution
Detect if installed already and adjust exit code accordingly

## Steps to Reproduce (for bugs)
1. Install git on fresh machine
2. check exit code

## Context
This means that (without a reboot) git is not available on the PATH to any application already running

## Your Environment
* Package Version used: 2.29.2
* Operating System and version: Windows Server 2019
* Chocolatey version: 0.10.5

**Comment by majkinetor** [comment]
I would definitely NEVER reboot to have git - that is insane. 

You should restart shell or use `refreshenv`.

**Comment by BlythMeister** [comment]
on my build agent, it's not the shell, it's services that need restarting to get an updated PATH.

**Comment by majkinetor** [comment]
That is highly specific to your case so you should fix it yoursef. WIndows API has WM_SETTINGCHANGE broadcast with parameter Environment you can try to use. 

In any case you can restart-computer after cinst git yourself.

**Comment by BlythMeister** [comment]
I'm not saying the package should restart.

But it should return the exit code to advise a reboot.

That way, you can have custom logic to react to that status and trigger the reboot if you so wish.

**Comment by BlythMeister** [comment]
It's a case of only wanting to restart when chocolatey has actually run the upgrade.

If it's the same version, I won't want to restart.

**Comment by majkinetor** [comment]
Not sure how to do that reliably. Your best bet is probably to `gcm git` and if it errors restart computer.

**Comment by BlythMeister** [comment]
if this package returned the right exit code...then you could react to that.

https://chocolatey.org/docs/commandsinstall#exit-codes

> 3010: success, reboot required

**Comment by majkinetor** [comment]
Via what logic ?

**Comment by BlythMeister** [comment]
Add `Set-PowerShellExitCode 3010` at the end of the script

**Comment by majkinetor** [comment]
When ?

**Comment by BlythMeister** [comment]
2 choices.

Everytime it runs (maybe a bit ott) or pre-install check path for git.exe and if not present, then return the exit code.
