### ISSUE TITLE
(chocolatey-python.extension) Install Python Packages

### ISSUE THREAD

**Issue by naveen521kk** [chocolatey-community/chocolatey-coreteampackages#1579]
## Expected Behavior
This is a new package where they will to function `Install-PipPackage` and `Uninstall-PipPackage`, where people can create a chocolatey package easily for the existing project in `pip`. 
Here is my idea of what is should do,
- Check whether the specified Python version is installed. (Allow Range inputs.). Finally, lock over the executable to run command.
- Check whether Pip is installed. If not install it. Also, run the command, `python -m pip install --upgrade pip wheel`. To upgrade
- Install the package using pip, where it uses `--prefix` parameter and install it to tools directory. For example,
  ```pwsh
  python -m pip install "numpy==$version" --compile --prefix="$InstallLocation\Numpy" --no-warn-script-location --log="pip.log"
  ```
  Passing the parameter `--compile` is optional but would speed loading. The ` --prefix` would install things in that directory so we can have control over it. It is logged to `pip.log`.
- Finally, finding the `site-packages` directory using `python -m site --user-site`, and then creating a `<package>.pth` file with `prefix` location as the content. In the user `site-packages` directory so that the users can use that package. 
- Create a `.json` file or anything, which contains the `python` used and the `site-package` in it so that it can be read while uninstalling.
- Creating symlinks the things in `$InstallLocation\<package>\Scripts` to add it in the path.
- Uninstalling should not call pip instead it would delete `$InstallLocation\<package>` and delete the `.pth` file created in the `site-package` folder.

## Context
- The reason I am asking this is this will provide users to select install location.
- Setting up proxy as configured in chocolatey.
- More access over installed files.
- Prevents installation failure if pip not installed #1565 . 
- Access the logs from pip easily.

**Comment by majkinetor** [comment]
I like it, its quite comprehensive and well though out. Feel free to PR.

> The reason I am asking this is this will provide users to select install location.

Not sure what is the best default location. Perhaps `Get-ToolsLocation\PipPackages`.

> Setting up proxy as configured in chocolatey.

I would add the $proxy variable. Check out this code from mkdocs: https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/mkdocs/tools/ChocolateyInstall.ps1

**Comment by naveen521kk** [comment]
@majkinetor Maybe you can add "Up for Grabs" label. I'm not working on this.
