### ISSUE TITLE
(graphviz) 2.44.1 looks broken

### ISSUE THREAD

**Issue by CAMOBAP** [chocolatey-community/chocolatey-coreteampackages#1580]
`choco install graphviz` produce

```
C:\Windows\system32>choco install graphviz
Chocolatey v0.10.15
Installing the following packages:
graphviz
By installing you accept licenses for the packages.
Progress: Downloading Graphviz 2.44.1... 100%

Graphviz v2.44.1 [Approved]
graphviz package files install completed. Performing other installation steps.
The package Graphviz wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): Y

Attempt to use original download file name failed for 'C:\ProgramData\chocolatey\lib\Graphviz\tools\graphviz-install-2.44.1-win64.exe'.
Copying graphviz
  from 'C:\ProgramData\chocolatey\lib\Graphviz\tools\graphviz-install-2.44.1-win64.exe'
Installing graphviz...
graphviz has been installed.
WARNING: Can't find graphviz install location
 The install of graphviz was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

[chocolatey.log](https://github.com/chocolatey-community/chocolatey-coreteampackages/files/5588669/chocolatey.log)

Version `v2.38.0.20190211` works without any issues

## Expected Behavior
`dot` tool should be available after `graphviz` install

## Current Behavior
Formally the installation finished successfully but in fact, the `dot` tool has not ben installed

## Possible Solution
IDK, but if I run `%USERPROFILE%\AppData\Local\Temp\chocolatey\Graphviz\2.44.1\graphvizInstall.exe` without `/S` it works

## Steps to Reproduce (for bugs)
1. `choco install graphviz --version 2.44.1`
2.  check output
3. also you may check`dot -?`, it not found
4.

## Your Environment

* Package Version used: 2.44.1
* Operating System and version: Windows 10
* Chocolatey version: 0.10.15
* Install/uninstall gist:

**Comment by majkinetor** [comment]
The installer didn't find installation path so it couldn't add shim to the PATH.

Dot is probably there. 

Definitely a bug due to recent release.

**Comment by CAMOBAP** [comment]
> Dot is probably there.

@majkinetor  I can confirm that there is no dot.exe in chocolatey's bin directory

**Comment by majkinetor** [comment]
Not in bin directory, its there on the system.

**Comment by CAMOBAP** [comment]
@majkinetor you are right, it's in "Programm Files".

But for "v2.38.0.20190211" dot was in chocolatey's bin. If this new behavior is expected, feel free to close this ticket

**Comment by majkinetor** [comment]
No, its a bug. I will fix it ASAP.

**Comment by majkinetor** [comment]
Try it now please. It should be fixed:

https://chocolatey.org/packages/Graphviz/2.44.1.20201124

`cinst graphviz --version 2.44.1.20201124`

**Comment by CAMOBAP** [comment]
@majkinetor thank you a lot

**Comment by majkinetor** [comment]
No problem mate. Keep up the good work with your projects (always happy to see more doc generators).
