### ISSUE TITLE
(php) Revert dependency change for PHP

### ISSUE THREAD

**Issue by shivammathur** [chocolatey-community/chocolatey-coreteampackages#1587]
PHP 8.0 does not require `visualstudio2019buildtools` for installing it and should work fine with `vcredist140`.
`vcredist140` supports Visual studio 2015 to 2019, i.e. it covers `vs16`.

`visualstudio2019buildtools` is required for building PHP from source, not for installing PHP.

## Expected Behavior
Installing PHP 8.0.0 should install `vcredist140` just like it did with previous versions of PHP.

## Current Behavior
After #1585, Installing PHP 8.0.0 installs `visualstudio2019buildtools` as a dependency.

## Possible Solution
in `automatic/php/update.ps1`
```diff
- 'vs16' = @{ Id = 'visualstudio2019buildtools'; Version = '16.8.2.0' }
+ 'vs16' = @{ Id = 'vcredist140'; Version = '14.28.29325.2' }
```

## Steps to Reproduce (for bugs)
1. Installing `PHP 8.0.0` installs `visualstudio2019buildtools`, which is not required.

## Your Environment

* Package Version used: `PHP (Hypertext Preprocessor) 8.0.0`
* Operating System and version: `Windows 10`
* Chocolatey version: `0.10.16-beta`
* Install/uninstall gist: `choco install php`

**Comment by maxim-lobanov** [comment]
cc @pavinthan, @majkinetor as PR owners.
