### ISSUE TITLE
(protoc) rc version blocks new stable version automatic upgrade

### ISSUE THREAD

**Issue by drelatgithub** [chocolatey-community/chocolatey-coreteampackages#1588]
This is an issue I'm facing but I might need help to fix it. The google protocol buffer (protoc) package was set to automatically upgrade itself, but I've just realized that it has not done so for months, while there are actually new stable versions coming out. Disclaimer: I helped with the automation of the protoc package upgrade (https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1345), but I was not the maintainer of the package, so I was unaware of what happened later.

## Expected Behavior
The stable versions get updated normally.

## Current Behavior
Current stable version is stuck in `3.12.3`.
Previously in July, a new version named `4.0.0-rc-2` was published. And since then, new stable versions do not trigger an update, as displayed below.
```
protoc - checking updates using au version 2020.12.1.180737

URL check
  https://github.com//protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-win32.zip
  https://github.com//protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-win64.zip
nuspec version: 4.0.0-rc-2
remote version: 3.14.0
No new version found
```

## Possible Solution

Since it's been a while, I'm a little confused on how choco deals with rc/alpha/beta vs stable versions as well as how auto-update codes should check for updates properly. Currently, I think, in chocolatey, the `4.0.0-rc-2` version should only be installed if `--pre` option is specified, and the normal installation should just go with the newest stable version `3.14.0`, but is the AU also treating rc/alpha/beta and stable versions separately? How should I judge whether I can overwrite the current version `4.0.0-rc-2` with `3.x.y` since the previous stable version information is no longer there? Any help will be much appreciated!

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by RedBaron2** [comment]
@drelatgithub 
The quick fix is to change the nuspec version to `0.0.0`, but this won't prevent it from happening in the future.
The `protoc` package has no logic to help it determine a `--pre` or `stable` release. Best suggestion is to re-work the package into a stream. This will keep the package versions for `--pre` and `stable` separate. Example: `chromium` package.
