### ISSUE TITLE
(musescore) Wrong installer is downloaded

### ISSUE THREAD

**Issue by sarunint** [chocolatey-community/chocolatey-coreteampackages#1590]
## Expected Behavior
The current installer on MuseScore website is named `MuseScore-3.5.2.311459983-x86_64.msi`.

## Current Behavior
In `chocolateyInstall.ps1`, the installer is named `MuseScore-3.5.2.310568139-x86_64.msi`, which is an unstable version. So if I run `choco install musescore`, the unstable version is installed.

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/f38407183ea88101eaf9e97c963608ad2cc8202b/automatic/musescore/tools/chocolateyInstall.ps1#L5-L12

## Possible Solution
Changing the installer name? I think.

## Steps to Reproduce (for bugs)
1. `choco install musescore`\

## Context
Currently, `choco install musescore` installs the unstable version.

## Your Environment

* Package Version used: `3.5.2`
* Operating System and version: Windows 10 20H2
* Chocolatey version: 0.10.15
* Install/uninstall gist:

**Comment by RedBaron2** [comment]
@sarunint 
The current `update.ps1` file for the `musescore` package only uses a version with major.minor.build it needs to be changed to use a major.minor.build.release version according to your report of the current release.
If you want you can submit a PR for this change.
Thanks for the observation.

**Comment by majkinetor** [comment]
a901945e69e3b0aef58d1cfb6d05fd851eada2ff
