### ISSUE TITLE
(openshift-cli) stuck at v3

### ISSUE THREAD

**Issue by chillum** [chocolatey-community/chocolatey-coreteampackages#1601]
This repo contains `openshift-cli` package, that's stuck two years ago at latest v3 version.  
OpenShift is v4 nowdays, so it would be great to have an up-to-date OpenShift CLI in Choco.

## Expected Behavior

`choco install openshift-cli` installs recent v4.6

## Current Behavior

`choco install openshift-cli` installs outdated v3.11

## Possible Solution

openshift-cli releases for v4 moved out of GitHub, they're now at https://mirror.openshift.com/pub/openshift-v4/clients/oc/

I created a v4 package manually, but it may be possible to make it automated as well. manual package looks like:
```powershell
$packageArgs = @{
    PackageName   = 'openshift-cli'
    Url           = 'https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.6.0-202005061824.git.1.7376912.el7/windows/oc.zip'
    Checksum      = '705D7615D097EF5A4C44219C143156BF2D6BFE43B6298E637273552153E5516D'
    ChecksumType  = 'sha256'
    UnzipLocation = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
}

Install-ChocolateyZipPackage @packageArgs
```

**Comment by RedBaron2** [comment]
@chillum 
It appears that the `update.ps1` file used for this package needs to be updated to point to the new repository of `https://github.com/openshift/okd/releases`

If you would like to submit a PR with the required changes in place. I'm sure the moderators here will take it under advisement.

Thanks again for bringing this issue to light.

**Comment by AdmiringWorm** [comment]
I have marked this issue as `Up for grabs`.

@chillum let us know if you are interested in providing a pull request to get this package updated, and we can get this issue assigned to you.
