### ISSUE TITLE
(googlechrome) Include master_preferences file

### ISSUE THREAD

**Issue by TaffarelJr** [chocolatey-community/chocolatey-coreteampackages#1603]
When installing the Google Chrome Enterprise MSI, a file called `master_preferences` can be placed alongside `chrome.exe` in the install destination folder (`%ProgramFiles%\Google\Chrome\Application\`) to configure Chrome and control how it first launches.

It would be great if there was a flag on the Chocolatey package to specify a path to a `master_preferences` file to be included in the installation. Ideally we'd include both local drive & URI support.

Notes:
- Google will be changing the name of this file to `initial_preferences.json` in Chrome 88, so it would probably be best to just take whatever file is specified and leave the name alone.
- Some documentation on the `master_preferences` file here:
  - https://support.google.com/chrome/a/answer/187948
  - https://www.chromium.org/administrators/configuring-other-preferences

## Expected Behavior
Examples:
```
choco install googlechrome --package-parameters="/PreferenceFile='C:\InstallFiles\master_preferences'"
choco install googlechrome --package-parameters="/PreferenceFile='C:\InstallFiles\initial_preferences.json'"
choco install googlechrome --package-parameters="/PreferenceFile='http://mydomain.com/InstallFiles/master_preferences'"
```
Each of these variants would install the Chrome enterprise MSI like normal, but then copy the specified file to the Chome install directory (`%ProgramFiles%\Google\Chrome\Application\`) as its final step.

The name of the file would not be changed from the specified name, but _would_ overwrite any previously-existing file. (Chrome includes a very simple `master_preferences` file by default.)

Chocolatey would throw an exception if the specified file was not found, could not be downloaded, or otherwise could not be copied to the install directory.

## Current Behavior
1. Use Chocolatey to install Chome
2. Copy/download `master_preferences` file from wherever I have it stored
3. Handle any exceptions manually

## Context
Mostly cosmetic; I'd love to be able to shrink all my Chocolatey installs to 1-liners, instead of requiring multiple lines & error handling to fully install and configure one app.

**Comment by TheCakeIsNaOH** [comment]
> Mostly cosmetic; I'd love to be able to shrink all my Chocolatey installs to 1-liners, instead of requiring multiple lines & error handling to fully install and configure one app.

https://github.com/chocolatey/choco/issues/1185 is probably what you want.

**Comment by AdmiringWorm** [comment]
I agree with @TheCakeIsNaOH that it would be better served through a hook (which is what the linked issue is about).
But due to the lack of it, it is definitely something that *could* be implemented in the package itself.
Not sure if allowing downloading a file would be appropriate though, but a local file is something that could be added.

**Comment by majkinetor** [comment]
Whats wrong with `cp` ?
