### ISSUE TITLE
(sourcetree) License url is pointing to a missing webpage

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-coreteampackages#1605]
Seems that the license page of the [source tree](https://chocolatey.org/packages/SourceTree/3.4.1) package have been moved, and need to be updated before any more versions of the package can be published.

/CC @pascalberger

**Comment by pascalberger** [comment]
This is another classic move of Atlassian... I searched for license but wasn't able to find any. On the website there's a [Terms Of Use](https://sourcetreeapp.com/) link at the bottom, but which obviously doesn't apply to SourceTree, since it goes to `Atlassian Cloud Terms of Service` and SourceTree is also not listed on the product specific terms. They probably just forgot that they also have SourceTree. I'm tempted to just get rid of this package, because I'm really tired how Atlassian handles this and it's not worth the effort.

**Comment by pascalberger** [comment]
I tried to reach out by Twitter to them: https://twitter.com/hereispascal/status/1349088367867277312

**Comment by AdmiringWorm** [comment]
Found this in their terms of use

> 1.4. Software Products Not Covered. These Terms do not apply to our downloadable software products (currently designated as “Server” and “Data Center” deployments), use of which requires a separate license agreement with us. For clarity, however, any client software (e.g., a desktop or mobile application) we provide as part of the Cloud Products themselves remains subject to these Terms.

With this, I could assume that the sourcetree software is covered by the same license/terms of use that the `Atlassian Cloud Terms of Service` details.

Would be great to have someone from the chocolatey team confirm wether this would be acceptable on the community repository, in the lack of a specific License covering SourceTree.

Reference to the terms of use: https://www.atlassian.com/legal/cloud-terms-of-service

/cc @pauby @gep13 @ferventcoder

**Comment by pauby** [comment]
Unless it specifically allows redistribution, the software can't be embedded. Moderators need to err on the side of caution when things like this crop up.

**Comment by AdmiringWorm** [comment]
@pauby yes of course. I did not mean for embedding, but if those Terms of service/Terms of use would be appropriate to link to as the metadata license URL?
The installation process would still be kept the same, with downloading the installer during installation.
As of right now, the only reason the package is failing (AFAIK) is because they removed the previous license location without having a dedicated license page for the software anymore.

**Comment by pauby** [comment]
Ahhhhh. Apologies. I misunderstood.

If it were me, as it's the only license there is, I would use it and, for belt and braces, add a note in the description.

**Comment by pascalberger** [comment]
Got an answer: https://twitter.com/AskAtlassian/status/1349457093078650880

Proper license is: https://www.atlassian.com/legal/software-license-agreement
