### ISSUE TITLE
(everything) Does not install silently

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-coreteampackages#1611]
## Expected Behavior
Everything package should install silently.

## Current Behavior
When upgrading to the last couple of everything versions, this window pops up:

![image](https://user-images.githubusercontent.com/12760779/106452928-76673980-6480-11eb-9916-5e7be331f825.png)

## Steps to Reproduce (for bugs)
1. `choco upgrade everything`

## Your Environment

* Package Version used: 1.4.11005
* Operating System and version: Windows 10
* Chocolatey version: 0.10.15
* Install/uninstall gist: N/A

**Comment by AdmiringWorm** [comment]
I just tested the package right now, and from what it seems it works and installs as it should.
My theory is that there may be some remembered arguments that conflict with the arguments that are supposed to be used with the package.

@pauby can you confirm that you are still experiencing this issue?

**Comment by pauby** [comment]
@AdmiringWorm I forced installed it now, same version as above, and it appears to be working. I'd be curious if it will still do that at the next version upgrade. If it does, I'll come back and reopen this but happy to close it now.

> My theory is that there may be some remembered arguments that conflict with the arguments that are supposed to be used with the package.

I've never used any parameters with this package.

**Comment by AdmiringWorm** [comment]
> I've never used any parameters with this package.

You could have hit https://github.com/chocolatey/choco/issues/2111 (but that is just speculations)
