### ISSUE TITLE
(adobe flash) downloads removed by adobe, should be unlisted

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-coreteampackages#1612]
Download URLs for Flash products have been removed from Adobe's website, and additionally, recent versions time bombed last month and are now non-functional.

Reference: https://www.adobe.com/products/flashplayer/end-of-life.html (see question 8)

Core Team packages that this applies to:
- [`flashplayerppapi`](https://chocolatey.org/packages/flashplayerppapi)
- [`flashplayeractivex`](https://chocolatey.org/packages/flashplayeractivex)
- [`flashplayerplugin`](https://chocolatey.org/packages/flashplayerplugin)

----

I think unlisting all current versions of these packages is the way to go.

**Comment by gep13** [comment]
@TheCakeIsNaOH out of interest, what was the outcome here?  Why has the issue been closed?

**Comment by TheCakeIsNaOH** [comment]
When I tried the links on all of these in my browser, they did not download anything. However, that was just an issue with my browser, and they actually still download fine with Chocolatey.

**Comment by gep13** [comment]
@TheCakeIsNaOH ah, gotcha. Thanks for confirming!
