### ISSUE TITLE
(poweriso) outdated url and checksum in chocolateyInstall.ps1

### ISSUE THREAD

**Issue by mareccs** [chocolatey-community/chocolatey-coreteampackages#1614]
Hi!

when i install poweriso package, i get a checksum error. This is because the url and the checksum in chocolateyInstall.ps1 file is outdated. Is it possible to correct is? Thanks for your work!

The actual url and checksum is:
url = 'http://www.poweriso.com/PowerISO7.exe'
url64bit = 'http://www.poweriso.com/PowerISO7-x64.exe'
checksum = 'C3343AE00CD02451840C5D86AC0F96D3E397E5598A07FB85F1696FAD4D04EB73'
checksum64 = '3E5E2E52BC558E25BA00DD36856DD296D76B1ACE82A5DBDD09957CE3C39AAF76'

**Comment by AdmiringWorm** [comment]
A new version have been triggered to be updated, and should be pushed to chocolatey.org in a few minutes.

It will take a few hours until it can be used for normal consumption...
