### ISSUE TITLE
PowerISO Checksum Error

### ISSUE THREAD

**Issue by python4lyfe** [chocolatey-community/chocolatey-coreteampackages#1621]
## Expected Behavior
Installation of PowerISO via Chocolatey

## Current Behavior
When attempting to download and install PowerISO, I receive a checksum error and a failure message.

## Steps to Reproduce (for bugs)
1. Run the command: choco install poweriso

## Context
How about the error logs?

[choco_error.txt](https://github.com/chocolatey-community/chocolatey-coreteampackages/files/6062545/choco_error.txt)

## Your Environment

* Package Version used: 7.8.0
* Operating System and version: Windows 10 Professional x64 - 20H2
* Chocolatey version: 0.10.15
* Install/uninstall gist: see steps to reproduce

**Comment by AdmiringWorm** [comment]
I have forced a new update of the package. We'll see if it goes through the verifier at this time, otherwise I would probably need to make some changes and request for an exemption.
