### ISSUE TITLE
(mkdocs) Find the Python Executable Correctly

### ISSUE THREAD

**Issue by naveen521kk** [chocolatey-community/chocolatey-coreteampackages#1623]
## Expected Behavior
Currently, the package just chooses the first `python.exe` which it seems. The `python.exe` could be from a venv(virtual environment) and could be problematic. It should query registry as specified in https://www.python.org/dev/peps/pep-0514 and then find the `python.exe` which is originally installed from an Installer and use the `python.exe` from there.

## Current Behavior
Doesn't query the registry for finding the correct Python Executable.

## Possible Solution
Some function like the below one should be used to find python executable and pip must be used there.
```ps
function FindPython {
  param(
    $allowed_python_versions
  )
  # see https://www.python.org/dev/peps/pep-0514/#structure
  # we are querying machine regsitry only because chocolatey
  # installs python in admin mode only.
  $avaiable_installation = Get-ChildItem -Path Registry::HKEY_LOCAL_MACHINE\Software\Python\PythonCore | Select-Object Name
  foreach ($install in $avaiable_installation) {
    $name_install = $install.Name
    $install_version = ($name_install -split '\\')[-1]
    if ($allowed_python_versions.Contains($install_version)) {
      Write-Host "Found Python Version from Registry $install_version" -ForegroundColor Yellow
      $python_executable = Get-ItemProperty -Path "Registry::$name_install\InstallPath" | Select-Object ExecutablePath
      Write-Host "Found Install Path from Registry $($python_executable.ExecutablePath)" -ForegroundColor Yellow
      return $python_executable.ExecutablePath
    }
  }
}
```

## Steps to Reproduce (for bugs)
1. Create a virtual environment `python -m venv _test` (python3 only).
2. Activate it `_test\Scripts\activate`
3. Run the install now. `choco install mkdocs`

**Comment by pauby** [comment]
@naveen521kk As you've already provided the code for this, do you want to submit a PR?

**Comment by naveen521kk** [comment]
I don't know whether the code the will or not, that's why I didn't submit a PR.

**Comment by pauby** [comment]
You provided the code above in your original message.

**Comment by naveen521kk** [comment]
didn't notice that. ok, I will make one soon.

**Comment by naveen521kk** [comment]
I don't think I would be able to work on this in the coming weeks, so I will close this.
