### ISSUE TITLE
After installing python3 with choco only typing  `python` will get you into the python3 prompt

### ISSUE THREAD

**Issue by cmdline-batchelor** [chocolatey-community/chocolatey-coreteampackages#1630]
## Expected Behavior
After installing chocolatey:
typing `python3`In cmd should get you into a python3 prompt.

## Current Behavior
- Typing `python` gets you into a python 3 prompt
- This isn’t good as what if the user has 2 versions of python?

## Possible Solution
- This could have something to do with all new win10 installations coming with `*\windowsApps\python3.exe` with 0 bytes (tested on fresh win10 vm and win10 machine)
- Configure python3 to be opened with `python3` rather than `python`
- I am having a hard time finding the `python3.exe` Or any python3*.exe or would just run that directly

## Steps to Reproduce (for bugs)
1. `choco install -y python3`
2. After install and reboot type `python3`:
       Windows store popup will appear, asking you to install python3

3. Type `python`:  you’ll end up in a python3 prompt

## Context
typing `python3` shoud get you in to a python3 prompt what if I had 2 different versions? As you can see from the curren behaviour this would cause a conflict or override and so I wouldn’t be able to use both versions side by side.

## Your Environment  
* Package Version used: python3
* Operating System and version: win10, also fresh vbox win10 vm
* Chocolatey version: latest (installed 3-4 days ago)

**Comment by naveen521kk** [comment]
This is something you want to report to Python itself and not here.

They provide an alternate way `py.exe` to run between python2 and python3, for example
`py -2` will open a python2 prompt and `py -3` will open a python3 prompt.

Have a look at https://www.python.org/dev/peps/pep-0397/

**Comment by cmdline-batchelor** [comment]
@naveen521kk ah ok so this is a windows issue only as in the past running this on centos `python3` would do what I wanted it to
