### ISSUE TITLE
(Firefox) Doesn't correctly logs System locale

### ISSUE THREAD

**Issue by CookieHCl** [chocolatey-community/chocolatey-coreteampackages#1631]
## Expected Behavior

My system locale is `ko-KR`, log should say the same.

## Current Behavior

Log says:  
2021-03-24 13:40:22,541 27184 [INFO ] - VERBOSE: System locale is: 'en-US'...

## Possible Solution

In the [code](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/firefox/tools/helpers.ps1), firefox package is using [Get-UICulture](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-uiculture?view=powershell-7.1), but probably chocolatey is `en-US`, so maybe Get-UICulture inside chocolatey returns `en-US`?  
Maybe you should use [Get-Culture](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-culture?view=powershell-7.1) or [Get-WinSystemLocale](https://docs.microsoft.com/en-us/powershell/module/international/get-winsystemlocale?view=windowsserver2019-ps).  
Unfortunately, I don't know how to test inside chocolatey, and my powershell returns `ko-KR` for those 3 functions, so I don't know which one is actually correct.

## Steps to Reproduce (for bugs)

Install firefox, see the logs

## Context

Package should get the correct locale.

## Your Environment

* Package Version used: 87.0
* Operating System and version: Microsoft Windows NT 10.0.19042.0
* Chocolatey version: 0.10.15
* Install/uninstall gist: Sorry I can't understand this

**Comment by AdmiringWorm** [comment]
> In the code, firefox package is using Get-UICulture, but probably chocolatey is en-US, so maybe Get-UICulture inside chocolatey returns en-US?

That isn't how those functions work, unfortunately, they call directly into the operating system to acquire the locale from there, not to the local process (there are different calls that make that happen, but that isn't PowerShell explicit code).

> Maybe you should use Get-Culture or Get-WinSystemLocale.
> Unfortunately, I don't know how to test inside chocolatey, and my powershell returns ko-KR for those 3 functions, so I don't know which one is actually correct.

Unfortunately, using `Get-Culture` would be incorrect in this case. That function is more related to how to format dates, numbers, etc. While `Get-UICulture` is for which locale text should be in.
`Get-WinSystemLocale` also can not be used, as it was first introduced in Windows 10, and packages need to keep backwards compatibility with older versions of windows.

> Log says:
> 2021-03-24 13:40:22,541 27184 [INFO ] - VERBOSE: System locale is: 'en-US'...

That is a display bug, and not the actual locale that was found (the script uses the wrong variable and prints out the fallback locale instead).

> Install/uninstall gist: Sorry I can't understand this

A gist is a file that has been uploaded to: https://gist.github.com/ (sometimes included in a comment, but uploading it to the URL is preferred).
When saying Install/uninstall gist it means the complete log as shown in `%ChocolateyInstall%\logs\chocolatey.log` should be uploaded to the previously mentioned location, and a link to that gist shared here.

Unfortunately, to get anywhere with this issue, this log would be necessary as there are additional information needed (the logs mainly).

**Comment by CookieHCl** [comment]
@AdmiringWorm 
Sorry, I didn't knew the log was showing the wrong variable.  
I've uninstalled and installed firefox again, and found out that package correctly gets system locale, but it doesn't log it correctly.  
(Didn't knew this because I was upgrading at the first time, so I just thought the package didn't get the system locale, but it just used the installed locale.)

Here is the [log file](https://gist.github.com/CookieHCl/77b0613cc610d061893488dc9323cd29) line 478-480.
> 2021-03-25 23:10:07,002 8748 [INFO ] - VERBOSE: Installed locale is: ''...
> 2021-03-25 23:10:07,005 8748 [INFO ] - VERBOSE: System locale is: 'en-US'...
> 2021-03-25 23:10:07,016 8748 [INFO ] - VERBOSE: Using locale 'ko'...

So the problem wasn't Get-UICulture, it was the log's problem.

**Comment by AdmiringWorm** [comment]
> Sorry, I didn't knew the log was showing the wrong variable.

It isn't something that would be expected that a user of the package knows, I didn't even know it myself before looking at the script (when you opened the issue).

> I've uninstalled and installed firefox again, and found out that package correctly gets system locale, but it doesn't log it correctly.

So it do work as expected, with the only problem being the package outputting the wrong system locale. That is good to hear.

The output bug is fixed in the repository now, and should be available for any new package that gets pushed to chocolatey.org
