### ISSUE TITLE
(python3) missing version 3.6.8.20200110?

### ISSUE THREAD

**Issue by CookieHCl** [chocolatey-community/chocolatey-coreteampackages#1636]
## Expected Behavior

[python](https://community.chocolatey.org/packages/python/#versionhistory) package has version 3.6.8.20200110,  
so [python3](https://community.chocolatey.org/packages/python3/#versionhistory) package should have it.

## Current Behavior

[python](https://community.chocolatey.org/packages/python/#versionhistory) package has version 3.6.8.20200110,  
but [python3](https://community.chocolatey.org/packages/python3/#versionhistory) package doesn't, thus preventing installing it.

## Steps to Reproduce (for bugs)
`choco install python --version=3.6.8.20200110`

## Context

Python 3.6.8.20200110 is in python package, but not in python3 package.

## Notes
Also, can I ask about what are these python versions with dates?  
According to [python 3.6 release schedule](https://www.python.org/dev/peps/pep-0494/), there was no python 3.6 released at 20200110.  
What does version 3.6.8.20200110 means?

**Comment by AdmiringWorm** [comment]
> Also, can I ask about what are these python versions with dates?

These are fix version (existing versions can't be updated, so fixes need to go into a package with the fix version notation).
Typically this means that there are changes to either the package or the software installer was updated without the version being bumped upstream.

> Python 3.6.8.20200110 is in python package, but not in python3 package.

I think there was an effort to try creating a fix version for both the meta package (`python`) and the installer package (`python3`). My assumption is that the latter failed somehow, wasn't resolved and the n forgotten about.
I'll see if I can push out a version for the `python3` package with the missing fix version.

**Comment by AdmiringWorm** [comment]
I have triggered a forced update with that version specifier, if all goes well that version should be available on chocolatey.org in an hour or two.

**Comment by AdmiringWorm** [comment]
The missing version is now approved and available on chocolatey.org
