### ISSUE TITLE
(graphviz) extraneously shims additional executables

### ISSUE THREAD

**Issue by Starz0r** [chocolatey-community/chocolatey-coreteampackages#1642]
The Graphviz install seems to shim its entire bin folder, which ironically, does not happen to be graphviz.exe, which would have been the only acceptable shimmed executable.

## Expected Behavior
It should either shim nothing, or shim just graphviz.exe, which currently, it doesn't,

## Current Behavior
Currently, it shims everything in it's internal bin folder, which includes acyclic.exe, bcomps.exe, ccomps.exe, circo.exe, dijkstra.exe, dot.exe, fdp.exe, gc.exe, gml2gv.exe, graphml2gv.exe, gv2gml.exe, gvcolor.exe, gvgen.exe, gvpack.exe, gvpr.exe, gxl2gv.exe, mm2gv.exe, neato.exe, nop.exe, osage.exe, patchwork.exe, sccmap.exe, sfdp.exe, tred.exe, twopi.exe, and unflatten.exe.

## Possible Solution
For now, you could just add an ignored stub for all of these executables. The better alternative solution would to intentionally shim graphviz.exe so that the entire bin folder isn't searched.

## Steps to Reproduce (for bugs)
1. choco install graphviz -y

## Context
I'd like to keep my PATH and Chocolatey bin folder free from clutter, and extraneous shims that probably won't even work outside their specified environment, and have no job being there in the first place.

## Your Environment
* Package Version used: Graphviz 2.47.1
* Operating System and version: Windows 10 - 1909
* Chocolatey version: 0.10.15
* Install/uninstall gist: N/A

**Comment by AdmiringWorm** [comment]
Adding all of the executables as shims was an intentional change (see https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1610).

There is an argument made of perhaps having a package parameter that allow disabling the shimming of extra files though.

**Comment by AdmiringWorm** [comment]
> It should either shim nothing, or shim just graphviz.exe, which currently, it doesn't,

Odd, a shim for the `graphviz.exe` executable should also be created.
May have to look into why that doesn't happen.

**Comment by Starz0r** [comment]
Just wanted to ensure this was intended behavior, since it is, my issue has no more reasons to continue being open. Thank you for investigating this.
