### ISSUE TITLE
Chromium update doesn't result in an updated version

### ISSUE THREAD

**Issue by allenatdecisiv** [chocolatey-community/chocolatey-coreteampackages#1645]
I have Chromium v90.0.4430.72 installed. I run choco upgrade all. I hit "A" when asked to run 'chocolateyInstall.ps1' for the chromium package. Choco reports that it updated chromium successfully.  For this specific run of choco upgrade all, it's:
You have chromium v90.0.4430.72 installed. Version 90.0.4430.93 is available based on your source(s).

I then launch Chromium from its shortcut, I go to About Chromium and it's reporting "Version 90.0.4430.72 (Official Build) (64-bit)" which is the version choco reported it upgraded from. I am expecting About Chromium to report "Version 90.0.4430.93 (Official Build) (64-bit)".

I check the Chromium application directory and find this:
```
>dir "C:\Program Files\Chromium\Application"
 Volume in drive C has no label.
 Volume Serial Number is E28E-6A41

 Directory of C:\Program Files\Chromium\Application

04/29/2021  02:59 PM    <DIR>          .
04/29/2021  02:59 PM    <DIR>          ..
04/22/2021  01:45 PM    <DIR>          90.0.4430.72
04/29/2021  02:59 PM    <DIR>          90.0.4430.93
04/15/2021  01:36 AM         2,212,864 chrome.exe
04/29/2021  02:59 PM               407 chrome.VisualElementsManifest.xml
04/15/2021  01:36 AM           946,688 chrome_proxy.exe
04/26/2021  08:04 PM         2,214,400 new_chrome.exe
04/26/2021  08:04 PM           948,736 new_chrome_proxy.exe
04/29/2021  02:59 PM    <DIR>          SetupMetrics
               5 File(s)      6,323,095 bytes
               5 Dir(s)  601,555,795,968 bytes free
```

## Expected Behavior
I expect choco to update Chromium based on choco telling me that it will update Chromium, or that it found an update to the installed chromium package.

## Current Behavior
Choco leaves the old version installed and active.

## Steps to Reproduce (for bugs)
1. choco install chromium
2. wait for new version
3. choco upgrade all
4. hit "A" for running of chromium's chocolateyInstall.ps1
5. launch Chromium from it's shortcut
6. check the version of Chromium  with About Chromium

## Context
I have to uninstall chromium completely and re-install the updated version. I can't use choco upgrade all for chromium updates

## Your Environment
```
>ver
Microsoft Windows [Version 10.0.19042.928]
```
```
>choco --version
0.10.15
```
```
You have chromium v90.0.4430.72 installed. Version 90.0.4430.93 is available based on your source(s).
Progress: Downloading chromium 90.0.4430.93... 100%

chromium v90.0.4430.93 [Approved]
chromium package files upgrade completed. Performing other installation steps.
The package chromium wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

Installing 64-bit chromium...
chromium has been installed.
  chromium may be able to be automatically uninstalled.
 The upgrade of chromium was successful.
  Software installed to 'C:\Program Files\Chromium\Application'
```

**Comment by RedBaron2** [comment]
@allenatdecisiv
This seems to be a problem with the chromium installer not closing the application when it is found to be running.

I recommend that you always make sure the application is closed before you run the update for this package. You can always open an issue with the `Chromium Project` developers.

**Comment by allenatdecisiv** [comment]
@RedBaron2, okie dokie. Sounds good, thank you! I'll check on Chromium running prior to letting choco update it from now on. I would hope (🤞 ) that their installer would groak warnings and/or errors to signal that something went wrong, but I guess they don't?

**Comment by AdmiringWorm** [comment]
@allenatdecisiv another thing to note, in some cases you may already have closed chromium but some other program makes use of chromium for its own web browsing interface.
(Take steam as an example of that, which also prevents a full chromium upgrade).

This is also something that will prevent the old folder to be deleted by the installer, but unfortunately, there isn't much we can do about that :cry:

You can read a bit more about the update issue which has also been reported in the past here: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1088
