### ISSUE TITLE
(virtualbox) missing target param in file tag

### ISSUE THREAD

**Issue by overag3** [chocolatey-community/chocolatey-coreteampackages#1651]
In virtualbox.nuspec file, I noticed that the target parameter was missing in the file tag

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/410e1bfceabec25645bb30c23c75ff06c336fc35/automatic/virtualbox/virtualbox.nuspec#L54

it is displayed in this way on Chocolatey website :
![files-virtualbox-pkg](https://user-images.githubusercontent.com/54666189/118057126-7f26b000-b38b-11eb-8551-ef3becc3e855.png)

is it possible to fix this issue?

Regards

**Comment by AdmiringWorm** [comment]
Good catch, and thank you for reporting that mistake.

This is now fixed in the source repository and the correct path will be used in the package on any new version of virtualbox that gets submitted (old ones won't be updated).

**Comment by overag3** [comment]
Thanks for fix !
