### ISSUE TITLE
Allow bigger packages

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1669]
Current 200MB limit was OK few years back when it was introduced, but I think it should be higher nowdays, between 300 and 400 MB for example. There are few packages that fit into that category (particularly when both arch are included).

Any chance for that now that problem with big packages is solved ?

/cc @gep13 @pauby @ferventcoder

**Comment by pauby** [comment]
@majkinetor This isn't a Core Team Packages issue. It has already been [raised](https://github.com/chocolatey/home/issues/48).

**Comment by majkinetor** [comment]
Yeah, I know. I didn't know where to put it so I figured one of you guys will point me out.

**Comment by gep13** [comment]
@majkinetor any issues related to the Chocolatey Community Repository, or the associated Package Moderation Services should be added to the chocolatey/home repository.
