### ISSUE TITLE
(notepadplusplus) New version (8.0.0) available

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-coreteampackages#1675]
Notepad++ had a new version released a few days ago: https://notepad-plus-plus.org/news/v8-dark-mode/

**Comment by majkinetor** [comment]
Version 8.1 is available but it is pending  automated review.

https://community.chocolatey.org/packages/notepadplusplus.install/8.1

**Comment by opusforlife2** [comment]
Got the update.
