### ISSUE TITLE
(winscp) Shim for Winscp.com triggers an "Suspicious Double File Extension Execution" when used

### ISSUE THREAD

**Issue by ba-tno** [chocolatey-community/chocolatey-coreteampackages#1693]
Below issue is a bit far fetched, but I thought I would post it anyway as this seems to easiest path to fix it.

It appears that the McAfee virus scanner deletes executables with a double file extension when they are executed as part of a script.   
I use [chocolatey cleaner](https://community.chocolatey.org/packages/choco-cleaner) to maintain the chocolatey install. Part of that cleaner script checks if shims still point to an executable by checking the output of `$ShimFile --shimgen-help`.

In the case of WinSCP two shims are created under `c:\ProgramData\chocolatey\bin\`:
- `winscp.exe` which points to `c:\Program Files (x86)\WinSCP\WinSCP.exe`
- `winscp.com.exe` which points to `c:\Program Files (x86)\WinSCP\WinSCP.com` (related #1412 and #1134)

The latter shim is seen as "suspicious" and is deleted by McAfee when it is executed from a script.

## Expected Behavior

Ideally the created shim would have the same name as the original it points to, i.e. `winscp.com` instead of `winscp.com.exe`.
I understand the `.exe` is added by the shim generator and this is not configurable.  
Additionally chocolatey tools (like the cleaner) expect `.exe` files as shims, so it's best to stick to that extension.
Perhaps the WinSCP install script can rename `winscp.com.exe` to `winscp-com.exe` in the folder `c:\ProgramData\chocolatey\bin\` during the installation?

## Current Behavior

When WinSCP is installed through chocolatey two shims are created under `c:\ProgramData\chocolatey\bin\`:
- `winscp.exe` which points to `c:\Program Files (x86)\WinSCP\WinSCP.exe`
- `winscp.com.exe` which points to `c:\Program Files (x86)\WinSCP\WinSCP.com` (related #1412 and #1134)

## Possible Solution

The "proper" method would be to configure a McAfee exception, but in my current working environment I cannot configure those.
The current workaround I use is to rename the `winscp.com.exe` file manually to `winscp-com.exe` after every `choco upgrade all`.

## Steps to Reproduce (for bugs)

1. Have McAfee Endpoint security running
2. Install [chocolatey cleaner](https://community.chocolatey.org/packages/choco-cleaner)
3. Install [WinSCP rom chocolatey](https://community.chocolatey.org/packages/winscp)
4. Run `C:\tools\BCURRAN3\choco-cleaner.ps1` manually
5. McAfee should flag this as suspicious behaviour

## Context

I manage a Windows server in a corporate environment where antivirus exclusions are not easily obtained. Ideally I would be able to keep using chocolatey, but for that I need to make sure this does not raise any (false positive) antivirus flags.

## Your Environment

* Package Version used: 5.19.2
* Operating System and version: Windows Server 2016 v1607 build 14393.4467
* Chocolatey version: 0.10.15
* Install/uninstall gist: ...?

**Comment by pauby** [comment]
The issue here is McAfee being over aggressive in removing files with two extensions (I suspect it's two extensions where the last one is executable). From a package point of view things are being done correctly. From a Shimgen point of view things are being done correctly.

**Comment by ba-tno** [comment]
Thanks for the quick reply. I sort of suspected this, but given I have no control over McAfee I thought I would try this route. But I understand it's far fetched and very niche, so I'll stick to my current workaround.

**Comment by pauby** [comment]
If it was many virus scanners, then I think it would be reasonable for us to look at it as part of Chocolatey Shimgen.

Is there no way to turn this off or exclude folders in McAfee?

**Comment by ba-tno** [comment]
> Is there no way to turn this off or exclude folders in McAfee?  

No way for me at least. In the corporate environment I cannot request exceptions without a valid reason. Unfortunately "I have to manually rename the shimfile after every update" is not a valid reason.
