### ISSUE TITLE
(vagrant) Incorrect checksums

### ISSUE THREAD

**Issue by seeker** [chocolatey-community/chocolatey-coreteampackages#1696]
## Expected Behavior
Vagrant package should install or upgrade without issue.

## Current Behavior
Vagrant package install or upgrade fails due checksum mismatch.

## Possible Solution
Update package to use the correct hashes found in [vagrant_2.2.18_SHA256SUMS](https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_SHA256SUMS), link is listed at the bottom of the Vagrant [download page](https://www.vagrantup.com/downloads).

## Steps to Reproduce (for bugs)
1. Attempt to install or upgrade vagrant
2. Will fail with checksum mismatch:
```
Error - hashes do not match. Actual value was '8CE913BEE9DEBCBF39F313F4255E56F37DAC5281CD62458C0C0040E5C76EE93E'.
ERROR: Checksum for 'X:\tmp\chocolaty-cache\vagrant\2.2.18\vagrant_2.2.18_x86_64.msi' did not meet 'aed44d72e72d2183354c7e2e0f6118e289becba0491a67eb2e5551701b70d359' for checksum type 'sha256'.
```

## Context
Minor annoyance as it breaks automated updates and requires manually specifying the the correct checksum with `--checksum`

## Your Environment
* Package Version used: 2.2.18
* Operating System and version: Windows 10 20H2
* Chocolatey version: 0.10.15
* Install/uninstall gist: `choco upgrade vagrant -y`

**Comment by AdmiringWorm** [comment]
Looks like they have silently updated the installers, I'll queue a new fix version of the Vagrant package to be uploaded to the community repository, and a new version should hopefully be available in a few hours.

**Comment by AdmiringWorm** [comment]
A new version has been queued and will be pushed to the community repository. There will be a few hours until it becomes available for normal consumption.
