### ISSUE TITLE
(K9s) package no longer updated

### ISSUE THREAD

**Issue by derailed** [chocolatey-community/chocolatey-coreteampackages#1712]
## Current Behavior

A lag has been reported in the K9s user community regarding an issue with this choco package release. The current released version of K9s is 0.24.15 but it seems one can only upgrade to 0.24.10. 

I am not the original author here, but I would appreciate some insight or what I can do to ensure this gets updated in this repo.

Thank you all for your time and consideration!

## Steps to Reproduce (for bugs)

1. choco upgrade k9s => yields 0.24.10 but should be 0.24.15
2.
3.
4.

## Context

Can no longer update k9s installation

## Your Environment

* Package Version used: 0.24.10
* Operating System and version: Windows 10
* Chocolatey version:  latest
* Install/uninstall gist:

**Comment by pauby** [comment]
Fixed in #1713
