### ISSUE TITLE
(paint.net) Failed to upgrade paint.net package due to outdated download link

### ISSUE THREAD

**Issue by Some-Dood** [chocolatey-community/chocolatey-coreteampackages#1715]
Since the recent release of [Paint.NET 4.3](https://blog.getpaint.net/2021/09/22/paint-net-4-3-is-now-available/), the old [DotPdn download link](https://www.dotpdn.com/downloads/pdn.html) no longer works. In particular, the `update.ps1` script assumes the following download link (which is no longer the case):

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/862e464bee75578b09e279beb8af58e081c31d0f/automatic/paint.net/update.ps1#L17

## Expected Behavior

The `update.ps1` should use the new download link format.

## Current Behavior

Since the link format has changed, the update script results in a `404 Not Found` error.

## Possible Solution

The fix _should_ be quite trivial. I believe we only have to change the `$urlString` to `https://www.dotpdn.com/files/paint.net.$version.install.anycpu.web.zip`.

## Context
I encountered this error when I suspected that the automatic packages could not detect the latest Paint.NET version when I ran `choco upgrade`. Sure enough, when checking the [Update Status Page](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#paintnet), the reported `404 Not Found` error was the culprit.

## Your Environment

* Package Version used: 4.2.16
* Operating System and version: Windows 10 (21H1)
* Chocolatey version: 0.11.1

**Comment by majkinetor** [comment]
Changing the link will not solve the issue completely - during installation user input is required. The package also doesn't require dotNet any more as dependency.


After changing link this messages is shown:

![image](https://user-images.githubusercontent.com/85767/134808273-66c6a058-6d5a-4b36-a0d5-01b1da6b9b79.png)

After that it installs OK.

The best option would be to embed the offline installer.

**Comment by Some-Dood** [comment]
> The best option would be to embed the offline installer.

Luckily, these binaries are [available on GitHub](https://github.com/paintdotnet/release/releases)! I suppose the update logic should now [ping the GitHub API](https://api.github.com/repos/paintdotnet/release/releases) rather than the dotPDN page to retrieve the latest binaries.

**Comment by majkinetor** [comment]
Thanks for the help. Its up now:

- https://community.chocolatey.org/packages/paint.net/4.3
