### ISSUE TITLE
(python3) choco install python3 didn't install pip

### ISSUE THREAD

**Issue by weeix** [chocolatey-community/chocolatey-coreteampackages#1716]
## Expected Behavior

`pip -V` displays pip's version

## Current Behavior
```
$ python -V
Python 3.9.7
$ pip -V
bash: pip: command not found
```

## Steps to Reproduce (for bugs)

1. `choco install -y python3`
2. Re-open terminal
3. Type `pip -V`

## Context

I'm trying to install packages using pip.

## Your Environment

* Package Version used: python3 3.9.7
* Operating System and version: Windows v 10.0.19043.0
* Chocolatey version: 0.11.2
* Install/uninstall gist: https://gist.github.com/weeix/ab7be2c0e445fe86290b6fe2f5a4b35a

**Comment by weeix** [comment]
Solved by these steps:

1. `choco uninstall -y python3`
2. Download installer from https://www.python.org/downloads
3. Double-click the installer, choose "Repair"
3. Double-click the installer again, choose "Uninstall"
4. `choco install -y python3`

**Comment by hannah23280** [comment]
> Solved by these steps:
> 
> 1. `choco uninstall -y python3`
> 2. Download installer from https://www.python.org/downloads
> 3. Double-click the installer, choose "Repair"
> 4. Double-click the installer again, choose "Uninstall"
> 5. `choco install -y python3`

Why would such steps be needed?   If i would directly download the installer from python website, i would not even use choco in the first place
