### ISSUE TITLE
Migration of packages from ferventcoder's repository

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-coreteampackages#900]
I'm opening this issue for tracking purposes and for having a list to work against for packages that should/could be migrated from @ferventcoder's repository.
The repo is located at:
https://github.com/ferventcoder/chocolatey-packages

The list is as following:

- [x] [1password](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/1password) *High Priority*
- [x] [7zip.install-beta](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/7zip.install-beta) *Should be easy enough, now that we have streams*
- [ ] [CloudBerryExplorer.S3](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/CloudBerryExplorer.S3)
- [ ] [Compass](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/Compass)
- [ ] [PhantomJS](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/PhantomJS) *Priority?*
- [ ] [StExBar](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/StExBar)
- [ ] [VirtualCloneDrive](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/VirtualCloneDrive)
- [x] [Yeoman](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/Yeoman) Deprecated. Yo already here
- [ ] [adobereader](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/adobereader)
- [ ] [anyvideoconverter](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/anyvideoconverter)
- [ ] [appharbordcli.install](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/appharborcli.install)
- [ ] [attributechanger](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/attributechanger)
- [ ] [expresso](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/expresso)
- [ ] [filezilla.commandline](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/filezilla.commandline)
- [ ] [filezilla.server](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/filezilla.server)
- [x] [filezilla](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/filezilla)
- [ ] [fluffyapp](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/fluffyapp)
- [ ] [foobar2000](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/foobar2000)
- [x] [gitextensions](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/gitextensions)
- [ ] [googledrive](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/googledrive) *Is it still supported?*
- [ ] [grepwin](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/grepwin)
- [ ] [httrack.app](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/httrack.app)
- [ ] [httrack.tool](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/httrack.tool)
- [ ] [httrack](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/httrack)
- [ ] [jetty](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/jetty)
- [ ] [jruby](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/jruby)
- [x] [ketarin](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/ketarin) *Yes, we should keep the **competitor** updated*
- [x] [maxthon.commandline](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/maxthon.commandline) *Personal Priority*
- [ ] [maxthon.install](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/maxthon.install)
- [ ] [miranda](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/miranda)
- [x] [mono](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/mono) *High Priority*
- [ ] [mysql](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/mysql)
- [ ] [netbalancer](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/netbalancer)
- [ ] [nodejs.commandline](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/nodejs.commandline) *MAYBE? Is there still a portable edition of this one?*
- [ ] [nodejs.commandline.lts](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/nodejs.commandline.lts) **See above**
- [X] [nodejs.install.lts](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/nodejs.install.lts) *Already supported by the way of streams*
- [x] [pip](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/pip) *Deprecated, comes with python*
- [ ] [pngoptimizer.commandline](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/pngoptimizer.commandline)
- [ ] [pngoptimizer](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/pngoptimizer)
- [ ] [postgresql.v8](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/postgresql.v8) *High Priority*
- [ ] [postgresql.v9](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/postgresql.v9) *High Priority*
- [ ] [pspad](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/pspad)
- [ ] [puppet-agent.portable](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/puppet-agent.portable)
- [ ] [puppet-agent](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/puppet-agent) *High Priority*
- [ ] [puppet](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/puppet)
- [x] ~~[resharper](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/resharper)~~ maintained by JetBrains
- [x] [skype](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/skype) [_Hi priority_]
- [ ] [sliksvn](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/sliksvn)
- [x] [sqlite.analyzer](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/sqlite.analyzer)   [ contained in sqlite ]
- [x] [sqlite.shell](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/sqlite.shell)    [ contained in sqlite ]
- [x] [sqliteadmin](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/sqliteadmin)    [ contained in sqlite ]
- [ ] [sumatrapdf.commandline](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/sumatrapdf.commandline)
- [ ] [sumatrapdf.install](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/sumatrapdf.install)
- [ ] [sumatrapdf](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/sumatrapdf)
- [ ] [vim](https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/vim)

Some of the above may not necessarily need to be converted to AU automatic packages, but can be changed to manual packages.

EDIT:
Updated with link to repository, just in case.

**Comment by pascalberger** [comment]
Ferventcoders Yeoman is already moved to this repository: [yo](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/yo)

**Comment by majkinetor** [comment]
all sqlite stuff is now under single sqlite package

**Comment by gep13** [comment]
@AdmiringWorm historically, there were two fiddler packages, because one (fiddler) specifically targetted .Net Framework 2.0.  Where as the other (fiddler4) targetted .Net Framework.  This may no longer be important.

**Comment by pascalberger** [comment]
> pip Deprecated, comes with nodejs
I don't think thats true. pip is the python package manager (npm is the bundled node package manager)

**Comment by AdmiringWorm** [comment]
@gep13 yeah, I'm not sure if it's important anymore or not, but it should be updated with checksums anyhow.

@pascalberger Yeah, that isn't true, it is included with python, not nodejs. Huge typo on my part

**Comment by ferventcoder** [comment]
ReSharper is now maintained by the ReSharper team.

**Comment by ferventcoder** [comment]
The 7zip beta, not sure it's important anymore.

**Comment by AdmiringWorm** [comment]
> The 7zip beta, not sure it's important anymore.

probably not that important, but it could still be added as an additional stream on the existing 7zip package.
I don't think it would hurt too much to have it though

**Comment by ferventcoder** [comment]
@AdmiringWorm FYI, 1password v4 and v6 are nearly two different products. If we have a v6, there needs to be a 1password4 package.

**Comment by AdmiringWorm** [comment]
@ferventcoder well, we can certainly create a package solely for that version.
I won't be able to look at that today though, as I'll be gone the whole day, but I'll try to look into it later this week

**Comment by majkinetor** [comment]
I think we should close this. Number of most important packages are already migrated, vast majority of what is left is either already taken by somebody else or not updated any more or not used any more or not requested in comments etc.

Personally I think that only the following should be done:

- [ ] mysql
- [ ] filezilla.server
- [ ] postgresql 
- [ ] puppet
- [ ] pngoptimzer

and I will probably do them all in the future. 

In any way, I don't think that we should keep this open, it will stay here forever basically like it is always the case with huge issues like this one.

**Comment by AdmiringWorm** [comment]
I'm sorry, but I disagree. IMO it's still useful to have this open.
Originally, it was the intention of migration all of @ferventcoder's packages to this repository, otherwise it wouldn't be a need to create this issue.

**Comment by majkinetor** [comment]
> Originally, it was the intention of migrating all of @ferventcoder's packages to this repository, otherwise it wouldn't be a need to create this issue.

I am aware of your original intention (not mine). I think it was bad decision then to create such massive ticket that probably requires years to resolve fully, if it ever gets resolved.  But I didn't want to rant then, I always like to give chance. Its soon almost a year old without any activity for ~6mo, and with diminishing return, it's not hard to extrapolate how long we will have it here open.  Not to mention, ALL tickets have a lifetime here as per guidelines, this one included and should already have 'pending closure' tag.

We are not here to migrate random third party repositories - maintaining this repository is job for itself. - if you didn't notice issues started to pile up, and we still have 0 new maintainers. 

It's not particularly important who's repository is it. If you want to do this, you can keep private notes on it and create issue/PR here at the moment you choose to do some actual work . Otherwise, ticketing system will become huge hole of random tickets that scratch particular itch that somebody had once and that doesn't inspire confidence to any potential new comers - it reflects that we can't cope with the demand here, that we don't know how to resolve priorities and assign resources we have at the moment. 

Having issues like this is total anti-pattern in project management. I care about this repository, and others can do on their whatever they want. Its probably for the best we move this ticket to ferventcoder's repository, since that is the place where it should have been originally created. Imagine everybody starts to create massive migration tickets here ?

**A question for everybody** - would you rather have huge package repository that isn't maintained and presents bad public image for most-used packages on the public gallery, or smaller set of packages that always work and are polished and maintained all the time ? First time I came here, it was case one. We worked very hard to move it to the case 2.
